kotlinx-coroutines-nio/src/test/kotlin/kotlinx/coroutines/experimental/nio/AsyncIOTest.kt
=> Use available port instead of a random port

reactive/kotlinx-coroutines-rx1/src/main/kotlin/kotlinx/coroutines/experimental/rx1/RxAwait.kt, reactive/kotlinx-coroutines-rx1/src/test/kotlin/kotlinx/coroutines/experimental/rx1/ObservableSingleTest.kt
=> Implement awaitFirstOrDefault for RxJava1

README.md, pom.xml, reactive/kotlinx-coroutines-reactor/README.md, reactive/kotlinx-coroutines-reactor/pom.xml, reactive/kotlinx-coroutines-reactor/src/main/kotlin/kotlinx/coroutines/experimental/reactor/Convert.kt, reactive/kotlinx-coroutines-reactor/src/main/kotlin/kotlinx/coroutines/experimental/reactor/Flux.kt, reactive/kotlinx-coroutines-reactor/src/main/kotlin/kotlinx/coroutines/experimental/reactor/Mono.kt, reactive/kotlinx-coroutines-reactor/src/main/kotlin/kotlinx/coroutines/experimental/reactor/Scheduler.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/Check.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/ConvertTest.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/FluxCompletionStressTest.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/FluxMultiTest.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/FluxSingleTest.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/FluxTest.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/MonoTest.kt, reactive/kotlinx-coroutines-reactor/src/test/kotlin/kotlinx/coroutines/experimental/reactor/SchedulerTest.kt
=> #51 Add support for Reactor.

reactive/kotlinx-coroutines-rx1/README.md, reactive/kotlinx-coroutines-rx1/src/main/kotlin/kotlinx/coroutines/experimental/rx1/RxAwait.kt, reactive/kotlinx-coroutines-rx1/src/test/kotlin/kotlinx/coroutines/experimental/rx1/CompletableTest.kt
=> #49 Rx1 Completable.awaitCompleted implementation.

reactive/kotlinx-coroutines-rx2/README.md, reactive/kotlinx-coroutines-rx2/src/main/kotlin/kotlinx/coroutines/experimental/rx2/RxAwait.kt, reactive/kotlinx-coroutines-rx2/src/main/kotlin/kotlinx/coroutines/experimental/rx2/RxChannel.kt, reactive/kotlinx-coroutines-rx2/src/main/kotlin/kotlinx/coroutines/experimental/rx2/RxConvert.kt, reactive/kotlinx-coroutines-rx2/src/main/kotlin/kotlinx/coroutines/experimental/rx2/RxMaybe.kt, reactive/kotlinx-coroutines-rx2/src/test/kotlin/kotlinx/coroutines/experimental/rx2/Check.kt, reactive/kotlinx-coroutines-rx2/src/test/kotlin/kotlinx/coroutines/experimental/rx2/ConvertTest.kt, reactive/kotlinx-coroutines-rx2/src/test/kotlin/kotlinx/coroutines/experimental/rx2/MaybeTest.kt
=> Add support for Rx2 Maybe.

kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/CompletableDeferred.kt
A "CompletableDeferred" interface with a private implementation.
This allows delegator pattern and future implementations.
=> A "CompletableDeferred" interface with a private implementation (#70)

README.md
Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/103,
suggested by ProGuard team here: https://sourceforge.net/p/proguard/bugs/660/
=> ProGuard config

core/kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/channels/Channels.kt
=> SendChannel.sendBlocking extension method

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt, core/kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/CommonPool.kt
=> Introduce system property to control CommonPool parallelism

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt, common/kotlinx-coroutines-core-common/src/main/kotlin/kotlinx/coroutines/experimental/AbstractContinuation.kt, common/kotlinx-coroutines-core-common/src/main/kotlin/kotlinx/coroutines/experimental/CancellableContinuation.kt, core/kotlinx-coroutines-core/build.gradle, core/kotlinx-coroutines-core/src/test/kotlin/kotlinx/coroutines/experimental/CancellableContinuationExceptionHandlingTest.kt, gradle/compile-jvm.gradle, integration/kotlinx-coroutines-guava/src/test/kotlin/kotlinx/coroutines/experimental/guava/ListenableFutureTest.kt
Consistent cancellation, smoother migration after breaking binary/source compatibility
=> CancellableContinuation improvements

integration/kotlinx-coroutines-guava/src/test/kotlin/kotlinx/coroutines/experimental/guava/ListenableFutureExceptionsTest.kt, integration/kotlinx-coroutines-jdk8/src/main/kotlin/kotlinx/coroutines/experimental/future/Future.kt, integration/kotlinx-coroutines-jdk8/src/test/kotlin/kotlinx/coroutines/experimental/future/FutureExceptionsTest.kt
=> Unwrap exception on CompletionStage#await slow-path to provide consistent results

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-android.txt, binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt, binary-compatibility-validator/reference-public-api/kotlinx-coroutines-javafx.txt, binary-compatibility-validator/reference-public-api/kotlinx-coroutines-swing.txt, core/kotlinx-coroutines-core/src/Builders.kt, ui/kotlinx-coroutines-android/resources/META-INF/services/kotlinx.coroutines.experimental.BlockingChecker, ui/kotlinx-coroutines-android/src/HandlerContext.kt, ui/kotlinx-coroutines-javafx/resources/META-INF/services/kotlinx.coroutines.experimental.BlockingChecker, ui/kotlinx-coroutines-javafx/src/JavaFx.kt, ui/kotlinx-coroutines-javafx/test/JavaFxTest.kt, ui/kotlinx-coroutines-swing/resources/META-INF/services/kotlinx.coroutines.experimental.BlockingChecker, ui/kotlinx-coroutines-swing/src/Swing.kt, ui/kotlinx-coroutines-swing/test/SwingTest.kt
=> Forbid runBlocking in UI dispatchers

common/kotlinx-coroutines-core-common/src/JobSupport.kt, common/kotlinx-coroutines-core-common/test/JobTest.kt
=> Materialize an exception for Job onCancelling handlers

core/kotlinx-coroutines-core/src/EventLoop.kt
=> Remove no longer needed warning suppression

core/kotlinx-coroutines-core/src/scheduling/ExperimentalCoroutineDispatcher.kt, core/kotlinx-coroutines-core/test/scheduling/LimitingCoroutineDispatcherStressTest.kt, core/kotlinx-coroutines-core/test/scheduling/LimitingDispatcherTest.kt, core/kotlinx-coroutines-core/test/scheduling/SchedulerTestBase.kt
=> Provide API to create limited view of experimental dispatcher

core/kotlinx-coroutines-core/src/CoroutineExceptionHandlerImpl.kt
=> Use explicit classloader when loading installed CoroutineExceptionHadler impls

coroutines-guide.md
=> Small improvement in doc

common/kotlinx-coroutines-core-common/src/CoroutineScope.kt, common/kotlinx-coroutines-core-common/test/CoroutineScopeTest.kt
=> Fixed CoroutineScope.plus operator

ui/kotlinx-coroutines-android/animation-app/app/src/main/java/org/jetbrains/kotlinx/animation/Animation.kt
- Updates Android sample/AnimationModel to use structured concurrency
=> Upgrade Android sample to use structured concurrency

common/kotlinx-coroutines-core-common/src/CoroutineScope.kt, common/kotlinx-coroutines-core-common/test/CoroutineScopeTest.kt
=> Implicitly add Job in CoroutineScope constructor if it is missing

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt, core/kotlinx-coroutines-core/src/Executors.kt
=> Restore binary compatibility of Executor.asCoroutineDispatcher

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt, common/kotlinx-coroutines-core-common/src/CoroutineExceptionHandler.kt, common/kotlinx-coroutines-core-common/src/CoroutineScope.kt, common/kotlinx-coroutines-core-common/src/Job.kt, common/kotlinx-coroutines-core-common/src/JobSupport.kt, common/kotlinx-coroutines-core-common/src/Supervisor.kt, common/kotlinx-coroutines-core-common/src/internal/Scopes.kt, common/kotlinx-coroutines-core-common/test/JobTest.kt, common/kotlinx-coroutines-core-common/test/ParentCancellationTest.kt, common/kotlinx-coroutines-core-common/test/SupervisorTest.kt, core/kotlinx-coroutines-core/test/WithTimeoutOrNullJvmTest.kt, core/kotlinx-coroutines-core/test/exceptions/JobBasicCancellationTest.kt, core/kotlinx-coroutines-core/test/exceptions/JobExceptionHandlingTest.kt, core/kotlinx-coroutines-core/test/exceptions/JobNestedExceptionsTest.kt, core/kotlinx-coroutines-core/test/exceptions/ProduceExceptionsTest.kt, core/kotlinx-coroutines-core/test/exceptions/WithContextExceptionHandlingTest.kt, core/kotlinx-coroutines-core/test/guide/example-supervision-01.kt, core/kotlinx-coroutines-core/test/guide/example-supervision-02.kt, core/kotlinx-coroutines-core/test/guide/example-supervision-03.kt, core/kotlinx-coroutines-core/test/guide/test/ExceptionsGuideTest.kt, docs/coroutines-guide.md, docs/exception-handling.md
Documentation for Job spells the difference between the regular job
and the supervisor job.
Fixes #576
=> SupervisorJob & supervisorScope

common/kotlinx-coroutines-core-common/src/Dispatched.kt, common/kotlinx-coroutines-core-common/test/ExperimentalDispatchModeTest.kt
=> Check cancellation when starting unconfined coroutine

core/kotlinx-coroutines-core/src/scheduling/CoroutineScheduler.kt, core/kotlinx-coroutines-core/src/scheduling/Dispatcher.kt, core/kotlinx-coroutines-core/test/scheduling/CoroutineSchedulerCloseStressTest.kt
=> Fix shutdown sequence for CoroutineScheduler's views

ui/coroutines-guide-ui.md
Update children of a coroutine documentation link
=> Update link in coroutines-guide-ui.md

common/kotlinx-coroutines-core-common/src/CancellableContinuation.kt
Let's update documentation on 1.0.1 and provide a more precise mechanism (via another intrinsic) separately.
=> Clarify docs for CancellableContinuation

reactive/kotlinx-coroutines-rx2/src/RxFlowable.kt, reactive/kotlinx-coroutines-rx2/src/RxObservable.kt, reactive/kotlinx-coroutines-rx2/src/RxSingle.kt
=> Align rxFlowable nullability with the Reactive Streams spec

docs/basics.md, docs/cancellation-and-timeouts.md, docs/channels.md, docs/composing-suspending-functions.md, docs/coroutine-context-and-dispatchers.md, docs/exception-handling.md, docs/select-expression.md, docs/shared-mutable-state-and-concurrency.md
Need for Kotlin PDF documentation.
=> docs: make `Table of contents` as bold

kotlinx-coroutines-core/common/test/WithContextTest.kt
The issue previously reference was marked as fixed for one of the two problems it was about,
and a new one has been created for the remaining issue that is relevant here.
=> Update named arguments referenced issue

README.md
Fix a typo in the Multiplatform section
=> Fix a typo in main README.md

kotlinx-coroutines-core/common/test/AwaitTest.kt
Remove unnecessary semicolons from AwaitTest.kt
=> Remove unnecessary semicolon

license/NOTICE.txt
`kotlix` -> `kotlinx`
Should I send this PR to develop branch?
=> Fix typo in NOTICE

docs/exception-handling.md
=> grammatical tweaks

kotlinx-coroutines-core/common/src/flow/Builders.kt
* Detailed introductory paragraph
* Explanation on the meaning of "cold flow"
* Better self-contained example
=> Improve flowViaChannel docs

README.md
=> Fix link to proguard rules file

binary-compatibility-validator/test/PublicApiTest.kt, gradle.properties
AtomicFu version 0.12.5
This should really fix processing of class files
Fixes #1116
Fixes #1064
=> AtomicFu version 0.12.5

gradle/node-js.gradle, gradle/publish-npm-js.gradle
* Postpone version expansion on after evaluate phase
Fixes #1118
=> Fix npm publication

kotlinx-coroutines-core/common/src/flow/operators/Transform.kt
=> Rename transform parameters for consistency with stdlib

kotlinx-coroutines-core/common/src/JobSupport.kt, kotlinx-coroutines-core/common/src/flow/operators/Delay.kt, kotlinx-coroutines-core/common/test/selects/SelectLoopTest.kt
=> Select join fixed

kotlinx-coroutines-test/README.md
=> Fixes kotlin-coroutines-test TestCoroutineDispatcher docs

binary-compatibility-validator/test/PublicApiTest.kt, gradle.properties
* Updated to 0.12.7 version of atmoicfu with fixes.
* Added test that that is no references to atomicfu in any of the
resulting class files.
=> Ensure that there are no references to atomicfu in classes

kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt, kotlinx-coroutines-core/common/src/channels/ConflatedBroadcastChannel.kt, kotlinx-coroutines-core/common/src/flow/internal/NullSurrogate.kt, kotlinx-coroutines-core/common/src/flow/operators/Delay.kt, kotlinx-coroutines-core/common/src/flow/operators/Distinct.kt, kotlinx-coroutines-core/common/src/flow/operators/Merge.kt, kotlinx-coroutines-core/common/src/flow/operators/Zip.kt, kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt, kotlinx-coroutines-core/common/src/internal/Symbol.kt
* JvmStatic on unbox did not make sense anyway
* unbox is useful for other symbols
=> Consolidate NullSurrogate with Symbol

kotlinx-coroutines-core/native/src/Debug.kt
=> Use identity hash code on K/N for debug strings

kotlinx-coroutines-core/native/src/Builders.kt, kotlinx-coroutines-core/native/test/DelayExceptionTest.kt
=> Use nanosleep in runBlocking's delay on Native

kotlinx-coroutines-core/common/src/flow/Flow.kt, kotlinx-coroutines-core/common/src/flow/Migration.kt, kotlinx-coroutines-core/common/src/flow/operators/Context.kt, kotlinx-coroutines-core/common/test/flow/operators/CombineLatestTest.kt, kotlinx-coroutines-core/common/test/flow/operators/DebounceTest.kt, kotlinx-coroutines-core/common/test/flow/operators/FlatMapBaseTest.kt, kotlinx-coroutines-core/common/test/flow/operators/FlowContextTest.kt, kotlinx-coroutines-core/common/test/flow/operators/FlowWithTest.kt, kotlinx-coroutines-core/common/test/flow/operators/SampleTest.kt, kotlinx-coroutines-core/common/test/flow/operators/ZipTest.kt
=> Deprecate flowWith operator

kotlinx-coroutines-core/common/src/flow/Builders.kt
=> Fix flowViaChannel closing immediately.

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt, kotlinx-coroutines-core/common/src/Annotations.kt, kotlinx-coroutines-core/common/src/flow/Flow.kt, kotlinx-coroutines-core/common/src/flow/Migration.kt, kotlinx-coroutines-core/common/src/flow/internal/ChannelFlow.kt, kotlinx-coroutines-core/common/src/flow/internal/NopCollector.kt, kotlinx-coroutines-core/common/src/flow/operators/Context.kt, kotlinx-coroutines-core/common/src/flow/operators/Errors.kt, kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt, kotlinx-coroutines-core/common/test/TestBase.common.kt, kotlinx-coroutines-core/common/test/flow/operators/CatchTest.kt, kotlinx-coroutines-core/common/test/flow/operators/DropTest.kt, kotlinx-coroutines-core/common/test/flow/operators/FilterTest.kt, kotlinx-coroutines-core/common/test/flow/operators/MapNotNullTest.kt, kotlinx-coroutines-core/common/test/flow/operators/MapTest.kt, kotlinx-coroutines-core/common/test/flow/operators/OnEachTest.kt, kotlinx-coroutines-core/common/test/flow/operators/RetryTest.kt, kotlinx-coroutines-core/common/test/flow/operators/ScanTest.kt, kotlinx-coroutines-core/common/test/flow/operators/TakeTest.kt, kotlinx-coroutines-core/common/test/flow/operators/TakeWhileTest.kt
Flow exceptions handling facilities:
* Flow documentation introduces and explains "exception transparency"
concept in detail.
* Introduce exception handling operators:
* catch intermediate operator.
* retry and retryWhen intermediate operators.
* collect() without lambda terminal operator.
* onErrorXxx operators deprecated and moved to migration file when
it was appropriate.
=> Flow exceptions handling facilities

kotlinx-coroutines-core/common/test/flow/operators/CatchTest.kt
Amazingly, it works like a charm, but a test is needed to make
sure it will not get broken in the future.
=> Added a test that ensures proper context in catch/flowOn combinations

kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt, kotlinx-coroutines-core/common/src/Debug.common.kt, kotlinx-coroutines-core/common/src/Dispatched.kt, kotlinx-coroutines-core/common/src/EventLoop.common.kt, kotlinx-coroutines-core/common/src/JobSupport.kt, kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt, kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt, kotlinx-coroutines-core/common/src/channels/ConflatedBroadcastChannel.kt, kotlinx-coroutines-core/common/src/flow/internal/ChannelFlow.kt, kotlinx-coroutines-core/common/src/flow/operators/Merge.kt, kotlinx-coroutines-core/common/src/internal/Atomic.kt, kotlinx-coroutines-core/common/src/internal/SegmentQueue.kt, kotlinx-coroutines-core/common/src/selects/Select.kt, kotlinx-coroutines-core/common/src/sync/Mutex.kt, kotlinx-coroutines-core/js/src/Debug.kt, kotlinx-coroutines-core/jvm/src/CoroutineContext.kt, kotlinx-coroutines-core/jvm/src/Debug.kt, kotlinx-coroutines-core/jvm/src/DebugStrings.kt, kotlinx-coroutines-core/jvm/src/DefaultExecutor.kt, kotlinx-coroutines-core/jvm/src/EventLoop.kt, kotlinx-coroutines-core/jvm/src/internal/LockFreeLinkedList.kt, kotlinx-coroutines-core/jvm/src/internal/LockFreeTaskQueue.kt, kotlinx-coroutines-core/jvm/src/internal/ThreadSafeHeap.kt, kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt, kotlinx-coroutines-core/jvm/src/scheduling/WorkQueue.kt, kotlinx-coroutines-core/native/src/Debug.kt, kotlinx-coroutines-core/native/src/EventLoop.kt
Also make sure they are absent on native and JS
=> Rewrite assertions so that they are checked only in debug mode

kotlinx-coroutines-core/common/src/sync/Semaphore.kt, kotlinx-coroutines-core/common/test/sync/SemaphoreTest.kt
Cancellation in `Semaphore` should resume the next waiting acquirer if and only if the canceled request has been resumed under a race. The current implementation _always_ resumes the next waiting acquirer, so that it violates the semaphore contract.
=> Semaphore cancellation bug

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt, kotlinx-coroutines-core/common/src/flow/internal/FlowExceptions.common.kt, kotlinx-coroutines-core/common/src/flow/operators/Limit.kt, kotlinx-coroutines-core/common/src/flow/operators/Transform.kt, kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt, kotlinx-coroutines-core/common/test/flow/operators/IndexedTest.kt
=> withIndex and collectIndexed operators

kotlinx-coroutines-core/common/src/sync/Semaphore.kt
* Improved documentation
* Detailed error messages
=> Improve Semaphore API

kotlinx-coroutines-core/common/src/flow/operators/Zip.kt, kotlinx-coroutines-core/common/test/flow/operators/CombineTest.kt
edit: forcepushed with correct commit message
=> flow: fix recursion in combineTransform<T1, T2, R>()

binary-compatibility-validator/build.gradle, build.gradle, gradle.properties, gradle/dokka.gradle, gradle/publish-bintray.gradle, gradle/publish-npm-js.gradle, gradle/wrapper/gradle-wrapper.properties, kotlinx-coroutines-core/build.gradle, kotlinx-coroutines-core/jvm/test/TestBase.kt, kotlinx-coroutines-core/npm/README.md, kotlinx-coroutines-core/npm/package.json, kotlinx-coroutines-debug/build.gradle
* Gradle metadata format version 1.0 (stable)
* Using Gradle publish task for publishing
* Empty javadoc files (only) are published
=> Gradle version 5.6.1

kotlinx-coroutines-debug/test/CoroutinesDumpTest.kt
Fixed incorrect usage of Object.await/notify idiom
Fixes #1513
=> Robust waiting in CoroutinesDumpTest

integration/kotlinx-coroutines-guava/src/ListenableFuture.kt, integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt
=> Properly handle null values in ListenableFuture

kotlinx-coroutines-core/common/src/Await.kt, kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt, kotlinx-coroutines-core/common/src/EventLoop.common.kt, kotlinx-coroutines-core/common/src/JobSupport.kt, kotlinx-coroutines-core/common/src/channels/ArrayBroadcastChannel.kt, kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt, kotlinx-coroutines-core/common/src/selects/Select.kt
In preparation to native multithreading.
=> Replace all volatiles with atomics in common code

docs/flow.md
=> Fix example-flow-14 docs to show expected exception in text

kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt
=> All ArrayChannel.size accesses should be under the channel lock

kotlinx-coroutines-core/common/src/flow/internal/Combine.kt
* Avoid linear complexity for emits
* Extract slow-path to the separate method
* Reduce bytecode size
=> Slightly optimize combine operator

kotlinx-coroutines-core/jvm/src/Dispatchers.kt
Reference: https://youtrack.jetbrains.com/issue/KT-34671
=> Clarify documentation around Dispatcher.IO parallelism

gradle/dokka.gradle, ui/kotlinx-coroutines-android/build.gradle
It should speed up gradle configuration phase
=> Gradle: Don't resolve classpath during configuration phase

kotlinx-coroutines-core/build.gradle
=> Update module name for kotlinx-coroutines-core-common artifact

README.md, kotlinx-coroutines-debug/README.md, kotlinx-coroutines-debug/api/kotlinx-coroutines-debug.api, kotlinx-coroutines-debug/src/AgentPremain.kt, kotlinx-coroutines-debug/src/CoroutineInfo.kt, kotlinx-coroutines-debug/src/DebugProbes.kt, kotlinx-coroutines-debug/src/internal/DebugProbesImpl.kt, kotlinx-coroutines-debug/src/junit4/CoroutinesTimeout.kt, kotlinx-coroutines-debug/test/DebugTestBase.kt, kotlinx-coroutines-debug/test/DumpWithoutCreationStackTraceTest.kt, kotlinx-coroutines-debug/test/StracktraceUtils.kt, kotlinx-coroutines-debug/test/junit4/CoroutinesTimeoutDisabledTracesTest.kt, kotlinx-coroutines-debug/test/junit4/CoroutinesTimeoutTest.kt, kotlinx-coroutines-debug/test/junit4/TestFailureValidation.kt
=> Debugger improvements

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api, kotlinx-coroutines-core/common/src/Delay.kt, kotlinx-coroutines-core/common/src/Timeout.kt, kotlinx-coroutines-core/common/src/flow/operators/Delay.kt, kotlinx-coroutines-core/common/src/selects/Select.kt, kotlinx-coroutines-core/common/test/DelayDurationTest.kt, kotlinx-coroutines-core/common/test/WithTimeoutDurationTest.kt, kotlinx-coroutines-core/common/test/WithTimeoutOrNullDurationTest.kt, kotlinx-coroutines-core/common/test/flow/operators/DebounceTest.kt, kotlinx-coroutines-core/common/test/flow/operators/SampleTest.kt, kotlinx-coroutines-core/common/test/selects/SelectTimeoutDurationTest.kt
Fixed code-style & API dump. See #1811
=> #1811 fixup

docs/coroutine-context-and-dispatchers.md, kotlinx-coroutines-core/common/src/CoroutineScope.kt, kotlinx-coroutines-core/jvm/test/guide/example-context-10.kt, ui/coroutines-guide-ui.md
=> Update CoroutineScope docs

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Projects.kt
=> Kotlin DSL. Add version extension

ui/kotlinx-coroutines-swing/build.gradle.kts
=> Kotlin DSL - 'swing'

kotlinx-coroutines-test/build.gradle, kotlinx-coroutines-test/build.gradle.kts
=> Kotlin DSL - 'test'

build.gradle, settings.gradle
=> Plugin versions in 'plugins' block

.gitignore, .idea/codeStyleSettings.xml, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml
* Using Kotlin official style
* Start imports for all packages
* Continuation indent size = 4
=> IDEA Project code-style settings

kotlinx-coroutines-core/build.gradle, kotlinx-coroutines-core/jvm/src/debug/AgentPremain.kt
Testing: manual
Additionally, I plan to release (to my bintray) current version and ask someone to verify everything works in a more complicated projects
=> Add compileOnly android annotations and suppress lint for agent premain

benchmarks/build.gradle.kts, benchmarks/src/jmh/kotlin/benchmarks/flow/FlowFlattenMergeBenchmark.kt, benchmarks/src/jmh/kotlin/benchmarks/flow/NumbersBenchmark.kt, benchmarks/src/jmh/kotlin/benchmarks/flow/TakeBenchmark.kt, benchmarks/src/jmh/kotlin/benchmarks/flow/scrabble/FlowPlaysScrabbleBase.kt, benchmarks/src/jmh/kotlin/benchmarks/flow/scrabble/SaneFlowPlaysScrabble.kt, settings.gradle
=> Restore java configuration for 'benchmarks'

settings.gradle
* Fix project import in IDEA for JDK < 11
=> Include 'javafx' subproject for JDK 11+

build.gradle, gradle/compile-jvm-multiplatform.gradle, gradle/compile-jvm.gradle
=> Remove unused repositories

buildSrc/src/main/kotlin/UnpackAar.kt, integration/kotlinx-coroutines-play-services/build.gradle
=> Separate 'UnpackAar' action

buildSrc/src/main/kotlin/RunR8.kt, ui/kotlinx-coroutines-android/build.gradle.kts
=> Separate 'RunR8' task

benchmarks/build.gradle.kts, buildSrc/src/main/kotlin/MavenCentral.kt, buildSrc/src/main/kotlin/Properties.kt
=> Non-deprecated 'jmhJar' configuration

docs/shared-mutable-state-and-concurrency.md, kotlinx-coroutines-core/jvm/test/guide/example-sync-03.kt
=> Fixed val counter AtomicInteger in shared state example

docs/flow.md
Corrected word omission in sentence.
=> Fix word omission

kotlinx-coroutines-core/build.gradle
=> Fix jvm dependency on Android annotations

kotlinx-coroutines-core/common/src/Job.kt, kotlinx-coroutines-core/common/test/EmptyContext.kt, kotlinx-coroutines-core/common/test/EnsureActiveTest.kt, kotlinx-coroutines-core/common/test/flow/FlowInvariantsTest.kt, kotlinx-coroutines-core/jvm/test/flow/FlowCancellationTest.kt
=> Fix ensureAction to work in the empty context case

docs/basics.md, kotlinx-coroutines-core/jvm/test/guide/example-basic-08.kt
=> Increase timeout in the example to make sure it fails with threads

reactive/kotlinx-coroutines-jdk9/api/kotlinx-coroutines-jdk9.api, reactive/kotlinx-coroutines-jdk9/src/ReactiveFlow.kt, reactive/kotlinx-coroutines-reactive/api/kotlinx-coroutines-reactive.api, reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt, reactive/kotlinx-coroutines-reactive/test/FlowAsPublisherTest.kt, reactive/kotlinx-coroutines-reactor/api/kotlinx-coroutines-reactor.api, reactive/kotlinx-coroutines-reactor/src/ReactorFlow.kt, reactive/kotlinx-coroutines-reactor/test/FlowAsFluxTest.kt, reactive/kotlinx-coroutines-rx2/api/kotlinx-coroutines-rx2.api, reactive/kotlinx-coroutines-rx2/src/RxConvert.kt, reactive/kotlinx-coroutines-rx2/test/FlowAsFlowableTest.kt, reactive/kotlinx-coroutines-rx2/test/FlowAsObservableTest.kt, reactive/kotlinx-coroutines-rx3/api/kotlinx-coroutines-rx3.api, reactive/kotlinx-coroutines-rx3/src/RxConvert.kt, reactive/kotlinx-coroutines-rx3/test/FlowAsFlowableTest.kt, reactive/kotlinx-coroutines-rx3/test/FlowAsObservableTest.kt
=> Support context in Flow.asPublisher and similar methods

kotlinx-coroutines-core/jvm/test/internal/ConcurrentWeakMapTest.kt
Root cause: https://youtrack.jetbrains.com/issue/KT-40943
=> Fix sporadic ConcurrentWeakMapTest failures

gradle/compile-jvm.gradle, kotlinx-coroutines-core/build.gradle
Part of #1938
Related issue - #1983
=> New Kotlin/JVM & Kotlin/Multiplatform plugins

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api, kotlinx-coroutines-core/common/src/flow/operators/Lint.kt
=> Lint settings for 1.4

README.md, docs/basics.md, docs/composing-suspending-functions.md, docs/exception-handling.md, docs/flow.md, gradle.properties
=> Fix doc references that differ only in case (function vs interface)

CONTRIBUTING.md
Write the test the reproduces the bug. >> Write the test that reproduces the bug.
=> Grammar correction on the 'CONTRIBUTION.md' file

kotlinx-coroutines-core/common/src/flow/Channels.kt
=> Fix replacement for deprecated broadcastIn operator

kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro, kotlinx-coroutines-test/resources/META-INF/proguard/coroutines.pro
=> Fix incorrect ProGuard rules that allowed shrinking volatile felds

kotlinx-coroutines-core/jvm/src/Builders.kt
Signed-off-by: slavon <v.badalyan@open-bs.ru>
=> Using the same logic as packNanos in the code below

kotlinx-coroutines-core/common/src/Yield.kt
=> Clarify yield documentation

gradle/compile-js-multiplatform.gradle
=> Remove workarounds for Kotlin 1.3

kotlinx-coroutines-core/common/src/flow/Builders.kt
Successfully ran `./gradlew knit`
=> Fix typo in flow/Builders.kt

docs/topics/coroutines-basic-jvm.md
since it will be removed in Kotlin 1.5.0
=> update: delete -Xcoroutines flag 

kotlinx-coroutines-core/common/test/flow/VirtualTime.kt, kotlinx-coroutines-test/src/internal/MainTestDispatcher.kt
Fix for the latest Kotlin compiler version
=> Fix minBy/maxBy usages

kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
=> Mention benign data-race in getResult

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api, kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt, kotlinx-coroutines-core/common/test/flow/terminal/LastTest.kt
=> Introduce Flow.last and Flow.lastOrNull operators

kotlinx-coroutines-core/jvm/test/IntellijIdeaDebuggerEvaluatorCompatibilityTest.kt
=> Test invariant that IDEA evaluator depends on

CHANGES.md, README.md, RELEASE.md, gradle.properties, site/deploy.sh
* Properly handle files with spaces in deploy.sh
* Update version shield
=> Post-release cleanup

docs/kc.tree
add a redirect config for the previously renamed file `basics.md` to `coroutines-basics.md`
=> update: update kc.tree

docs/topics/compatibility.md
=> Docs: Replace deprecated UseExperimental annotation

CONTRIBUTING.md
This PR updates the link to Knit in `CONTRIBUTING.md`.
=> Update link to Knit in CONTRIBUTING.md

docs/topics/coroutines-basics.md, kotlinx-coroutines-core/jvm/test/guide/example-basic-04.kt
=> Fix examples in coroutine-basics.md

docs/topics/shared-mutable-state-and-concurrency.md
Using Dispatchers.Default we can make the coroutines run *parallely*.
=> Use correct wording

README.md, gradle.properties, gradle/compile-js-multiplatform.gradle, kotlinx-coroutines-core/common/src/Delay.kt, kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt, kotlinx-coroutines-core/common/src/channels/Deprecated.kt, kotlinx-coroutines-core/common/src/flow/SharingStarted.kt, kotlinx-coroutines-core/common/src/flow/operators/Lint.kt, kotlinx-coroutines-core/jvm/src/channels/Actor.kt, kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt
=> Update Kotlin to 1.5.20

kotlinx-coroutines-core/js/src/CoroutineContext.kt
Fixes #2843 
I tested the changes with React Native on an Android device and in Debug mode with Chrome
=> fix default dispatcher for react native

README.md
Adjust documented Kotlin version to 1.5.30 according to rest of docu
=> Documentation: Kotlin 1.5.30

kotlinx-coroutines-core/common/src/Delay.kt, kotlinx-coroutines-core/common/src/Timeout.kt, kotlinx-coroutines-core/common/src/flow/SharingStarted.kt, kotlinx-coroutines-core/common/src/flow/operators/Delay.kt, kotlinx-coroutines-core/common/src/selects/Select.kt, kotlinx-coroutines-core/common/test/DelayDurationTest.kt, kotlinx-coroutines-core/common/test/WithTimeoutDurationTest.kt, kotlinx-coroutines-core/common/test/WithTimeoutOrNullDurationTest.kt, kotlinx-coroutines-core/common/test/flow/operators/DebounceTest.kt, kotlinx-coroutines-core/common/test/flow/operators/SampleTest.kt, kotlinx-coroutines-core/common/test/flow/sharing/SharingStartedWhileSubscribedTest.kt, kotlinx-coroutines-core/common/test/selects/SelectTimeoutDurationTest.kt, kotlinx-coroutines-core/jvm/test/examples/example-delay-duration-01.kt, kotlinx-coroutines-core/jvm/test/examples/example-delay-duration-02.kt, kotlinx-coroutines-core/jvm/test/examples/example-delay-duration-03.kt, kotlinx-coroutines-core/jvm/test/flow/SharedFlowStressTest.kt, kotlinx-coroutines-test/common/test/Helpers.kt
=> Get rid of @ExperimentalTime where it is no longer necessary

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api, kotlinx-coroutines-core/common/src/flow/FlowCollector.kt, kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt
* It also saves us from copy-without-imports problem
Addresses #3037
=> Make FlowCollector fun interface, remove redundant extensions

kotlinx-coroutines-test/jvm/src/migration/TestCoroutineScope.kt
=> Unseal TestCoroutineScope

docs/topics/debugging.md, kotlinx-coroutines-debug/README.md
* Do not mention obsolete gradle-aspectj-android plugin at all
* Fix broken links
Addresses #3060
=> Adjust debugging documentation

kotlinx-coroutines-core/common/src/channels/Channel.kt
onDeliveredElement -> onUndeliveredElement
=> Fix typo: onDeliveredElement

docs/topics/channels.md, docs/topics/exception-handling.md
Just update doc, make code could click and run on [play.kotlinlang.org](https://play.kotlinlang.org)
=> Doc add missing playground runnable comments

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api, kotlinx-coroutines-core/common/src/selects/SelectUnbiased.kt
So it's easier to compare things with #3020
=> Reduce unnecessary @PublishedApi surface of UnbiasedSelectBuilderImpl

kotlinx-coroutines-core/common/src/Delay.kt, kotlinx-coroutines-core/common/src/Timeout.kt
=> Update delay and withTimeout* documentation

kotlinx-coroutines-debug/build.gradle
=> Remove Class-Path attribute from debug JAR

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api, kotlinx-coroutines-core/common/src/flow/operators/Transform.kt, kotlinx-coroutines-core/common/test/flow/operators/FilterTrivialTest.kt
=> Add parametrized Flow#filterIsInstance extension

docs/topics/debug-flow-with-idea.md, docs/topics/flow.md
minor fix for typo and link in documents
=> minor fix for typo and link

reactive/kotlinx-coroutines-reactor/src/Mono.kt, reactive/kotlinx-coroutines-reactor/test/MonoAwaitStressTest.kt
=> Make Mono.awaitSingleOrNull wait for onComplete()

build.gradle
=> Publish empty kotlinx-coroutines-jdk8 artifact

docs/cfg/buildprofiles.xml
To work the Edit page button on the website properly
=> fix: fix property for Edit page button

gradle.properties, js/example-frontend-js/build.gradle.kts, reactive/kotlinx-coroutines-rx3/test/Check.kt
It is updated only in gradle.properties and not in documentation as it's temporary measure to simplify development
=> Update Kotlin to 1.8.0-Beta

kotlinx-coroutines-core/common/src/flow/StateFlow.kt
=> Mention value-based conflation in MutableStateFlow

kotlinx-coroutines-test/common/src/internal/TestMainDispatcher.kt
Proposed fix for #3395 - Capturing the stack frames for both the reader+writer or the
writer+writer, depending upon the scenario.
This results in a thrown exception which looks similar to the following:
```
Dispatchers.Main is used concurrently with setting it
java.lang.IllegalStateException: Dispatchers.Main is used concurrently with setting it
at kotlinx.coroutines.test.internal.TestMainDispatcher$NonConcurrentlyModifiable.concurrentRW(TestMainDispatcher.kt:70)
at kotlinx.coroutines.test.internal.TestMainDispatcher$NonConcurrentlyModifiable.setValue(TestMainDispatcher.kt:84)
at kotlinx.coroutines.test.internal.TestMainDispatcher.resetDispatcher(TestMainDispatcher.kt:40)
at kotlinx.coroutines.test.TestDispatchers.resetMain(TestDispatchers.kt:37)
at …
```
=> NonConcurrentlyModifiable concurrency failures should identify both parties

docs/topics/select-expression.md
looks like `delay()` timings is changed in PR #3387
but same changes were not made in doc and sample code
this PR will fix it
=> minor fix for doc and sample code

docs/topics/shared-mutable-state-and-concurrency.md, kotlinx-coroutines-core/jvm/test/guide/test/SharedStateGuideTest.kt
=> Remove mentions of obsolete actors from our quickstart guide

docs/topics/shared-mutable-state-and-concurrency.md, kotlinx-coroutines-core/common/src/flow/operators/Delay.kt
=> Fix documentation

kotlinx-coroutines-core/common/src/flow/internal/SafeCollector.common.kt, kotlinx-coroutines-core/js/src/flow/internal/SafeCollector.kt, kotlinx-coroutines-core/jvm/src/flow/internal/SafeCollector.kt, kotlinx-coroutines-core/native/src/flow/internal/SafeCollector.kt
The compilation started failing after KT-59739
=> Fix ABSTRACT_MEMBER_NOT_IMPLEMENTED compilation with never Kotlin

buildSrc/src/main/kotlin/CommunityProjectsBuild.kt
=> Fix Typo: CommunityProjectsBuild.kt

docs/topics/coroutine-context-and-dispatchers.md
=> Fix the display of a code snippet on the website

kotlinx-coroutines-core/build.gradle, kotlinx-coroutines-test/build.gradle.kts
=> Remove memoryModel = experimental

kotlinx-coroutines-core/concurrent/src/MultithreadedDispatchers.common.kt, kotlinx-coroutines-core/jvm/src/ThreadPoolDispatcher.kt
=> Document newFixedThreadPoolContext in common code

kotlinx-coroutines-debug/src/DebugProbes.kt
=> Re-structure DebugProbes documentation and mention classloading

kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt
For desktop applications, Swing/JavaFx dispatcher should be picked by our fast SL mechanism. But if there is a dependency on firebase-sdk, it breaks: the dependency repackages Android classes, and we incorrectly assume we are on Android platform.
Explicitly take it into account
Fixes #3914
=> Fix obscure 'Main dispatcher is missing'

kotlinx-coroutines-core/common/src/Annotations.kt, kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt, kotlinx-coroutines-core/common/src/channels/Channel.kt, kotlinx-coroutines-core/common/src/intrinsics/Cancellable.kt
* @suppresses where necessary until https://github.com/Kotlin/dokka/issues/1861 is fixed
* Add @MustBeDocumented in case if it's leaked into public documentation
=> Tidy up @InternalCoroutinesApi documentation

kotlinx-coroutines-core/jvm/src/internal/Concurrent.kt
=> Add a workaround for incremental compilation bug

integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt
The `foo` coroutine could be cancelled before it's started, which would immediately trigger the `expect(3)` in `foo.invokeOnCompletion`. This could happen before `expect(2)` and fail the test.
=> Fix race condition in `ListenableFutureTest.testFutureIsDoneAfterChildrenCompleted`.

kotlinx-coroutines-core/jvm/test/DispatchersToStringTest.kt
=> Make a test configuration-independent

docs/topics/cancellation-and-timeouts.md, docs/topics/channels.md, docs/topics/composing-suspending-functions.md, docs/topics/coroutine-context-and-dispatchers.md, docs/topics/coroutines-basics.md, docs/topics/exception-handling.md, docs/topics/flow.md, docs/topics/select-expression.md, docs/topics/shared-mutable-state-and-concurrency.md
workaround until [WRS-5102](https://youtrack.jetbrains.com/issue/WRS-5102)
=> fix: reverting link changes to pass the knit check

kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
Renamed `detachChildIfNonResuable()` to `detachChildIfNonReusable()`
=> Fix a typo

kotlinx-coroutines-core/common/src/flow/operators/Lint.kt
=> Fix typos in deprecation messages

gradle/wrapper/gradle-wrapper.properties, integration-testing/gradle/wrapper/gradle-wrapper.properties
=> Use cache redirector to download Gradle
