README.md

On the repo, the package names don't have the suffix -1.

Fixed packaged names

---

coroutines-guide.md

Fixes the typo in the coroutines-guide.md

---

reactive/kotlinx-coroutines-rx1/src/main/kotlin/kotlinx/coroutines/experimental/rx1/RxAwait.kt
reactive/kotlinx-coroutines-rx1/src/main/kotlin/kotlinx/coroutines/experimental/rx1/RxScheduler.kt
reactive/kotlinx-coroutines-rx1/src/test/kotlin/kotlinx/coroutines/experimental/rx1/SchedulerTest.kt

`asCoroutineDispatcher` function for `Rx1` `Scheduler` (similar to the ones for `Rx2` and `Reactor` `Scheduler`).

Add support for Rx1 Scheduler.

---

kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/sync/Mutex.kt

> The mutex created is fair: lock is granted in sequential order to the applicants.

Mutex fairness documentation (#90)

---

reactive/kotlinx-coroutines-reactive/src/main/kotlin/kotlinx/coroutines/experimental/reactive/Convert.kt
reactive/kotlinx-coroutines-reactor/src/main/kotlin/kotlinx/coroutines/experimental/reactor/Convert.kt
reactive/kotlinx-coroutines-reactor/src/main/kotlin/kotlinx/coroutines/experimental/reactor/Flux.kt

Added some missing DefaultContext to reactive integrations.

Reactive default context

---

README.md

It links to a much more useful search page, showing the sub-packages, too.

Update Maven Central link to a more useful search

---

ui/coroutines-guide-ui.md

It writes that there's no "MouseEvent" on Android, actually there is android.view.MotionEvent. This sounds misleading.
Here is proposal for improvement to pass through View parameter in onClick.

Improved Android's onClick

---

core/kotlinx-coroutines-core/README.md
core/kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/internal/ThreadSafeHeap.kt
core/kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/test/TestCoroutineContext.kt
core/kotlinx-coroutines-core/src/test/kotlin/kotlinx/coroutines/experimental/test/TestCoroutineContextTest.kt

The purpose of this PR is to add a component that allows unit-tests that exercise code with Coroutines with delays and timeouts to run as fast as possible in near zero time.
Running a unit-test for code that contains one or more Coroutine with delays or timeouts requires the unit-test to wait and delay until the delays and timeouts of the various Coroutines come to pass.
This can cause unit-tests to take too much time to finish.
The addition of a new Coroutine context, called `TestCoroutineContext` alleviates this problem much like a `TestScheduler` does for RxJava2. When Coroutines use an instance of `TestCoroutineContext`, delays and timeouts can be fast-forwarded by calling its methods such as `advanceTimeBy` and `advanceTimeTo` and this will speed up the execution of these Coroutines.

Adding a test-helper class TestCoroutineContext.

---

ui/coroutines-guide-ui.md

As discussed on [Stack Overflow](https://stackoverflow.com/questions/51028384/whats-the-difference-between-a-job-ui-context-and-using-parent-job), the idiom `actor(contextJob + UI)` got first-class support in the form of `actor(UI, parent = contextJob)`. This PR updates the docs to reflect this improvement.
Since the `parent` parameter is nullable, this change allows us to also simplify the definition of `contextJob` and avoid the usage of `NonCancellable` as the explicit substitution for `null`.

Use parent = contextJob instead of contextJob + UI

---

common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt
common/kotlinx-coroutines-core-common/src/JobSupport.kt
common/kotlinx-coroutines-core-common/test/AbstractCoroutineTest.kt
common/kotlinx-coroutines-core-common/test/channels/ProduceTest.kt

1) Invoke handlers before dispatching in CancellableContinuation to make behaviour timing-independent and Unconfined doesn't produce unexpected results
2) Invoke onCancellation -> handlers -> onCompletion in Job to make behaviour timing-independent
Fixes #415

Change order of handlers in JobSupport and CancellableContinuation

---

coroutines-guide.md

Minor fixes for the English grammar in the coroutines guide to help ensure new readers understand coroutines properly.

Minor grammatical changes to the Coroutines guide

---

common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt
common/kotlinx-coroutines-core-common/test/CancellableContinuationTest.kt
core/kotlinx-coroutines-core/test/CancellableContinuationExceptionHandlingTest.kt
reactive/kotlinx-coroutines-reactive/test/IntegrationTest.kt
reactive/kotlinx-coroutines-rx1/src/RxAwait.kt
reactive/kotlinx-coroutines-rx1/test/IntegrationTest.kt
reactive/kotlinx-coroutines-rx2/test/IntegrationTest.kt

Here is a problem that every code that uses `suspendCancellableCoroutine` faces.
There is a race between cancellation of outer job and invocation of resume on a cancellable continuation and this race cannot be worked around by the code that uses `suspendCancellableCoroutine` function. Thus resume attempt on a cancelled continuation shall be simply ignored.
Fixes #450

Ignore resume on cancelled continuation

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
core/kotlinx-coroutines-core/src/Builders.kt

Using `-Dkotlinx.coroutines.blocking.checker=disable` to ignore all installed blocking checkers.

System property to control BlockingChecker extension point for runBlocking

---

core/kotlinx-coroutines-core/src/internal/SystemProps.kt
core/kotlinx-coroutines-core/test/guide/test/TestUtil.kt

To reduce the amount of useless output to (finite) terminal.
@ndkoval told that corresponding fix to LinChecker is coming

Do not print GuideTest system out if test passes

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
core/kotlinx-coroutines-core/src/CommonPool.kt
core/kotlinx-coroutines-core/src/Executors.kt
core/kotlinx-coroutines-core/src/ThreadPoolDispatcher.kt
core/kotlinx-coroutines-core/src/scheduling/CoroutineScheduler.kt
core/kotlinx-coroutines-core/src/scheduling/ExperimentalCoroutineDispatcher.kt
core/kotlinx-coroutines-core/test/guide/test/TestUtil.kt
integration/kotlinx-coroutines-jdk8/test/future/FutureTest.kt

Introducing `ExecutorCoroutineDispatche`r instead of `CloseableCoroutineDispatcher` (ABI breaking change)
Remove deprecated for long enough methods
Also, I like the idea to make `ThreadPoolDispatcher` internal and return `ExecutorCoroutineDispatcher` everywhere instead, but it will break a lot of existing ABI (though, maybe it's not that relevant)

Class for exposing dispatcher's executor

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
build.gradle
common/kotlinx-coroutines-core-common/src/Builders.common.kt
common/kotlinx-coroutines-core-common/src/JobSupport.kt
common/kotlinx-coroutines-core-common/src/ResumeMode.kt
common/kotlinx-coroutines-core-common/src/channels/AbstractChannel.kt
common/kotlinx-coroutines-core-common/src/channels/ConflatedBroadcastChannel.kt
common/kotlinx-coroutines-core-common/src/intrinsics/Undispatched.kt
common/kotlinx-coroutines-core-common/src/selects/Select.kt
common/kotlinx-coroutines-core-common/src/sync/Mutex.kt
common/kotlinx-coroutines-core-common/test/selects/SelectArrayChannelTest.kt
common/kotlinx-coroutines-core-common/test/selects/SelectRendezvousChannelTest.kt
core/kotlinx-coroutines-core/src/CoroutineContext.kt
core/kotlinx-coroutines-core/src/ThreadContextElement.kt
core/kotlinx-coroutines-core/src/internal/ThreadContext.kt
core/kotlinx-coroutines-core/test/DebugThreadNameTest.kt
core/kotlinx-coroutines-core/test/TestBase.kt
core/kotlinx-coroutines-core/test/ThreadContextElementTest.kt
core/kotlinx-coroutines-core/test/ThreadLocalTest.kt
core/kotlinx-coroutines-core/test/guide/example-context-11.kt
core/kotlinx-coroutines-core/test/guide/test/GuideTest.kt
core/kotlinx-coroutines-core/test/selects/SelectChannelStressTest.kt
coroutines-guide.md
integration/kotlinx-coroutines-quasar/src/Quasar.kt
js/kotlinx-coroutines-core-js/test/TestBase.kt
native/kotlinx-coroutines-core-native/test/TestBase.kt

Introduce ThreadContextElement API to integrate with thread-local sensitive code

---

binary-compatibility-validator/build.gradle
binary-compatibility-validator/reference-public-api/kotlinx-coroutines-slf4j.txt
integration/README.md
integration/kotlinx-coroutines-slf4j/README.md
integration/kotlinx-coroutines-slf4j/build.gradle
integration/kotlinx-coroutines-slf4j/src/MDCContext.kt
integration/kotlinx-coroutines-slf4j/test-resources/logback-test.xml
integration/kotlinx-coroutines-slf4j/test/MDCContextTest.kt
settings.gradle
site/docs/index.md

Reworked #403, integrated with #454, see #119

 Implementation of a SLF4J MDC Context

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
common/kotlinx-coroutines-core-common/src/CoroutineDispatcher.kt
core/kotlinx-coroutines-core/src/CoroutineContext.kt
core/kotlinx-coroutines-core/src/scheduling/ExperimentalCoroutineDispatcher.kt
core/kotlinx-coroutines-core/test/IODispatcherTest.kt
core/kotlinx-coroutines-core/test/TestBase.kt

Introduce IO dispatcher to offload blocking I/O-intensive tasks

---

ui/kotlinx-coroutines-javafx/src/JavaFxDispatcher.kt

Deprecation message of `JavaFx` says: "Use Dispatchers.Main". This is a bit confusing, since there is no `Dispatchers.Main` available in `kotlinx-coroutines-javafx`.
Deprecation message should be "Use Dispatchers.JavaFx".

Fix typo in deprecation message of JavaFx dispatcher

---

core/kotlinx-coroutines-core/src/EventLoop.kt
core/kotlinx-coroutines-core/test/RunBlockingTest.kt

Fixed cancellation of runBlocking event loon in the presence of delay

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-guava.txt
integration/kotlinx-coroutines-guava/src/ListenableFuture.kt
integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt
integration/kotlinx-coroutines-jdk8/src/future/Future.kt
integration/kotlinx-coroutines-jdk8/test/future/FutureTest.kt

…, provide ListenableFuture.asDeferred
Rationale: in most common use-cases awaiting the future is required to integrate with future-based API, current coroutine is the only user of this future and after its cancellation this future result is no longer needed. For non-cancelling await future.asDeferred().await() should be used
Fixes #515

Future cancellation

---

common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt
common/kotlinx-coroutines-core-common/src/Builders.common.kt
common/kotlinx-coroutines-core-common/src/CoroutineScope.kt
common/kotlinx-coroutines-core-common/src/internal/Scopes.kt
common/kotlinx-coroutines-core-common/test/WithContextTest.kt
core/kotlinx-coroutines-core/test/WithContextCancellationStressTest.kt
core/kotlinx-coroutines-core/test/exceptions/WithContextExceptionHandlingTest.kt

* Both are optimized and are rewritten via AbstractCoroutine
* Support for cancelling state is dropped from AbstractContinuation
and it is now faster, too
Fixes #553
Fixes #617

Fixed CoroutineScope of withContext block for structured concurrency

---

common/kotlinx-coroutines-core-common/src/Dispatchers.common.kt
core/kotlinx-coroutines-core/build.gradle
core/kotlinx-coroutines-core/src/CommonPool.kt
core/kotlinx-coroutines-core/src/CoroutineContext.kt
core/kotlinx-coroutines-core/src/Dispatchers.kt
core/kotlinx-coroutines-core/src/Executors.kt
core/kotlinx-coroutines-core/src/TimeSource.kt
core/kotlinx-coroutines-core/src/scheduling/CoroutineScheduler.kt
core/kotlinx-coroutines-core/src/scheduling/Dispatcher.kt
core/kotlinx-coroutines-core/src/scheduling/Tasks.kt
core/kotlinx-coroutines-core/src/scheduling/WorkQueue.kt
core/kotlinx-coroutines-core/test/TestBase.kt
core/kotlinx-coroutines-core/test/VirtualTimeSource.kt
core/kotlinx-coroutines-core/test/channels/ChannelsConsumeTest.kt
core/kotlinx-coroutines-core/test/channels/SimpleSendReceiveJvmTest.kt
core/kotlinx-coroutines-core/test/guide/example-context-01.kt
core/kotlinx-coroutines-core/test/guide/test/DispatcherGuideTest.kt
core/kotlinx-coroutines-core/test/guide/test/ExceptionsGuideTest.kt
core/kotlinx-coroutines-core/test/guide/test/TestUtil.kt
docs/coroutine-context-and-dispatchers.md
docs/exception-handling.md
reactive/kotlinx-coroutines-rx2/test/guide/test/ReactiveTestBase.kt

* Documentation and guide are updated correspondingly
* "DefaultDispatcher" is used as a public name of the default impl
* Implementation is integrated with virtual time-source
* Shutdown sequence is reimplemented in a safe way for tests,
makes "close" safe to use on custom instances.
* "close" on DefaultDispatcher throws exception just in case
* -Dkotlinx.coroutines.scheduler=off can be used to switch back to
CommonPool
Fixes #198

Coroutine scheduler is used by default instead of deprecated CommonPool

---

core/kotlinx-coroutines-core/src/EventLoop.kt
core/kotlinx-coroutines-core/src/internal/LockFreeMPMCQueue.kt
core/kotlinx-coroutines-core/src/internal/ThreadSafeHeap.kt
core/kotlinx-coroutines-core/src/scheduling/CoroutineScheduler.kt
core/kotlinx-coroutines-core/src/scheduling/Dispatcher.kt
core/kotlinx-coroutines-core/src/scheduling/Tasks.kt
core/kotlinx-coroutines-core/src/scheduling/WorkQueue.kt
core/kotlinx-coroutines-core/src/test_/TestCoroutineContext.kt
core/kotlinx-coroutines-core/test/internal/ThreadSafeHeapTest.kt
core/kotlinx-coroutines-core/test/scheduling/CoroutineSchedulerCloseStressTest.kt

* **CRITICAL**: Fixed synchronization of `ThreadSafeHeap.removeFirstIf`
* Reworked code to make sure that memory for disposed task never leaks
without violating ThreadSafeHeap encapsulation

Fixed rescheduling, synchronization & task disposal in EventLoop

---

README.md
binary-compatibility-validator/reference-public-api/kotlinx-coroutines-android.txt
binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
binary-compatibility-validator/reference-public-api/kotlinx-coroutines-javafx.txt
binary-compatibility-validator/reference-public-api/kotlinx-coroutines-swing.txt
common/kotlinx-coroutines-core-common/src/Dispatchers.common.kt
common/kotlinx-coroutines-core-common/src/MainCoroutineDispatcher.kt
common/kotlinx-coroutines-core-common/src/internal/MainDispatcherFactory.kt
core/kotlinx-coroutines-core/src/Dispatchers.kt
js/kotlinx-coroutines-core-js/src/Dispatchers.kt
native/kotlinx-coroutines-core-native/src/Dispatchers.kt
ui/README.md
ui/coroutines-guide-ui.md
ui/kotlinx-coroutines-android/resources/META-INF/services/kotlinx.coroutines.experimental.internal.MainDispatcherFactory
ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt
ui/kotlinx-coroutines-javafx/README.md
ui/kotlinx-coroutines-javafx/resources/META-INF/services/kotlinx.coroutines.experimental.internal.MainDispatcherFactory
ui/kotlinx-coroutines-javafx/src/JavaFxDispatcher.kt
ui/kotlinx-coroutines-swing/README.md
ui/kotlinx-coroutines-swing/resources/META-INF/services/kotlinx.coroutines.experimental.internal.MainDispatcherFactory
ui/kotlinx-coroutines-swing/src/SwingDispatcher.kt

Main thread dispatchers are grouped under Dispatchers object and are discoverable via ServiceLoader
* Dispatchers.Main can be consistently used and easily discovered, its implementation is discovered with ServiceLoader
* It allows us to add iOS Dispatchers.Main implementation in the future thus opening the door for multiplatform UI-dispatched code
* Workaround for #626, now Android users can start a migration to RC coroutines
Fixed #626

Move UI dispatcher to common Dispatchers.Main

---

common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt
common/kotlinx-coroutines-core-common/src/Job.kt
common/kotlinx-coroutines-core-common/src/JobSupport.kt
core/kotlinx-coroutines-core/test/exceptions/WithContextExceptionHandlingTest.kt

* Exceptions are never unwrapped when building cancellation cause
* This leads to more consistent behavior with respect to 3rd-party
exception that may be flowing through coroutines -- no 3rd-party
stack-trace will even get accidentally lost.
* This also leads to consistent behavior with respect to CancellationException:
they are never handled (even if they have some real exception as cause).
* The logic of how to cancel a child on failure (depending on the
"handlesException" flag in the parent job) is now encapsulated into
the parent itself, which leads to cleaner implementation in JobSupport.
* Job.getCancellationException is not used for child cancellation anymore
(it is used only and exclusively to cancel continuations)
* ParentJob interface with ParentJob.getChildJobCancellationCause …

Never unwrap 3rd party CancellationException

---

common/kotlinx-coroutines-core-common/src/Dispatchers.common.kt
core/kotlinx-coroutines-core/src/Dispatchers.kt
js/kotlinx-coroutines-core-js/src/Dispatchers.kt
native/kotlinx-coroutines-core-native/src/Dispatchers.kt

Also specified explicit public visibility for Dispatchers object.
Fixes #658
Fixes #665

Lazily load Dispatchers.Main and provide a stub impl on failure

---

docs/basics.md

In the text it states that "We explicitly specificy its `Unit` return type" but the code example does not explicitly set it

Added type <Unit> to be consistent with the text

---

core/kotlinx-coroutines-core/src/ThreadPoolDispatcher.kt

* The will be replaced by another mechanism in the future. See #261 for details.
* The proposed replacement is to use the standard java API: `Executors.newSingleThreadExecutor/newFixedThreadPool` and convert to dispatcher via `asCoroutineDispatcher()` extension.

Mark newSingle/FixedThreadPoolContext as obsolete, document the reason

---

common/kotlinx-coroutines-core-common/src/Builders.common.kt
common/kotlinx-coroutines-core-common/test/CoroutineScopeTest.kt
common/kotlinx-coroutines-core-common/test/SupervisorTest.kt
common/kotlinx-coroutines-core-common/test/WithContextTest.kt

Fix lost exception from dispatched withContext on cancelled job

---

docs/exception-handling.md

Old: Thread.uncaughExceptionHandler
New: Thread.uncaughtExceptionHandler

Fix miss spell in exception-handling.md

---

common/kotlinx-coroutines-core-common/src/Dispatched.kt
common/kotlinx-coroutines-core-common/src/Yield.kt
common/kotlinx-coroutines-core-common/src/internal/ArrayQueue.kt
common/kotlinx-coroutines-core-common/test/UnconfinedTest.kt

Implement yield for unconfined dispatchers

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
common/kotlinx-coroutines-core-common/src/CoroutineExceptionHandler.kt
reactive/kotlinx-coroutines-reactive/build.gradle
reactive/kotlinx-coroutines-reactive/src/Publish.kt
reactive/kotlinx-coroutines-reactive/test/PublishParentCancelStressTest.kt
reactive/kotlinx-coroutines-reactive/test/PublishTest.kt
reactive/kotlinx-coroutines-reactive/test/PublisherBackpressureTest.kt
reactive/kotlinx-coroutines-reactive/test/ReactiveStreamTckTest.kt

* Throw NPE on null subscriber
* Throw IAE when requested n <= 0 elements
* Do not sent any notification after cancel()

Reactive streams integration conformance to TCK verified & fixed

---

ui/coroutines-guide-ui.md

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Update coroutines-guide-ui.md gradle dependencies

---

README.md
binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
common/kotlinx-coroutines-core-common/src/CoroutineScope.kt
core/kotlinx-coroutines-core/src/Dispatchers.kt
ui/coroutines-guide-ui.md
ui/kotlinx-coroutines-swing/test/SwingTest.kt

Introduce MainScope factory and CoroutineScope.cancel extension

---

docs/channels.md

The produceSquares() function is probably a leftover, because only produceNumbers() 
and square() are actually used in the code sample.

Remove unnecessary function declaration from example

---

common/kotlinx-coroutines-core-common/src/Builders.common.kt

duplicate `,` character in async docs.

fix small typo of async method

---

common/kotlinx-coroutines-core-common/src/JobSupport.kt
core/kotlinx-coroutines-core/test/CancelledAwaitStressTest.kt

This is part of the problem that is shown in issue #893. The other
part of the problem (what happens during race) is addressed by PR #896
Fixes #893

Dispose waiting node when Deferred.await is cancelled

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
common/kotlinx-coroutines-core-common/src/CancellableContinuation.kt
common/kotlinx-coroutines-core-common/src/CancellableContinuationImpl.kt
common/kotlinx-coroutines-core-common/src/JobSupport.kt
common/kotlinx-coroutines-core-common/src/channels/AbstractChannel.kt
common/kotlinx-coroutines-core-common/src/sync/Mutex.kt
common/kotlinx-coroutines-core-common/test/CancellableContinuationTest.kt
integration/kotlinx-coroutines-jdk8/test/future/FutureTest.kt

There seems to be no other way to satisfactory fix the problem of a race between cancellation on CancellationContinuation and concurrent failure of the corresponding background process in a way the distinguishes "failure from cancellation attempt" from a "true failure" without placing undue burden on anyone who is implementing `await()` extension function for various future types.
- Added testTimeoutCancellationFailRace that works as a perfect litmus test; being allowed to run for a while it realiable detects various  problems in alternative approaches.
- Optimized CancellableContinuationImpl; merged its code with AbstractContinuation class that is not needed as a separate class and it removed.
- Deprecated and hidden CancellableContinuation.initCancellability(); it is now always invoked …

Ignore exception on cancel/fail race in CancellableContinuation

---

kotlinx-coroutines-core/jvm/src/channels/Actor.kt
kotlinx-coroutines-core/jvm/test/channels/ActorLazyTest.kt
kotlinx-coroutines-core/jvm/test/channels/ActorTest.kt

Rationale:
While it is possible to atomically transition state machine to "completed", it has multiple caveats:
* It breaks intuition that "close" allows actors to process remaining messages and call its body
* It introduces one more internal API dependency
* It makes behaviour of non-lazy and lazy actors inconsistent
Fixes #939

Start lazy actor when calling close

---

kotlinx-coroutines-debug/src/CoroutineState.kt
kotlinx-coroutines-debug/src/internal/DebugProbesImpl.kt
kotlinx-coroutines-debug/test/RunningThreadStackMergeTest.kt
kotlinx-coroutines-debug/test/SanitizedProbesTest.kt
kotlinx-coroutines-debug/test/ScopedBuildersTest.kt
kotlinx-coroutines-debug/test/StracktraceUtils.kt

* Capture thread of coroutine when it's transited to running state
* During dump retrieve the stacktrace of captured thread for running coroutines and merge it with metadata-based stacktrace
Fixes #997

Obtain real stacktrace of running coroutines in debug agent

---

kotlinx-coroutines-core/common/src/Builders.common.kt
kotlinx-coroutines-core/common/test/WithContextTest.kt

* Immediately check is the new context is cancelled and throw
CancellationException as needed
* Properly explain cancellation behavior in documentation
Fixes #962

Make all invocations of withContext cancellable

---

reactive/kotlinx-coroutines-reactive/src/Channel.kt
reactive/kotlinx-coroutines-reactive/test/IntegrationTest.kt
reactive/kotlinx-coroutines-reactive/test/PublishTest.kt
reactive/kotlinx-coroutines-reactor/test/FluxTest.kt
reactive/kotlinx-coroutines-rx2/src/RxChannel.kt
reactive/kotlinx-coroutines-rx2/test/FlowableTest.kt
reactive/kotlinx-coroutines-rx2/test/MaybeTest.kt
reactive/kotlinx-coroutines-rx2/test/ObservableTest.kt

Fixed bugs in MaybeSource/ObservableSource.consumeEach implementation
so that observable is disposed on cancellation.
Also optimized implementation of bridge function to avoid extra dispose
calls if possible (this is permissible by specification, though)
Fixes #1008

Cancellation in consumeEach should dispose Rx Observable

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/CoroutineScope.kt
kotlinx-coroutines-core/common/src/Dispatchers.common.kt
kotlinx-coroutines-core/common/src/MainCoroutineDispatcher.kt
kotlinx-coroutines-core/jvm/src/Dispatchers.kt
kotlinx-coroutines-test/src/internal/MainTestDispatcher.kt
ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt

Promote Unconfined, immediate, MainScope and CoroutineScope.cancel to stable API

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/CoroutineScope.kt
kotlinx-coroutines-core/common/src/Job.kt
kotlinx-coroutines-core/common/test/EnsureActiveTest.kt

Add ensureActive extension

---

kotlinx-coroutines-core/jvm/src/ThreadContextElement.kt

Clarify thread locals documentation

---

kotlinx-coroutines-core/common/src/Builders.common.kt
kotlinx-coroutines-core/common/test/CoroutineDispatcherOperatorFunInvokeTest.kt

Add operator invoke for CoroutineDispatcher

---

common/kotlinx-coroutines-core-common/src/Await.kt

* double `when`
* 2nd change can be either `wait for the failing deferred` or `await the failing deferred`. Sounds a bit off with `wait the failing deferred`.
Let me know which is preferred

Update awaitAll documentation wording

---

core/kotlinx-coroutines-core/src/Builders.kt

It looks to me like there was a small typo in the `runBlocking` KDoc.

fix `runBlocking` documentation typo

---

kotlinx-coroutines-core/common/src/internal/SystemProps.common.kt
kotlinx-coroutines-core/js/src/internal/SystemProps.kt
kotlinx-coroutines-core/jvm/src/internal/SystemProps.kt
kotlinx-coroutines-core/native/src/internal/SystemProps.kt

Move `systemProp` function to the common module; only the JVM platform implements it properly while others always use provided default value. This change makes it possible to use different constants in production and tests not only in JVM code but in common code as well.

Move `systemProp` function to the common module

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
docs/coroutine-context-and-dispatchers.md
integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt
integration/kotlinx-coroutines-jdk8/test/future/FutureTest.kt
kotlinx-coroutines-core/jvm/src/ThreadContextElement.kt
kotlinx-coroutines-core/jvm/src/internal/ThreadContext.kt
kotlinx-coroutines-core/jvm/test/TestBase.kt
kotlinx-coroutines-core/jvm/test/ThreadLocalTest.kt
kotlinx-coroutines-core/jvm/test/guide/example-context-11.kt

Add ThreadLocal.isPresent and ThreadLocal.ensurePresent methods

---

docs/channels.md

Use `sequence` and `iterator` instead of `buildSequence` and `buildIterator`.

Update Channels docs to Koltin 1.3

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
integration/kotlinx-coroutines-guava/src/ListenableFuture.kt
integration/kotlinx-coroutines-jdk8/src/future/Future.kt
kotlinx-coroutines-core/common/src/AbstractCoroutine.kt
kotlinx-coroutines-core/common/src/Builders.common.kt
kotlinx-coroutines-core/common/src/CompletedExceptionally.kt
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/Timeout.kt
kotlinx-coroutines-core/common/src/channels/Broadcast.kt
kotlinx-coroutines-core/common/src/channels/Produce.kt
kotlinx-coroutines-core/common/src/internal/Scopes.kt
kotlinx-coroutines-core/common/test/AbstractCoroutineTest.kt
kotlinx-coroutines-core/common/test/ParentCancellationTest.kt
kotlinx-coroutines-core/jvm/src/Builders.kt
kotlinx-coroutines-core/jvm/src/channels/Actor.kt
kotlinx-coroutines-core/jvm/test/exceptions/ProduceExceptionsTest.kt
kotlinx-coroutines-core/jvm/test/exceptions/SuppressionTests.kt
reactive/kotlinx-coroutines-reactive/src/Publish.kt
reactive/kotlinx-coroutines-reactor/src/Mono.kt
reactive/kotlinx-coroutines-reactor/test/MonoTest.kt
reactive/kotlinx-coroutines-rx2/src/RxCompletable.kt
reactive/kotlinx-coroutines-rx2/src/RxMaybe.kt
reactive/kotlinx-coroutines-rx2/src/RxObservable.kt
reactive/kotlinx-coroutines-rx2/src/RxSingle.kt
reactive/kotlinx-coroutines-rx2/test/CompletableTest.kt
reactive/kotlinx-coroutines-rx2/test/MaybeTest.kt
reactive/kotlinx-coroutines-rx2/test/SingleTest.kt

* JobSupport.handleJobException (which is called before the coroutine goes
to the final state) is now called only when parent did not handle
exception and is used only in launch-like coroutines (launch and actor)
to report uncaught exception.
* The final result of other types coroutines that, by default, have an
object "to store exceptions" is consistently processed after all
other notifications when the coroutine state is already complete and
is reported as uncaught exception as a last-resort processing tactic
when it cannot be otherwise handled.
* The above change makes the order of notifications for future { ... } and
other async-like coroutine builders consistent with the order in which
async { ... }.await() is notified.
* The "handled" state of exception (whether it was processed or …

Improved coroutine exception handling logic

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/CancellableContinuation.kt
kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
kotlinx-coroutines-core/common/src/Dispatched.kt
kotlinx-coroutines-core/common/src/Job.kt
kotlinx-coroutines-core/common/test/CancellableResumeTest.kt

* Allows safe return of closeable resources from suspending
functions, as it provides a way to close a resource if the
corresponding job was cancelled.
* Documentation on the context and expected behavior of
CompletionHandler implementations is updated.
Fixes #1044

Introduce CancellableContinuation.resume with onCancelling lambda

---

kotlinx-coroutines-core/jvm/src/test_/TestCoroutineContext.kt

It looks to me that there is a typo: Coroutine~~s~~Context

fix typo: Coroutine"s"Context

---

README.md
kotlinx-coroutines-core/js/npm/README.md

* Provide a better "getting started" example without GlobalScope
* Restore lost information on how to use coroutines with JS and Native
* Update link to the guide (point it to kotlinlang.org version that has
runnable code snippets).

Update top-level readmes with better example and js + native links

---

build.gradle
gradle.properties
gradle/compile-common.gradle
gradle/compile-js-multiplatform.gradle
gradle/compile-jvm-multiplatform.gradle
gradle/compile-native-multiplatform.gradle
kotlinx-coroutines-core/common/src/flow/operators/Merge.kt

* Update to atomicfu 0.12.4, which fixes plugin operation with
kotlin-multiplatform
* Remove explicit dependencies (plugins adds them automatically)
* There will be no atomicfu dependency in the resulting artefacts
Fixes #1116
Fixes #1064

Fix atomicfu post-processing and dependencies

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-jdk8.txt
integration/kotlinx-coroutines-jdk8/src/future/Future.kt
integration/kotlinx-coroutines-jdk8/test/future/AsFutureTest.kt
integration/kotlinx-coroutines-jdk8/test/future/FutureTest.kt

CompletableJob.asCompletableFuture

---

kotlinx-coroutines-core/jvm/src/test_/TestCoroutineContext.kt

Delete the duplicated "based" word from header doc

Fix header documentation typo in "TestCoroutineContext"

---

kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
kotlinx-coroutines-core/common/src/Dispatched.kt
kotlinx-coroutines-core/jvm/test/CancellableContinuationResumeCloseStressTest.kt
kotlinx-coroutines-core/jvm/test/JobStructuredJoinStressTest.kt

The race happens in the slow-path of 'join' implementation when
parent invokes join on a child coroutines that crashes and cancels
the parent.
Fixes #1123

Fix a race in Job.join that sporadically results in normal completion

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-test.txt
kotlinx-coroutines-test/README.md
kotlinx-coroutines-test/src/TestBuilders.kt
kotlinx-coroutines-test/src/TestCoroutineDispatcher.kt
kotlinx-coroutines-test/src/TestCoroutineExceptionHandler.kt
kotlinx-coroutines-test/test/TestRunBlockingOrderTest.kt
kotlinx-coroutines-test/test/TestRunBlockingTest.kt

* Get rid of ThreadSafeHeap usages, make it internal again
* Yield support in test dispatcher
* Allow partial override of coroutine context
* Code style fixes

kotlinx-coroutines-test cleanup

---

README.md

3.3.0 (non canary/beta release) didn't have R8 enabled by default.

README: R8 is default in 3.4.0+ and 3.3.0-beta

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/channels/Channel.kt
kotlinx-coroutines-core/common/src/channels/ChannelCoroutine.kt
kotlinx-coroutines-core/common/src/flow/internal/AbortFlowException.kt
kotlinx-coroutines-core/common/src/flow/operators/Context.kt
kotlinx-coroutines-core/common/src/flow/operators/Limit.kt
kotlinx-coroutines-core/common/src/flow/operators/Zip.kt
kotlinx-coroutines-core/common/test/channels/ArrayBroadcastChannelTest.kt
kotlinx-coroutines-core/common/test/channels/ArrayChannelTest.kt
kotlinx-coroutines-core/common/test/channels/BasicOperationsTest.kt
kotlinx-coroutines-core/common/test/channels/ConflatedChannelTest.kt
kotlinx-coroutines-core/common/test/channels/LinkedListChannelTest.kt
kotlinx-coroutines-core/common/test/channels/ProduceTest.kt
kotlinx-coroutines-core/common/test/channels/RendezvousChannelTest.kt
kotlinx-coroutines-core/common/test/flow/IdFlowTest.kt
kotlinx-coroutines-core/common/test/flow/operators/ZipTest.kt
kotlinx-coroutines-core/jvm/test/channels/DoubleChannelCloseStressTest.kt
kotlinx-coroutines-core/jvm/test/channels/TickerChannelCommonTest.kt
kotlinx-coroutines-core/jvm/test/exceptions/ProduceExceptionsTest.kt

* ReceiveChannel.cancel always closes channel with CancellationException,
so sending or receiving from a cancelled channel produces the
corresponding CancellationException.
* Cancelling produce builder has similar effect, but an more specific
instance of JobCancellationException is created.
* This ensure that produce/consumeEach pair is transparent with respect
to cancellation and can be used to build "identity" transformation
of the flow (the corresponding test is added).
* ClosedSendChannelException is now a subclass of IllegalStateException,
so that trying to send to a channel that was closed normally is
reported as program error and is not eaten (test is added).
Fixes #957
Fixes #1128

Fix exception types for channels to ensure transparency & reporting

---

kotlinx-coroutines-test/README.md

Maybe this sample needs runBlockingTest method.

kotlinx-coroutines-test README: use runBlockingTest for withTimeout sample code

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-debug.txt
kotlinx-coroutines-debug/src/junit4/CoroutinesTimeout.kt
kotlinx-coroutines-debug/src/junit4/CoroutinesTimeoutStatement.kt
kotlinx-coroutines-debug/test/junit4/CoroutinesTimeoutTest.kt
kotlinx-coroutines-debug/test/junit4/TestFailureValidation.kt

Add overload with long for CoroutinesTimeout.seconds

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/flow/operators/Zip.kt
kotlinx-coroutines-core/common/test/flow/operators/CombineLatestTest.kt
kotlinx-coroutines-core/common/test/flow/operators/CombineLatestVarargTest.kt

* combineLatest(Iterable<Flow<T>>) is not added deliberately, use-case is unclear
* All specific overloads are marked as inline to reduce binary compatibility pressure
Fixes #1193

Add combineLatest with multiple flows

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/CompletableJob.kt
kotlinx-coroutines-core/common/src/Job.kt
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/test/ParentCancellationTest.kt
kotlinx-coroutines-core/common/test/SupervisorTest.kt
kotlinx-coroutines-core/jvm/test/exceptions/Exceptions.kt
kotlinx-coroutines-core/jvm/test/exceptions/JobExceptionHandlingTest.kt
kotlinx-coroutines-core/jvm/test/exceptions/JobExceptionsStressTest.kt
kotlinx-coroutines-core/jvm/test/exceptions/JobNestedExceptionsTest.kt
kotlinx-coroutines-core/jvm/test/exceptions/ProduceExceptionsTest.kt
kotlinx-coroutines-core/jvm/test/exceptions/WithContextExceptionHandlingTest.kt

* Wrap exceptions into CE if parent cancels its child. This is possible because now we can be sure that no one is invoking 'cancel(Throwable)', thus if parent cancels its children, an exception is definitely handled.
* This changes allows exceptions in hierarchies to be handled only once even when coroutines in the hierarchy are capable of handling exceptions
* Breaking change: CompletableJob.completeExceptionally(exception) uses its parameter as additional debug information for children ('cause' of CE), thus changing the result of its children. For example, if CJ was a parent of CompleteableDeferred and CJ was completed exceptionally with exception E1, now CD.await() will throw CE instead of E1
* Recursively check whether parent handles exception to avoid duplicates reporting when Job() …

Improve coroutine exception handling logic

---

kotlinx-coroutines-core/common/src/CoroutineContext.common.kt
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/flow/Flow.kt
kotlinx-coroutines-core/common/src/flow/FlowCollector.kt
kotlinx-coroutines-core/common/src/flow/internal/SafeCollector.kt
kotlinx-coroutines-core/common/src/internal/Scopes.kt
kotlinx-coroutines-core/common/test/flow/FlowInvariantsTest.kt
kotlinx-coroutines-core/js/src/CoroutineContext.kt
kotlinx-coroutines-core/jvm/src/CoroutineContext.kt
kotlinx-coroutines-core/native/src/CoroutineContext.kt

* Strengthen flow context preservation invariant
* Cache result of the context check thus speeding up safe collector on happy path by a factor of three
* Separate fast and slow paths in JobSupport to drastically change inlining decisions of the JVM that are crucial for leaf coroutines with flows

SafeCollector rework

---

kotlinx-coroutines-core/jvm/src/CoroutineExceptionHandlerImpl.kt
kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt
kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt

The developer still has to disable the FastServiceLoader manually
if they're using R8.
R8 is then able to optimize away the ServiceLoader and reflection
entirely, resulting in direct class instantiation and no extra I/O
on calling thread.
Fixes #1231

Enable R8 optimization of Dispatchers.Main loading

---

kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt
kotlinx-coroutines-core/common/test/channels/ConflatedChannelTest.kt
kotlinx-coroutines-core/common/test/flow/channels/ChannelFlowTest.kt

Adjust behavior of conflated channel to deliver last value

---

docs/channels.md

Seems like channels documentation wasn't updated.

Remove experimental warning from Channels docs

---

benchmarks/src/jmh/kotlin/benchmarks/SemaphoreBenchmark.kt
binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
gradle.properties
kotlinx-coroutines-core/common/src/flow/operators/Merge.kt
kotlinx-coroutines-core/common/src/internal/SegmentQueue.kt
kotlinx-coroutines-core/common/src/sync/Semaphore.kt
kotlinx-coroutines-core/common/test/sync/SemaphoreTest.kt
kotlinx-coroutines-core/jvm/test/internal/SegmentBasedQueue.kt
kotlinx-coroutines-core/jvm/test/internal/SegmentQueueLFTest.kt
kotlinx-coroutines-core/jvm/test/internal/SegmentQueueTest.kt
kotlinx-coroutines-core/jvm/test/sync/SemaphoreStressTest.kt

An efficient semaphore implementation.
Fixes #1088

Add Semaphore

---

reactive/coroutines-guide-reactive.md
reactive/kotlinx-coroutines-reactive/src/Channel.kt
reactive/kotlinx-coroutines-reactor/test/BackpressureTest.kt
reactive/kotlinx-coroutines-rx2/test/BackpressureTest.kt
reactive/kotlinx-coroutines-rx2/test/guide/test/GuideReactiveTest.kt

This makes Publisher.collect consistent with Publisher.asFlow and
ensures smooth integration with reactive backpressure operators
"out of the box".
Fixes #1267

Change default request size in Publisher.openSubscription to one

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/flow/Flow.kt
kotlinx-coroutines-core/common/src/flow/Migration.kt
kotlinx-coroutines-core/common/src/flow/operators/Errors.kt
kotlinx-coroutines-core/common/src/flow/operators/Transform.kt
kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt
kotlinx-coroutines-core/common/test/flow/operators/OnCompletionTest.kt
kotlinx-coroutines-core/common/test/flow/terminal/LaunchInTest.kt

`onCompletion` and basic `launchIn` support for 1.3.0-M2.
Open questions that we can work on later:
* Enforce exception transparency in catch/retry/onCompletion operators
* Optional DSL for `launchIn`, maybe with order enforcement

Declarative flow operators

---

kotlinx-coroutines-core/common/src/channels/Produce.kt

Type parameter of awaitClose is not used but produces a warning in
new type inference when used with builder inference as in callbackFlow
as seen in this issue: https://youtrack.jetbrains.com/issue/KT-32097
Using star projection removes the warning and is binary compatible
thanks to generics type erasure.

Replace unneeded type parameter with projection

---

kotlinx-coroutines-core/common/src/flow/Builders.kt

Fixed sample to use `awaitClose` instead of `await`

---

kotlinx-coroutines-core/common/src/flow/internal/SafeCollector.kt

Use the correct builder method `flowChannel` in the checkContext error description

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/flow/Migration.kt
kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/common/src/flow/operators/Transform.kt
kotlinx-coroutines-core/common/test/flow/operators/OnCompletionTest.kt
kotlinx-coroutines-core/common/test/flow/operators/OnStartTest.kt
kotlinx-coroutines-core/common/test/flow/operators/TransformTest.kt

Add Flow.onStart, support emit in onCompletion
* All "emitting" operators (onStart, transform, onCompletion) are moved
to Emitters.kt and are implemented in a safe way, making sure that
user-specified block is called on a SafeCollector only.
* Unsafe internal version of transform (unsafeTransform) is introduced.  
* All transformations in Transform.kt are rewritten via unsafeTransform. 
* Added migration for startWith and concatWith.
* Consistent docs for all migration functions.
* JvmMultifileClass for Migration.kt so that renamed/deprecated 
functions (when they moved there) continue to resolve.
Fixes #1168

Add Flow.onStart, support emit in onCompletion

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/CoroutineScope.kt
kotlinx-coroutines-core/common/src/Job.kt

Cancel extensions for CoroutineScope and Job

---

integration/kotlinx-coroutines-jdk8/src/time/Time.kt
integration/kotlinx-coroutines-jdk8/test/time/DurationOverflowTest.kt

Treat Duration.ZERO as 0L in jdk8 extensions

---

kotlinx-coroutines-core/common/test/flow/terminal/SingleTest.kt
reactive/kotlinx-coroutines-reactive/src/Publish.kt
reactive/kotlinx-coroutines-rx2/src/RxCompletable.kt
reactive/kotlinx-coroutines-rx2/src/RxMaybe.kt
reactive/kotlinx-coroutines-rx2/src/RxObservable.kt
reactive/kotlinx-coroutines-rx2/src/RxSingle.kt
reactive/kotlinx-coroutines-rx2/test/CompletableTest.kt
reactive/kotlinx-coroutines-rx2/test/ConvertTest.kt
reactive/kotlinx-coroutines-rx2/test/FlowableExceptionHandlingTest.kt
reactive/kotlinx-coroutines-rx2/test/MaybeTest.kt
reactive/kotlinx-coroutines-rx2/test/ObservableExceptionHandlingTest.kt
reactive/kotlinx-coroutines-rx2/test/SingleTest.kt

 Consistently handle fatal exceptions in reactive integrations

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/flow/Builders.kt
kotlinx-coroutines-core/common/src/flow/Channels.kt
kotlinx-coroutines-core/common/src/flow/Flow.kt
kotlinx-coroutines-core/common/src/flow/FlowCollector.kt
kotlinx-coroutines-core/common/src/flow/internal/FlowCoroutine.kt
kotlinx-coroutines-core/common/src/flow/internal/NopCollector.kt
kotlinx-coroutines-core/common/src/flow/internal/SafeCollector.kt
kotlinx-coroutines-core/common/src/flow/operators/Context.kt
kotlinx-coroutines-core/common/src/flow/operators/Delay.kt
kotlinx-coroutines-core/common/src/flow/operators/Distinct.kt
kotlinx-coroutines-core/common/src/flow/operators/Errors.kt
kotlinx-coroutines-core/common/src/flow/operators/Limit.kt
kotlinx-coroutines-core/common/src/flow/operators/Merge.kt
kotlinx-coroutines-core/common/src/flow/operators/Transform.kt
kotlinx-coroutines-core/common/src/flow/operators/Zip.kt
kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt
kotlinx-coroutines-core/common/src/flow/terminal/Collection.kt
kotlinx-coroutines-core/common/src/flow/terminal/Count.kt
kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt
kotlinx-coroutines-core/jvm/test/flow/FlatMapStressTest.kt

Only core interfaces and the most trivial operators are promoted to stable.
`switchMap` and `combienLatest` are demoted (we can do it within milestones, but not across different versions)

Stabilize core flow

---

docs/coroutine-context-and-dispatchers.md
kotlinx-coroutines-core/common/README.md
kotlinx-coroutines-core/jvm/src/CoroutineContext.kt
kotlinx-coroutines-core/jvm/src/Debug.kt

* Mention in the guide that `-ea` turns it on.
* Give a link to DEBUG_PROPERTY_NAME instead of newCoroutineContext.
The later does not have details on its page anymore, since
the details were only mentioned in JVM version.
* Move description in of debugging facilities to DEBUG_PROPERTY_NAME
in the code.

Better docs on coroutines debugging property

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/flow/Migration.kt

This represents a class in the RxJava library. Not saying US English is
better, but it is. 🤣 
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/subjects/BehaviorSubject.java

Use RxJava Spelling for BehaviorSubject.

---

kotlinx-coroutines-core/common/src/flow/Builders.kt

The function calling asFlow() doesn't need to be suspending, and the
doc seems to suggest otherwise.

Fix documentation of (suspend () -> T).asFlow()

---

build.gradle

These exclusions are obsolete since Kotlin 1.3.40.
Resolves #1405

Remove no longer needed tests excludes

---

integration/kotlinx-coroutines-guava/build.gradle

This fixes vulnerability CVE-2018-10237
See https://ossindex.sonatype.org/vuln/24585a7f-eb6b-4d8d-a2a9-a6f16cc7c1d0

Update Guava to the latest version 28.0

---

kotlinx-coroutines-core/common/src/flow/operators/Merge.kt
kotlinx-coroutines-core/common/test/flow/operators/BufferTest.kt
kotlinx-coroutines-core/common/test/flow/operators/FlatMapMergeTest.kt
kotlinx-coroutines-core/common/test/flow/operators/FlowOnTest.kt

* Implementation detail (launch on each value) is leaking into upstream behaviour
* The overhead is negligible compared to launching a new coroutines and sending to channel, but it provides a much approachable mental model when no suspension in the upstream flow happens (note: upstream never sends elements to the channel)
Fixes #1392

Check for cancellation in concurrent flow merge on each element

---

kotlinx-coroutines-bom/build.gradle

Currently kx-coroutines-core-{common,js,native} publications missing

Cover all publications in bom

---

kotlinx-coroutines-core/common/src/flow/Migration.kt
kotlinx-coroutines-core/common/src/flow/operators/Delay.kt

This will make Flow API surface more orthogonal with less operators to
remember. Both of them can be easily written without too much additional
code and still produce quite readable and easy to understand code:
delayFlow(time) = onStart { delay(time) }
delayEach(time) = onEach { delay(time) }
Fixes #1429

Deprecate delayFlow and delayEach

---

kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt
kotlinx-coroutines-core/common/test/channels/ArrayChannelTest.kt
kotlinx-coroutines-core/jvm/test/channels/ArrayChannelStressTest.kt

Rationale:
Such change will allow us to use huge buffers in various flow operators without having a serious footprint in suspension-free scenarios

Allocate underlying buffer in ArrayChannel in on-demand manner

---

kotlinx-coroutines-core/common/src/selects/Select.kt
kotlinx-coroutines-core/jvm/test/flow/CombineStressTest.kt

Do not report already handled exception in select builder

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/jvm/src/Executors.kt
kotlinx-coroutines-core/jvm/test/ExecutorsTest.kt

Introduce CoroutineDispatcher.asExecutor() extension

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/internal/LockFreeLinkedList.common.kt
kotlinx-coroutines-core/common/src/selects/Select.kt
kotlinx-coroutines-core/common/src/sync/Mutex.kt
kotlinx-coroutines-core/common/test/selects/SelectLinkedListChannelTest.kt
kotlinx-coroutines-core/common/test/selects/SelectRendezvousChannelTest.kt
kotlinx-coroutines-core/js/src/internal/LinkedList.kt
kotlinx-coroutines-core/jvm/src/internal/LockFreeLinkedList.kt
kotlinx-coroutines-core/jvm/test/internal/LockFreeLinkedListTest.kt
kotlinx-coroutines-core/jvm/test/selects/SelectMemoryLeakStressTest.kt
kotlinx-coroutines-core/native/src/internal/LinkedList.kt

There is no need for multi-word atomic performAtomicIfNotSelected
operation when enqueuing select node for operation. We can simply
enqueue (addLast) xxxSelect node (SendSelect, ReceiveSelect, LockSelect).
If the coroutine that rendezvous with this node finds out that the
select expression was already selected, then it'll try again.
* Removed SelectInstance.performAtomicIfNotSelected function
* Removed Mutex.TryEnqueueLockDesc class, simplified onLock
* Removed AbstractSendChannel.TryEnqueueSendDesc class, simpler onSend
* Removed AbstractChannel.TryEnqueueReceiveDesc class, simpler onReceive

Optimize select expression registration phase

---

gradle.properties
kotlinx-coroutines-core/jvm/test/channels/ChannelLFStressTest.kt

It tests lock-freedom on send and receive operations on rendezvous
channels. The test is comprehensive enough to fail on buffered
channels (which are currently not lock-free) and will help us
ensuring that lock-freedom property is not lost while channels are
being improved and refactored.

Add RendezvousChannelStressLFTest

---

README.md
knit/src/Knit.kt

* All API references are converted to links via knit
* Knit support short names to external extensions (like [Promise.await])
* Added Flow reference to the readme
Fixes #1468

Update top-level README with links:

---

kotlinx-coroutines-core/build.gradle
kotlinx-coroutines-core/jvm/test/internal/LockFreeLinkedListAtomicLFStressTest.kt
kotlinx-coroutines-core/jvm/test/internal/SegmentQueueLCStressTest.kt
kotlinx-coroutines-core/jvm/test/linearizability/ChannelIsClosedLCStressTest.kt
kotlinx-coroutines-core/jvm/test/linearizability/ChannelLCStressTest.kt
kotlinx-coroutines-core/jvm/test/linearizability/LockFreeListLCStressTest.kt
kotlinx-coroutines-core/jvm/test/linearizability/LockFreeTaskQueueLCStressTest.kt

* All stress tests end with StressTest, also:
* LFStressTest checks lock-freedom
* LCStressTest checks linearizability via LinCheck
* Gradle build exclusion/inclusion patterns are properly updated:
- jdk16Test excludes both LFStressTest and LCStressTest since they
depends on JDK8
- Regular tests exclude LFStressTest since they are long (5 sec each)
- A separate lockFreedomTest target that is run on "build"

Consistent naming for stress tests

---

integration/kotlinx-coroutines-jdk8/src/future/Future.kt
integration/kotlinx-coroutines-jdk8/test/future/FutureTest.kt

* A dedicated test is added that checks consistency of unwrapping
between slow and fast paths of both CompletionStage.await and
CompletionStage.asDeferred implementations.
* In the fast-path for both of them implementation of
CompletableFuture.get() does unwrapping of CompletionException, taking
its cause when it is not null. To mimic this behavior, the slow path
of both await and asDeferred shall perform similar unwrapping.
Fixes #1479

Consistently unwrap exception in slow path of CompletionStage.asDeferred

---

integration/kotlinx-coroutines-guava/src/ListenableFuture.kt
integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt

This fixes:
- Cancellation without an untrapped CancellationException propagating
through a Callback; isCancelled() is the correct way to check for
cancellation
- Bidirectional propagation of cancellation through
`asListenableFuture()`
- The cause getting lost in the `asListenableFuture()` future  when
cancelling its `Deferred` parent with a cause
This also:
- Extensively documents the package and the contracts created by the
promise-creating extension methods and `future()`
- Uses `getUninterruptibly()` for speed
- Uses `AbstractFuture` to make as certain as possible that
`Future.cancel()` will return `true` at most once
- Should clear up rare spooky race conditions around
cancellation/interruption in hybrid Coroutines/Guava Futures
codebases
There are probably a few more interesting …

Repaired some of ListenableFuture.kt's cancellation corner cases.

---

kotlinx-coroutines-core/common/src/sync/Semaphore.kt
kotlinx-coroutines-core/jvm/test/sync/SemaphoreStressTest.kt

This bug surfaced about a month ago during the formal proof. The bug is demonstrated in the provided test that used to fail, but no longer does with this patch.

Fix of a bug in the semaphore

---

build.gradle
kotlinx-coroutines-core/build.gradle

Also enable assertions and test output while running (long) LFStressTest

Fix propagation for stressTest property for nightly stress tests

---

kotlinx-coroutines-core/jvm/test/TestBase.kt

* Should not run long stress-tests during regular builds.

Check for -PstressTest=true to run "long" stress test

---

kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/channels/LinkedListChannel.kt
kotlinx-coroutines-core/jvm/test/linearizability/ChannelCloseLCStressTest.kt

Send operations must ALWAYS help close the channel when they observe
that it was closed before throwing an exception.
Fixes #1419

Fixed linearizability of Channel.close operation

---

ui/kotlinx-coroutines-android/animation-app/app/build.gradle
ui/kotlinx-coroutines-android/animation-app/app/proguard-rules.pro
ui/kotlinx-coroutines-android/animation-app/app/src/main/java/org/jetbrains/kotlinx/animation/Animation.kt
ui/kotlinx-coroutines-android/animation-app/app/src/main/java/org/jetbrains/kotlinx/animation/MainActivity.kt
ui/kotlinx-coroutines-android/animation-app/app/src/main/res/layout/activity_main.xml
ui/kotlinx-coroutines-android/animation-app/app/src/main/res/layout/content_main.xml
ui/kotlinx-coroutines-android/animation-app/build.gradle
ui/kotlinx-coroutines-android/animation-app/gradle.properties
ui/kotlinx-coroutines-android/animation-app/gradle/wrapper/gradle-wrapper.properties
ui/kotlinx-coroutines-android/example-app/app/build.gradle
ui/kotlinx-coroutines-android/example-app/app/proguard-rules.pro
ui/kotlinx-coroutines-android/example-app/app/src/main/java/com/example/app/MainActivity.kt
ui/kotlinx-coroutines-android/example-app/app/src/main/res/layout/activity_main.xml
ui/kotlinx-coroutines-android/example-app/app/src/main/res/layout/content_main.xml
ui/kotlinx-coroutines-android/example-app/build.gradle
ui/kotlinx-coroutines-android/example-app/gradle.properties
ui/kotlinx-coroutines-android/example-app/gradle/wrapper/gradle-wrapper.properties

* Gradle 5.4.1
* AGP 3.5.0
* Migrated to AndroidX
* Updated versions of all dependencies to the most recent ones
* Removed proguard rules

Update example Android apps toolchain (AGP 3.5.0, AndroidX)

---

kotlinx-coroutines-core/jvm/test/channels/ChannelLFStressTest.kt

A channel must be "cancelled" to abort both working senders & receivers.
Fixes #1507

Fixed completion sequence of ChannelLFStressTest

---

kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/internal/InlineList.kt
kotlinx-coroutines-core/common/test/channels/ChannelsTest.kt

We cannot resume closed receives until all receivers are removed from the list.
Consider channel state: head -> [receive_1] -> [receive_2] -> head
- T1 called receive_2, and will call send() when it's receive call resumes
- T2 calls close()
Now if T2's close resumes T1's receive_2 then it's receive gets
"closed for receive" exception, but its subsequent attempt to send
successfully rendezvous with receive_1, producing non-linearizable
execution.

Fixes linearizability of Channel.close in advanced receive+send case

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/CompletableDeferred.kt
kotlinx-coroutines-core/common/test/CompletableDeferredTest.kt

The naming for this convenience function is inspired by Continuation.resumeWith.

Add CompletableDeferred.completeWith(result: Result<T>)

---

kotlinx-coroutines-core/jvm/test/sync/MutexStressTest.kt
kotlinx-coroutines-core/jvm/test/sync/SemaphoreStressTest.kt

Make Semaphore and Mutex stress tests concurrent

---

integration/kotlinx-coroutines-guava/src/ListenableFuture.kt

This should prevent successful casts to type SettableFuture, meaning
client code can't access and complete the internal Future without
resorting to reflection.

Hid the SettableFuture of future {}.

---

kotlinx-coroutines-core/build.gradle

* `./gradlew :kotlinx-coroutines-core:jvmTest`
becomes really fast, since it does not run any stress tests.
* `./gradlew build`
still runs all the tests.

Separate all JVM stress tests into a stressTest gradle task

---

kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/channels/ArrayBroadcastChannel.kt
kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt
kotlinx-coroutines-core/common/src/selects/Select.kt

This bug was introduced by #1524. The crux of problem is that
TryOffer/PollDesc.onPrepare method is no longer allowed to update
fields in these classes (like "resumeToken" and "pollResult") after call
to tryResumeSend/Receive method, because the latter will complete
the ongoing atomic operation and helper method might find it complete
and try reading "resumeToken" which was not initialized yet.
This change removes "pollResult" field which was not really needed
("result.pollResult" field is used) and removes "resumeToken" by
exploiting the fact that current implementation of
CancellableContinuationImpl does not need a token anymore. However,
CancellableContinuation.tryResume/completeResume ABI is left intact,
because it is used by 3rd party code.
This fix lead to overall simplification of …

Fix race condition in pair select

---

kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt

The following incorrect execution with parallel `offerInternal` and `isClosedForReceive` may occur:
1.  `offerInternal` increments `size`
2. `isClosedForReceive` reads `size == 1` and returns `false`, while the channel is closed and the buffer is actually empty
3. `offerInternal` detects that the channel is closed
4. `offerInternal` reverts `size` to the previous value (decrements)
Thus, `isClosedForReceive` can read an intermediate `size` state, and return incorrect results. To fix this, `isClosedForReceive` and `offerInternal` should not interfere.
Hopefully, this change also fixes #1526.

Fix ArrayChannel.isBufferEmpty atomicity

---

kotlinx-coroutines-core/common/test/flow/operators/MapTest.kt

We were testing onEach {} instead of map {} operator there.

Make MapTest - testErrorCancelsUpstream - actually test map operator

---

docs/exception-handling.md

**The original sentence was:**
"If a coroutine encounters exception other than `CancellationException`, it cancels its parent with that exception."
**I added an additional 'an' before 'exception':**
"If a coroutine encounters **an** exception other than `CancellationException`, it cancels its parent with that exception."

Improve sentence grammar by adding 'an'

---

kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/jvm/src/internal/LockFreeLinkedList.kt

This bug was introduced by PR #1524. It was reproducing when there
is a regular "send" operation on one side of a channel and
"select { onReceive }" on another side of the channel and the
"send" coroutine gets cancelled. The problem is that
SendElement.tryResumeSend implementation was calling finishPrepare
before it has successfully resumed continuation, so if that
continuation was already cancelled, the code in "finishPrepare" had
already stored the wrong affected node which it would later try to
call "completeResume" on.
This patch also adds hexAddress to the debug toString method of
all internal node classes in channel implementation.
Fixes #1588

Fix race in channel select/cancel

---

kotlinx-coroutines-core/common/src/CoroutineScope.kt

Seems like a javadoc points that all other children would be cancelled in case any other child coroutine would be cancelled or failed. Changed javadoc accordingly.

Typo in CoroutineScope's javadoc

---

kotlinx-coroutines-core/jvm/test/exceptions/StackTraceRecoveryTest.kt

Compiler now properly optimizes tail calls to suspendCancellableCoroutine
so we need to make sure it is not a tail call for this test

Fix StackTraceRecoveryTest.testCancellableContinuation for 1.3.60

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
docs/flow.md
kotlinx-coroutines-core/common/src/flow/Migration.kt
kotlinx-coroutines-core/common/test/flow/FlowInvariantsTest.kt

This migration was motivated by the limited invariant preservation check, which is now more advanced; Additionally, such migration prohibits meaningful use-cases like "compute value in encapsulated context and then emit in flow context"
Fixes #1616

Get rid of deprecated FlowCollector<*>.withContext

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/Unconfined.kt
kotlinx-coroutines-core/common/src/Yield.kt
kotlinx-coroutines-core/common/src/internal/DispatchedContinuation.kt
kotlinx-coroutines-core/common/test/ImmediateYieldTest.kt
kotlinx-coroutines-core/common/test/TestBase.common.kt
ui/kotlinx-coroutines-android/test/HandlerDispatcherTest.kt
ui/kotlinx-coroutines-javafx/src/JavaFxDispatcher.kt
ui/kotlinx-coroutines-javafx/test/JavaFxTest.kt
ui/kotlinx-coroutines-swing/test/SwingTest.kt

Support yield in immediate dispatchers

---

docs/basics.md
kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt
kotlinx-coroutines-core/common/src/Dispatchers.common.kt
kotlinx-coroutines-core/common/src/MainCoroutineDispatcher.kt

* Clarifications of CoroutineExceptionHandler execution
* Clarifications of MainCoroutineDispatcher.immediate
* Outdated documentation (pointed out by Google AndoidX team) for isDispatchNeeded is rewritten
Fixes #1650
Fixes #1651
Fixes #1634

Improve documentation

---

kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/common/test/flow/operators/OnCompletionTest.kt

* We cannot allow emitting elements when downstream exception occurred, otherwise it may lead to a weird side-effects when "collect" block (or any other terminal operator) has thrown an exception, but keeps receiving new values
* Another solution may be to silently ignore emitted values, but it may lead to a postponed cancellation and surprising behaviour for users
Fixes #1654

Rethrow downstream exception during "onCompletion" emissions

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/flow/internal/Merge.kt
kotlinx-coroutines-core/common/src/flow/operators/Merge.kt
kotlinx-coroutines-core/common/test/flow/operators/MergeTest.kt

Introduce merge operator

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-debug.txt
kotlinx-coroutines-debug/src/DebugProbes.kt
kotlinx-coroutines-debug/src/internal/DebugProbesImpl.kt

This method is required to simplify integration with IDEA during an arbitrary remote debugging session

Introduce DebugProbes.isInstalled method

---

kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt
kotlinx-coroutines-core/jvm/test/exceptions/StackTraceRecoveryTest.kt

Make sure that exception recovery does not break exception message

---

kotlinx-coroutines-core/jvm/src/CoroutineExceptionHandlerImpl.kt
kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt
kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt
ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-from-1.6.0/coroutines.pro
ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-upto-1.6.0/coroutines.pro
ui/kotlinx-coroutines-android/test/R8ServiceLoaderOptimizationTest.kt

`ServiceLoader` has proven itself as a very unstable mechanism on Android (see all the issues in a `loadMainDispatcherFactory` comment). Moreover, failures in SL are considered by `kotlinx.coroutines` users as errors in the library itself, making it look unstable. We are not really happy with that, so here is an attempt to avoid `ServiceLoader` on Android for `Dispatchers.Main`.
Though I am not sure whether this change should be merged in `kotlinx.coroutines`. Moreover, I am not sure how exactly to evaluate the potential impact of this change.
@wojtek-kalicinski and @JakeWharton could you please help with reviewing this change first?
Fixes #1557
Fixes #878

User Class.forName instead of ServiceLoader to instantiate Dispatchers.Main on Android

---

kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro

Proguard rule to keep volatile name of SafeContinuation

---

kotlinx-coroutines-core/common/src/flow/Channels.kt

The KDoc for `broadcastIn` looks to have been copy/pasted, and refers to `produce` (now `produceIn`) instead of itself.  
Similarly, the comment for `productIn` still refers to `produce`.

update `broadcastIn` and `produceIn` KDocs with correct names

---

kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt

The following non-linearizable execution can occur in `ArrayChannel` without this fix (here, capacity = 1):
```
| receive(): SUSPENDED + Closed    | offer(3): true             | receive():  3    |
|                                  | send(5):  SUSPENDED + void |                  |
|                                  | close(): true              |                  |
```
1. The 1st thread `receive()` checks whether the channel is empty.
2. `offer(3)` и `send(5)` from the 2nd thread are executed, the last one suspends.
3. The 3rd thread `receive()` retrieves `3` from the buffer and `send(5)` request from the waiting queue, resuming the last one. Thus, it holds the channel lock, but both the buffer and the waiting queue are empty (it should put `5` to the buffer)
4. After that, the 1st thread …

Fix non-linearizability in `ArrayChannel` while moving an element from the waiting queue to the buffer

---

binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt
kotlinx-coroutines-core/common/src/flow/Channels.kt
kotlinx-coroutines-core/common/test/flow/channels/ChannelBuildersFlowTest.kt

* Experimental ReceiveChannel.receiveAsFlow extension convert channel to flow in fan-out fashion allowing for multi-use.
* Also, ReceiveChannel.consumeAsFlow is promoted to experimental from preview
Fixes #1490

ReceiveChannel.receiveAsFlow extension

---

reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt
reactive/kotlinx-coroutines-reactive/test/PublisherAsFlowTest.kt
reactive/kotlinx-coroutines-reactor/test/FlowAsFluxTest.kt
reactive/kotlinx-coroutines-reactor/test/FluxContextTest.kt
reactive/kotlinx-coroutines-rx2/test/FlowableContextTest.kt

* When using asFlow().flowOn(...) context is now properly tracked and taken into account for both execution context of the reactive subscription and for injection into Reactor context.
* Publisher.asFlow slow-path implementation is simplified. It does not sure specialized openSubscription anymore, but always uses the same flow request logic.
Fixes #1765

Fix context support in Publisher.asFlow.flowOn

---

kotlinx-coroutines-core/common/src/selects/Select.kt

Just a quick drive-by discovered while browsing the source.

Remove extraneous word in comment

---

kotlinx-coroutines-debug/test/RunningThreadStackMergeTest.kt

`runBlocking` waits for all the threads it spawned to finish, so
if `verifyDump` failed in `RunningThreadStackMergeTest.kt`, the
tests would just hang: one of the threads would wait for a
barrier to break, which would never happen.
Maybe a commit this granular does not make sense in `develop` and should be cherry-picked in some other branch, for example, `jdk-11`, but that one is busy now.

Fix some tests hanging when `verifyDump` fails

---

kotlinx-coroutines-core/jvm/test/FieldWalker.kt
kotlinx-coroutines-core/jvm/test/ReusableCancellableContinuationTest.kt
kotlinx-coroutines-core/jvm/test/flow/ConsumeAsFlowLeakTest.kt

* Works on future JDKs that forbid reflective access to JDK classes
* Show human-readable path to field is something fails

Improve FieldWalker, don't access JDK classes

---

reactive/kotlinx-coroutines-rx2/test/LeakedExceptionTest.kt

See the commit message for the rationale.
I looked at the other uses of `withExceptionHandler`, and it seems that all the other executions are deterministic. I have slight doubts about `testExceptionAfterCancellation`, but, to my understanding, `blockingSubscribe` ensures that every execution is finished.

Fix a race in some tests for JavaRX integration

---

kotlinx-coroutines-core/jvm/test/AwaitStressTest.kt
kotlinx-coroutines-core/jvm/test/CancellableContinuationResumeCloseStressTest.kt
kotlinx-coroutines-core/jvm/test/ExecutorRule.kt

It is a non-goal to replace all existing executor usages in stress tests, replaced just a few for the demonstration

Introduce ExecutorRule for stress-tests for simpler development process

---

README.md
build.gradle
docs/debugging.md
kotlinx-coroutines-core/common/src/selects/Select.kt
kotlinx-coroutines-core/jvm/src/internal/Concurrent.kt
kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt
kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt
kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt
kotlinx-coroutines-core/jvm/src/scheduling/Dispatcher.kt
kotlinx-coroutines-core/jvm/src/scheduling/Tasks.kt
kotlinx-coroutines-core/jvm/test/scheduling/CoroutineSchedulerTest.kt
ui/kotlinx-coroutines-android/README.md
ui/kotlinx-coroutines-android/build.gradle
ui/kotlinx-coroutines-android/r8-test-rules.pro
ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-from-1.6.0/coroutines.pro
ui/kotlinx-coroutines-android/src/AndroidExceptionPreHandler.kt
ui/kotlinx-coroutines-android/testdata/r8-test-common.pro
ui/kotlinx-coroutines-android/testdata/r8-test-rules-no-optim.pro
ui/kotlinx-coroutines-android/testdata/r8-test-rules.pro

Optimize the size of the coroutines library in Android projects

---

kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt
kotlinx-coroutines-core/jvm/src/internal/LockFreeLinkedList.kt
kotlinx-coroutines-core/jvm/test/channels/ChannelSendReceiveStressTest.kt

Lock-free list implementation is considerably simplified, taking into
account a limited number of operations that it needs to support.
* prev pointers in the list are not marked for removal, since we
don't need to support linearizable backwards iteration.
* helpDelete method is completely removed. All "delete-helping" is
performed only by correctPrev method.
* correctPrev method bails out when the node it works on is removed to
reduce contention during concurrent removals.
* Special open methods "isRemoved" and "nextIfRemoved" are introduced
and are overriden in list head class (which is never removed).
This ensures that on long list "removeFist" operation (touching head)
does not interfere with "addLast" (touch tail). There is still
sharing of cache-lines in this case, but no helping …

Simpler and faster lock-free linked list

---

ui/kotlinx-coroutines-javafx/api/kotlinx-coroutines-javafx.api
ui/kotlinx-coroutines-javafx/src/JavaFxConvert.kt
ui/kotlinx-coroutines-javafx/src/JavaFxDispatcher.kt
ui/kotlinx-coroutines-javafx/test/JavaFxDispatcherTest.kt
ui/kotlinx-coroutines-javafx/test/JavaFxObservableAsFlowTest.kt
ui/kotlinx-coroutines-javafx/test/JavaFxStressTest.kt
ui/kotlinx-coroutines-javafx/test/examples/FxAsFlow.kt

Solves https://github.com/Kotlin/kotlinx.coroutines/issues/1695
It seems there is no way to implement this for `Observable` as it doesn't even expose the type of the observable value.

Implement ObservableValue<T>.asFlow()

---

kotlinx-coroutines-core/jvm/src/internal/LockFreeLinkedList.kt
kotlinx-coroutines-core/jvm/test/internal/LockFreeLinkedListAddRemoveStressTest.kt
kotlinx-coroutines-core/jvm/test/internal/LockFreeLinkedListAtomicLFStressTest.kt

* The problem was introduced by #1565. When doing concurrent add+removeFirst the following can happen:
- "add" completes, but has not correct prev pointer in next node yet
- "removeFirst" removes freshly added element
- "add" performs "finishAdd" that adjust prev pointer of the next node and thus removed element is pointed from the list again
* A separate LockFreeLinkedListAddRemoveStressTest is added that reproduces this problem.
* The old LockFreeLinkedListAtomicLFStressTest is refactored a bit.

Fixed memory leak on a race between adding/removing from lock-free list

---

reactive/kotlinx-coroutines-reactive/src/Await.kt
reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt
ui/kotlinx-coroutines-android/build.gradle
ui/kotlinx-coroutines-android/test/R8ServiceLoaderOptimizationTest.kt

Make call to service loader in reactor integrations optimizable by R8

---

integration/kotlinx-coroutines-jdk8/api/kotlinx-coroutines-jdk8.api
integration/kotlinx-coroutines-jdk8/src/time/Time.kt
integration/kotlinx-coroutines-jdk8/test/time/FlowDebounceTest.kt
integration/kotlinx-coroutines-jdk8/test/time/FlowSampleTest.kt

#1834 fixup

---

kotlinx-coroutines-test/README.md

There was a small mistake in the Readme of kotlinx-coroutines-test. A lateinit variable evaluated to null at the beginning.

Readme improvement

---

kotlinx-coroutines-core/common/src/channels/Broadcast.kt
kotlinx-coroutines-core/common/test/channels/BroadcastTest.kt
kotlinx-coroutines-core/jvm/src/channels/Actor.kt

ReceiveChannel.broadcast shall start lazy coroutine when closed

---

publication-validator/build.gradle

During the change of the publication validator, a bug was
introduced that led to MavenPublicationValidator being run not on
the artifacts from the local Maven repository but on classfiles
from the corresponding subproject. This is a problem because this
test is for the behavior of the atomicfu plugin, which could in
theory produce nice classfiles in one place but wrong ones in the
other, and the only important thing to test is whether the
published classfiles are good.
Now, this is fixed.

Fix publication validator not looking in the local maven repository

---

kotlinx-coroutines-core/common/src/EventLoop.common.kt
kotlinx-coroutines-core/jvm/src/DefaultExecutor.kt
kotlinx-coroutines-core/jvm/test/DefaultExecutorStressTest.kt
kotlinx-coroutines-core/jvm/test/channels/TickerChannelTest.kt

Solves https://github.com/Kotlin/kotlinx.coroutines/issues/856.

Fix DefaultExecutor not being able to exit

---

kotlinx-coroutines-core/common/src/channels/ArrayBroadcastChannel.kt
kotlinx-coroutines-core/jvm/test/channels/BroadcastChannelLeakTest.kt

When ArrayBroadcastChannel was closed it was still retaining a reference to its subscription (even if that subscription was cancelled) while, in fact, either closing a broadcast channel or cancelling subscription should remove the reference.
This is no problem with ConflatedBroadcastChannel, but it is added to the test for completeness.

Fix leak of subscription reference in closed ArrayBroadcastChannel

---

README.md

Correct what appears to be a typo in the description of the `JDK_18` environment variable in the README.

Correct JDK version typo

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/common/test/flow/operators/OnCompletionTest.kt
kotlinx-coroutines-core/common/test/flow/operators/OnEmptyTest.kt
kotlinx-coroutines-core/common/test/flow/operators/OnStartTest.kt

`onEmpty` operator seems like a missing building block that is pretty consistent with an existing Flow API.
`ifEmpty`, though, may be confusing for both Flow and advanced stdlib users:
* On the one hand, one may expect `flow.ifEmpty { value }` behaviour reasonable
* On the other hand, stdlib users may expect `ifEmpty` to have the following signature: `Flow<T>.ifEmpty(block: () -> Flow<T>)` with a slightly different behaviour (Rx analogue of `switchIfEmpty`)
Taking that into account, I've decided not to add it.
Also, experimental status is still here for all `Flow.on*` API (e.g. see #1732), let's remove it in 1.4.x or even 1.5.0

Flow onEmpty

---

docs/exception-handling.md
kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt
kotlinx-coroutines-core/jvm/test/guide/example-exceptions-01.kt
kotlinx-coroutines-core/jvm/test/guide/example-exceptions-02.kt
kotlinx-coroutines-core/jvm/test/guide/example-exceptions-04.kt
kotlinx-coroutines-core/jvm/test/guide/example-exceptions-05.kt
kotlinx-coroutines-core/jvm/test/guide/example-exceptions-06.kt
kotlinx-coroutines-core/jvm/test/guide/example-supervision-03.kt
kotlinx-coroutines-core/jvm/test/guide/test/ExceptionsGuideTest.kt

Improve docs for CoroutineExceptionHandler

---

gradle.properties
ui/kotlinx-coroutines-android/android-unit-tests/build.gradle
ui/kotlinx-coroutines-android/build.gradle
ui/kotlinx-coroutines-android/src/AndroidExceptionPreHandler.kt
ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt

Legacy -> new artifact mappings: https://developer.android.com/jetpack/androidx/migrate/artifact-mappings
The most recent version: https://developer.android.com/jetpack/androidx/releases/annotation

Migrate to androidx.annotation from legacy android.support.annotion

---

js/js-stub/build.gradle.kts

Kotlin DSL - 'js-stub'

---

stdlib-stubs/build.gradle.kts

Kotlin DSL - 'stdlib-stubs'

---

coroutines-guide.md
docs/flow.md
kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/common/test/flow/operators/OnCompletionTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/FlowGuideTest.kt

Flow.onCompletion now reports all failures and cancellation in its cause just like invokeOnCompletion. A null cause is reported if and only if flow had completed successfully (no failure, no cancellation). Emission of additional elements after the end of the flow is only possible from inside of onCompletion block in case of successful completion.
Also fixed a bug where onCompletion implementation was trying to add exception to its own list of suppressed exceptions, which is not allowed.
Fixes #1693

Breaking change: Experimental Flow.onCompletion contract for cause

---

kotlinx-coroutines-core/common/src/flow/Channels.kt
kotlinx-coroutines-core/common/src/flow/operators/Context.kt
kotlinx-coroutines-core/common/src/flow/operators/Distinct.kt
kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/common/src/flow/operators/Errors.kt
kotlinx-coroutines-core/common/src/flow/operators/Limit.kt
kotlinx-coroutines-core/common/src/flow/operators/Transform.kt
kotlinx-coroutines-core/common/src/flow/operators/Zip.kt
kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt
kotlinx-coroutines-core/common/src/flow/terminal/Count.kt
kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt

What's left:
* produceIn/broadcastIn, the former is yet TBD, the latter will be deprecated at some point
* scan/scanReduce will be renamed in a major release to be consistent with stdlib
* merge & co -- TBD parallelism
* onCompletion/onStart/onEmpty -- we may want to tweak it a little
* channelFlow/callbackFlow -- we may want to tweak it a little

Remove experimental status from Flow API

---

build.gradle
buildSrc/src/main/kotlin/JavaVersion.kt
ui/kotlinx-coroutines-javafx/build.gradle

Common java version method

---

build.gradle
buildSrc/src/main/kotlin/Platform.kt

Platform util in 'buildSrc'

---

js/example-frontend-js/src/ExampleMain.kt

* Deprecated API usage removed

Use standard random API

---

kotlinx-coroutines-core/jvm/src/internal/Concurrent.kt

I've failed to write a reliable test here. See also #571
Fixes #1992

Fix logic that determines future removal for scheduled executors

---

kotlinx-coroutines-core/jvm/src/Interruptible.kt

* Fix code formatting in doc example and make it more concise (both vertically and horizontally).
* Don't promote custom `withTimeout` logic in examples. Use the actual `withTimeout` function.
* Logical introduction of `context` parameter in docs (first use without it, then explain how it helps), consistent doc references.
* Improved implementation in various places:
* runInterruptibleInExpectedContext does not have to be suspend
* There is always Job in the context
* ThreadState should not do complex init in constructor (that's bad style)
* ThreadState does not need inner State class, atomic int is enough
* Consistent project-wide variable naming: state -> _state
* Consistent use of `error` function to throw IllegalStateException

Improve docs & code style in runInterruptibe

---

kotlinx-coroutines-core/common/src/flow/StateFlow.kt

Remove a reference to a missing close method from MutableStateFlow doc

---

build.gradle
buildSrc/src/main/kotlin/Idea.kt
buildSrc/src/main/kotlin/JavaVersion.kt
buildSrc/src/main/kotlin/jdk-convention.gradle.kts
settings.gradle
ui/kotlinx-coroutines-javafx/build.gradle

Part of #1938
* JDK 11
* Weak check for IDEA

Add project JDK convention 

---

kotlinx-coroutines-core/common/src/CompletableDeferred.kt
kotlinx-coroutines-core/common/src/CompletableJob.kt
kotlinx-coroutines-core/common/src/Deferred.kt
kotlinx-coroutines-core/common/src/Job.kt

* A more consistent prose in the Job interface documentation, gradually explaining concepts without repetition.
* Clear introduction and naming of "coroutine job" vs "completable job".
* Explanation of what is a "cancellation cause" of Job and how that relates to CancellationException.
* Added a note to all Job-derived interfaces that they are not safe for inheritance in 3rd party libraries.
* Consistently copied a note on thread-safety to all job-derived interfaces.

Improved Job docs

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Dokka.kt
reactive/kotlinx-coroutines-reactive/build.gradle.kts
ui/kotlinx-coroutines-android/build.gradle.kts

Add Dokka configuration method

---

benchmarks/build.gradle.kts
site/build.gradle.kts

Avoid task name duplication

---

build.gradle
gradle/compile-js.gradle
js/example-frontend-js/build.gradle
js/example-frontend-js/npm/webpack.config.js

Use new Kotlin/JS plugin

---

gradle/compile-js-multiplatform.gradle
gradle/publish-npm-js.gradle
gradle/test-mocha-js.gradle
js/example-frontend-js/build.gradle

- Migrate names to 1.4-M2 in both mode with compatibility with 1.3.7x versions

Adopt Kotlin/JS for 1.4-M2

---

kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro

The rule -keepnames class kotlinx.coroutines.android.AndroidDispatcherFactory {} is present in kotlinx.coroutines.android/META-INF/proguard/coroutines.pro and should therefore not be needed. If the -keepnames class kotlinx.coroutines.android.AndroidExceptionPreHandler {} is needed, it should go into kotlinx.coroutines.android/META-INF/proguard/coroutines.pro

Remove keep rules mentioning kotlinx.coroutines.android

---

coroutines-guide.md
docs/flow.md
kotlinx-coroutines-core/common/src/flow/Builders.kt
kotlinx-coroutines-core/common/src/flow/operators/Context.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-37.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-38.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-39.kt
kotlinx-coroutines-core/jvm/test/guide/test/FlowGuideTest.kt

* Remove outdated phrase on "flow infrastructure does not introduce additional cancellation points". They were introduced by #2028
* Add a section on "Flow cancellation check" with examples on `Flow.cancellable()`` operator.
* Add a bit more detail in `flow` and `cancellable` docs with links to `ensureActive()`.

Improve the docs and guide on flow cancellation

---

docs/flow.md
kotlinx-coroutines-core/common/src/Unconfined.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt
kotlinx-coroutines-core/jvm/src/scheduling/Dispatcher.kt
kotlinx-coroutines-core/jvm/src/scheduling/Tasks.kt
kotlinx-coroutines-core/jvm/test/guide/test/FlowGuideTest.kt

Recognizable toString is not only pretty and aligned with our own glossary, but also significantly affects "group by dispatcher" feature in the upcoming IDEA debugger, see the screenshot: https://imgur.com/a/2zqM5pn
The second commit is just nice to have while we are here

Minor improvements of debugging experience

---

kotlinx-coroutines-core/common/src/flow/operators/Zip.kt

Code examples of those operators were using the deprecated `delayEach` function. This rewrites them with `onEach { delay(n) }`.

Fix examples in docs for combine and zip operators

---

benchmarks/src/jmh/kotlin/benchmarks/flow/TakeWhileBenchmark.kt
kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/common/src/flow/operators/Limit.kt
kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt
kotlinx-coroutines-core/common/test/flow/FlowInvariantsTest.kt
kotlinx-coroutines-core/common/test/flow/operators/TransformWhileTest.kt

Also, all flow-truncating operators are refactored via a common internal collectWhile operator that properly uses AbortFlowException and checks for its ownership, so that we don't have to look for bugs in interactions between all those operators (and zip, too, which is also flow-truncating).
Fixes #2065

Flow.transformWhile operator

---

docs/flow.md
kotlinx-coroutines-core/jvm/test/guide/example-flow-01.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-02.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-03.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-04.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-05.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-06.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-13.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-14.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-15.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-16.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-17.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-18.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-19.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-26.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-27.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-28.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-29.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-30.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-31.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-32.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-33.kt
kotlinx-coroutines-core/jvm/test/guide/example-flow-34.kt
kotlinx-coroutines-core/jvm/test/guide/test/FlowGuideTest.kt

The name 'foo' might be hard to get for novice developers. It is really hard to find a "meaningful" name for all examples in the docs, so this is simply a consistent solution. The alternative is to something like "simpleFlow", but adding a "Flow" suffix to the name implicitly condones Hungarian notation, which is not aligned with Kotlin coding style.

Rename 'foo' function to 'simple' in flow docs

---

reactive/kotlinx-coroutines-jdk9/test/FlowAsPublisherTest.kt
reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt
reactive/kotlinx-coroutines-reactive/test/FlowAsPublisherTest.kt
reactive/kotlinx-coroutines-reactive/test/PublisherRequestStressTest.kt

The race was leading to emitting more items via onNext than requested, the corresponding stress-test was added, too
Fixes #2109

Fix race in Flow.asPublisher

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/MainCoroutineDispatcher.kt
kotlinx-coroutines-core/js/src/Dispatchers.kt
kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt
kotlinx-coroutines-core/jvm/test/DispatchersToStringTest.kt
kotlinx-coroutines-core/native/src/Dispatchers.kt
ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt
ui/kotlinx-coroutines-android/test/HandlerDispatcherTest.kt
ui/kotlinx-coroutines-javafx/src/JavaFxDispatcher.kt
ui/kotlinx-coroutines-javafx/test/JavaFxDispatcherTest.kt
ui/kotlinx-coroutines-swing/src/SwingDispatcher.kt
ui/kotlinx-coroutines-swing/test/SwingTest.kt

So that is shows as "Dispatchers.Main" and "Dispatchers.Main.immediate"

Consistent toString for MainCoroutineDispatcher implementations

---

kotlinx-coroutines-core/build.gradle
kotlinx-coroutines-core/jvm/test/RunInterruptibleStressTest.kt

The test is improved so that it fails, not hangs, on a failure. However, it will not pass on Windows + JDK 1.6 due to a bug in JDK (which can be easily confirmed with this modification to a test), so it excluded when running on JDK 1.6.
Fixes #2144

Fix hanging RunInterruptibleStressTest on Windows with JDK 1.6

---

kotlinx-coroutines-core/common/src/CancellableContinuation.kt

Basically reverts the documentation update in #800 due to the changes in #896

Fix docs for CancellableContinuation

---

ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-from-1.6.0/coroutines.pro

In commit #3a8a0ea this keep rule was removed from kotlinx-coroutines-core (which is good), but this caused `AndroidDispatcherFactory` to be minimized in newer R8 versions. Adding a rule explicitly fixes the problem.
I didn't succeed in making a sample project to reproduce the issue, as the project that faces this issue has a complex multi module setup (which might be the cause). I verified this change is working by including the local `kotlinx-coroutines-android` jar in the project and not getting the following error:
```
Fatal Exception: java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
at …
```

Add a keep rule for AndroidDispatcherFactory for R8 version > 1.6.0

---

docs/flow.md

For some reason, some sample outputs in section `Flow Exceptions` are not displayed in the documentation. This commit fixes this issue.

Fix some sample outputs not being displayed in flow.md

---

buildSrc/src/main/kotlin/Idea.kt
kotlinx-coroutines-core/js/src/Dispatchers.kt
kotlinx-coroutines-core/js/test/ImmediateDispatcherTest.kt
kotlinx-coroutines-core/jvm/src/Executors.kt
kotlinx-coroutines-core/native/src/Dispatchers.kt
ui/kotlinx-coroutines-android/build.gradle.kts

* Immediate dispatcher on JS, test added
* Style fixes

Cherry-picks from native-mt branch to reduce maintenance burden

---

kotlinx-coroutines-core/common/src/CoroutineScope.kt

This is leftover from #2044 fix.
Fixes #2241

Fixed CoroutinesScope.ensureActive docs

---

build.gradle
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/CacheRedirector.kt

On CI set CACHE_REDIRECTOR=true environment property.

Support JetBrains cache-redirector service for stable CI builds

---

reactive/kotlinx-coroutines-reactive/api/kotlinx-coroutines-reactive.api
reactive/kotlinx-coroutines-reactive/src/Await.kt
reactive/kotlinx-coroutines-reactive/test/IntegrationTest.kt
reactive/kotlinx-coroutines-reactor/test/FluxSingleTest.kt

This commit adds `awaitSingle` variants similar to `awaitFirst` ones, but always emitting the value during `onComplete()`.
Fixes #1993

Add Publisher.awaitSingleOrDefault|Null|Else extensions

---

kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt

It seems to be the legacy from times when CC was a Job, in order to observe behaviour change, a specific example should be accurately made.
Note that this changes the behaviour of the following (weird, but still) test:
```
@Test
fun suspendCancellableContinuationParentStart() = runTest {
val job = launch(start = CoroutineStart.LAZY) { println("Aha!") }
::suspendCancellable.startCoroutine(Continuation(job) {})
}
suspend fun suspendCancellable() = suspendCancellableCoroutine<Int> { 
it.resumeWith(Result.success(42))
}
```

Remove parent.start() from CancellableContinuationImpl.kt

---

kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro

Solves https://github.com/Kotlin/kotlinx.coroutines/issues/2046 and
https://github.com/Kotlin/kotlinx.coroutines/issues/2266.
I tested these issues separately, reproduced both problems and checked that this edit solves them, but I'm not sure whether we should also test for this. Maybe make the example Android projects part of the build conditionally?

Fix proguard rules

---

CONTRIBUTING.md

The wording is a bit confusing and does not clearly indicate that you can set `JDK_XX` to whatever JDK version you want.

Clarify the env requirements in CONTRIBUTING.md

---

kotlinx-coroutines-core/jvm/src/Dispatchers.kt

Clarify documentation for IO dispatcher

---

docs/knit.properties
docs/knit.test.template
gradle.properties
knit.properties
kotlinx-coroutines-core/common/src/flow/operators/Delay.kt
kotlinx-coroutines-core/jvm/test/examples/example-delay-01.kt
kotlinx-coroutines-core/jvm/test/examples/example-delay-02.kt
kotlinx-coroutines-core/jvm/test/examples/example-delay-duration-01.kt
kotlinx-coroutines-core/jvm/test/examples/example-delay-duration-02.kt
kotlinx-coroutines-core/jvm/test/examples/test/FlowDelayTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/BasicsGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/CancellationGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/ChannelsGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/ComposingGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/DispatcherGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/ExceptionsGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/FlowGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/SelectGuideTest.kt
kotlinx-coroutines-core/jvm/test/guide/test/SharedStateGuideTest.kt
kotlinx-coroutines-core/jvm/test/knit/TestUtil.kt
kotlinx-coroutines-core/knit.properties

* All Flow.debounce/sample KDoc example code snippets are automatically tested with Knit.
* Flow.sample timings are made larger, so that they produce an expected output when run under the real time, too.
Fixes #2243

Update Flow.sample KDoc example timings, add tests

---

coroutines-guide.md
docs/cancellation-and-timeouts.md
kotlinx-coroutines-core/common/src/Timeout.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-08.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-09.kt
kotlinx-coroutines-core/jvm/test/guide/test/CancellationGuideTest.kt

This is a tricky gotcha that needs additional explanation. There are two examples added, one showing the bad code and explaining why it does not work, and the other showing the correct way to write it.
Fixes #2233

Added docs on withTimeout asynchrony and its use with resources

---

README.md
kotlinx-coroutines-debug/README.md

Added instructions to work around #2023.
Also, the answer to #2274 is now documented.

Document problems with building coroutines-using Android projects

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/Job.kt
kotlinx-coroutines-core/common/test/JobExtensionsTest.kt
kotlinx-coroutines-core/jvm/src/Interruptible.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt

Introduce CoroutineContext.job extension

---

kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/jvm/src/flow/internal/SafeCollector.kt
kotlinx-coroutines-core/jvm/test/flow/OnCompletionInterceptedReleaseTest.kt

Unfortunately, I wasn't able to find any meaningful scenario (=> write a test) when this actually leads to a memory leak for the existing set of API.  But still, this is a time bomb waiting to explode

Release intercepted SafeCollector when onCompletion block is done

---

kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
kotlinx-coroutines-core/common/test/flow/sharing/SharedFlowScenarioTest.kt

Problematic scenario:
* Emitter suspends because there is a slow subscriber
* Fast subscriber collects all the values and suspend
* Slow subscriber resumes, collects value, causes emitter to be resume
* Fast subscribers must be resumed in this case, too
Fixes #2320

Fix SharedFlow with replay for subscribers working at different speed

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/flow/operators/Delay.kt
kotlinx-coroutines-core/common/test/flow/operators/DebounceTest.kt
kotlinx-coroutines-core/jvm/test/examples/example-delay-03.kt
kotlinx-coroutines-core/jvm/test/examples/example-delay-duration-03.kt
kotlinx-coroutines-core/jvm/test/examples/test/FlowDelayTest.kt

Adding support for debounce selector to allow changing debounce time based on the latest emitted value.
Resolves #1216.
Based on PR #2314

Add debounce selector

---

kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
kotlinx-coroutines-core/common/test/flow/sharing/SharedFlowScenarioTest.kt
kotlinx-coroutines-core/jvm/test/flow/SharedFlowStressTest.kt

* Added a specific test for a problematic scenario.
* Added stress test with concurrent emitters and subscribers that come and go.
Fixes #2356

SharedFlow: Fix scenario with concurrent emitters and cancellation of subscriber

---

CHANGES.md
README.md
RELEASE.md
gradle.properties
kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
kotlinx-coroutines-core/common/test/flow/sharing/SharedFlowScenarioTest.kt
kotlinx-coroutines-core/jvm/test/flow/SharedFlowStressTest.kt
kotlinx-coroutines-debug/README.md
kotlinx-coroutines-test/README.md
ui/coroutines-guide-ui.md
ui/kotlinx-coroutines-android/animation-app/gradle.properties
ui/kotlinx-coroutines-android/example-app/gradle.properties

This is a patch release with an important fix to the `SharedFlow` implementation.
* SharedFlow: Fix scenario with concurrent emitters and cancellation of subscriber (#2359, thanks to @vehovsky for the bug report).

Version 1.4.1

---

kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/selects/Select.kt
kotlinx-coroutines-core/jvm/src/Future.kt

Simplify JobNode.toString to reduce code and avoid potential StackOverflow

---

kotlinx-coroutines-core/common/src/flow/operators/Lint.kt

Add lint warnings on SharedFlow operations that never complete

---

kotlinx-coroutines-core/common/src/flow/SharingStarted.kt
kotlinx-coroutines-core/common/test/flow/sharing/ShareInTest.kt

It was a part of the original design, but was forgotten because prototype was developer before Kotlin 1.4.0.
It makes implementing custom SharingStarted strategies more concise.

Make SharingStarted a fun interface

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
kotlinx-coroutines-core/common/src/flow/StateFlow.kt

* Override MutableSharedFlow.emit to attach a more appropriate docs than the one inherited from FlowCollector.
* Clarify thread-safety of all the MutableSharedFlow & MutableState "mutating" methods.
The latter is needed, because Flows, in general, are sequential, but shared flows provide all the necessarily synchronization themselves, so, to avoid confusion it makes sense to additionally mention thread-safety of shared flows in all the relevant mutating functions.

Clarify thread-safety of SharedFlow methods in docs

---

kotlinx-coroutines-core/common/src/Builders.common.kt

Clarify withContext(NonCancellable) behavior

---

build.gradle
gradle/compile-jvm-multiplatform.gradle
gradle/compile-jvm.gradle
kotlinx-coroutines-core/build.gradle
kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt
kotlinx-coroutines-core/common/src/selects/SelectUnbiased.kt
kotlinx-coroutines-core/jvm/src/internal/LockFreeLinkedList.kt
kotlinx-coroutines-debug/build.gradle

To be used in specific kotlinx-train CI configuration. It's needed for faster adoption of JVM IR compiler.

Add build parameter to build coroutines with JVM IR compiler

---

ui/kotlinx-coroutines-javafx/build.gradle.kts

Remove platform-specific dependencies on JavaFx artifacts

---

integration/kotlinx-coroutines-guava/src/ListenableFuture.kt
integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt

Implement bidirectional cancellation for `future` coroutine builder.
This also:
* Refactors JobListenableFuture infrastructure so it can be reused in CoroutineScope.future and Deferred.asListenableFuture;
* Provides more descriptive `toString` implementation for the returned Future;
* Fixes stack traces in thrown exception, so it includes call to get() that triggered the exception to be thrown;
* Hides ListenableFuture.asDeferred return type, so it can't be casted to CompletableDeferred;
* Adds more tests to cover fixed corner cases;
* Improves documentation;
* Suppresses annoying warnings in tests.

Repair some corner cases in cancellation propagation between coroutines and listenable futures 

---

kotlinx-coroutines-core/common/src/flow/operators/Zip.kt

This fixes #2419 by updating the 4-parameter version of combine to use the optimized `combineUnsafe`.

Use combineUnsafe for 4 parameter combine

---

kotlinx-coroutines-core/common/src/CoroutineStart.kt
kotlinx-coroutines-core/common/src/channels/Channels.common.kt
kotlinx-coroutines-core/jvm/src/CommonPool.kt
kotlinx-coroutines-core/jvm/src/CoroutineContext.kt
kotlinx-coroutines-core/jvm/src/Dispatchers.kt
kotlinx-coroutines-core/jvm/src/ThreadPoolDispatcher.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugCoroutineInfoImpl.kt
kotlinx-coroutines-core/jvm/src/flow/internal/SafeCollector.kt
kotlinx-coroutines-core/jvm/src/internal/Concurrent.kt
kotlinx-coroutines-core/jvm/src/internal/LockFreeLinkedList.kt
kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt
kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt
kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt
kotlinx-coroutines-debug/src/CoroutineInfo.kt

* Remove explicit API mode suppressions
* Use list build in ReceiveChannel.toList to prevent casting to mutable list
* Migrate to maxByOrNull
* Remove redundant nullabilities

Cleanup core module after update to Kotlin 1.4

---

build.gradle
gradle/publish-bintray.gradle

* Remove conditional publication that is compatible with Kotlin 1.3.70 plugin
* Get rid of workaround in old MPP plugin with dependency renaming

Gradle stewardship

---

kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt
kotlinx-coroutines-debug/test/SanitizedProbesTest.kt

Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/1437

Preserve a frame with source code location when sanitizing traces

---

kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt
kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt
kotlinx-coroutines-core/common/src/channels/LinkedListChannel.kt
kotlinx-coroutines-core/common/test/channels/ChannelUndeliveredElementTest.kt

Fix LinkedListChannel.onUndeliveredElement call on channel cancel

---

README.md
gradle.properties
js/example-frontend-js/build.gradle

+ Remove Kotlin/JS example workaround

Update to Kotlin 1.4.21

---

kotlinx-coroutines-core/common/src/EventLoop.common.kt
kotlinx-coroutines-core/js/src/EventLoop.kt
kotlinx-coroutines-core/jvm/src/EventLoop.kt
kotlinx-coroutines-core/nativeDarwin/src/EventLoop.kt
kotlinx-coroutines-core/nativeDarwin/test/AutoreleaseLeakTest.kt
kotlinx-coroutines-core/nativeOther/src/EventLoop.kt

Resolves #2322
While 1.4.30-M1 fixed `Worker.execute()` leaking ObjC autoreleasing objects when running native code on a K/N Worker thread ([KT-42822](https://youtrack.jetbrains.com/issue/KT-42822)), it does not address the issue at KoltinX Coroutines framework level.
More specifically, when tasks on an EventLoop call into native code, any autoreleasing object — especially many ObjC method return values — is effectively leaked <sup>[1]</sup>. This is because [the first available autoreleasepool in the call stack is in `workerMain()`, and it wraps around a most likely never-returning <sup>[2]</sup> `runEventLoop()`](https://github.com/Kotlin/kotlinx.coroutines/blob/89a9f7d53c7add3492d0846b5dbd623ab5b5d81d/kotlinx-coroutines-core/native/src/Workers.kt#L46-L52). 
This PR introduced a failing …

[native-mt] Fix ObjC autorelease object leaks with native-mt dispatchers

---

kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt
kotlinx-coroutines-core/nativeDarwin/test/MainDispatcherTest.kt

Resolves https://github.com/Kotlin/kotlinx.coroutines/issues/2283
First commit includes a test case that fails in both macosx64 background & main tests.

[native-mt] Fix the errornous isDispatchNeeded check in Dispatchers.Main.immediate on Darwin platforms.

---

kotlinx-coroutines-core/common/src/channels/Channels.common.kt
kotlinx-coroutines-core/common/test/BuilderContractsTest.kt

Add callsInPlace to ReceiveChannel.consume

---

README.md

Restructure README (multiplatform)

---

integration/kotlinx-coroutines-guava/src/ListenableFuture.kt
integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt
integration/kotlinx-coroutines-guava/test/ListenableFutureToStringTest.kt

Mirror of https://github.com/Kotlin/kotlinx.coroutines/pull/2422

Do not throw from JobListenableFuture.isCancelled 

---

kotlinx-coroutines-core/common/src/CoroutineStart.kt
kotlinx-coroutines-core/common/test/AtomicCancellationCommonTest.kt

Promote CoroutineStart.UNDISPATCHED to non experimental API

---

benchmarks/src/jmh/kotlin/benchmarks/ChannelSinkBenchmark.kt
benchmarks/src/jmh/kotlin/benchmarks/ChannelSinkDepthBenchmark.kt
kotlinx-coroutines-core/common/src/Builders.common.kt
kotlinx-coroutines-core/common/src/CoroutineContext.common.kt
kotlinx-coroutines-core/common/src/internal/DispatchedContinuation.kt
kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt
kotlinx-coroutines-core/js/src/CoroutineContext.kt
kotlinx-coroutines-core/jvm/src/Builders.kt
kotlinx-coroutines-core/jvm/src/CoroutineContext.kt
kotlinx-coroutines-core/jvm/src/internal/ThreadContext.kt
kotlinx-coroutines-core/jvm/test/ThreadContextElementRestoreTest.kt
kotlinx-coroutines-core/native/src/CoroutineContext.kt

This fix solves the problem of restoring thread-context when returning to another context in undispatched way. It impacts suspend/resume performance of coroutines that use ThreadContextElement since we have to walk up the coroutine completion stack in search for
parent UndispatchedCoroutine. However, there is a fast-path to ensure that there is no performance impact in cases when ThreadContextElement is not used by a coroutine.
Fixes #985

Restore thread context elements when directly resuming to parent

---

kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt
kotlinx-coroutines-core/jvm/src/internal/ThreadContext.kt
kotlinx-coroutines-core/jvm/test/ThreadContextOrderTest.kt

* Restore the context in the reverse order of update, so they are properly nested into each other
* Also, do a minor cleanup
Fixes #2195

Properly nest ThreadContextElement

---

docs/topics/coroutines-basic-jvm.md

Changed the coroutines JVM tutorial to reference Maven Central [instead of JCenter](https://twitter.com/kotlin/status/1357261339379576841).

Removed JCenter from the tutorial

---

kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt

`RunningThreadStackMergeTest.testStackMergeWithContext` was failing:
https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxTrain_Kotlin140_LibrariesBranchesFor150Release/3329282?buildTab=tests&status=failed&expandedTest=4424896350783031328
`kotlinx.coroutines.debug.internal.DebugProbesImpl.updateState`
sometimes parks in order to acquire a lock, which leads BlockHound
to detect an illegal blocking call. Now, blocking calls inside
`DebugProbesImpl` are permitted. Though allowing `updateState`
would suffice, the other users of the lock seem safe, too, and are
allowed even when it doesn't make much sense to call them from
coroutines.

Fix a test that was flaky because of BlockHound

---

build.gradle
buildSrc/src/main/kotlin/kotlin-jvm-conventions.gradle.kts
integration-testing/build.gradle
kotlinx-coroutines-debug/build.gradle
reactive/kotlinx-coroutines-rx2/build.gradle
reactive/kotlinx-coroutines-rx3/build.gradle

They were deprecated long time ago and were removed in Gradle 7.

Fix build script compilation issues

---

README.md

- Add articles.
- Fix words.
- Fix capitalization.

Improve readability.

---

kotlinx-coroutines-core/common/src/Job.kt

Fix Job.children docs

---

kotlinx-coroutines-core/common/src/flow/operators/Merge.kt

Mention default buffering in flattenMerge documentation

---

kotlinx-coroutines-core/common/src/Job.kt

* It slightly cuts down startup time
* It simplifies the code in general
* It do not serve its purpose, coroutines are already protected from StackOverflowError with nested event-loops where applicable

Do not initialize CoroutineExceptionHandler in Job <clinit>

---

kotlinx-coroutines-core/jvm/test/lincheck/SemaphoreLincheckTest.kt

Fixes the Lincheck test for Semaphore, see
https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxTrain_Kotlin140_LibrariesBranchesFor150Release/3383227
https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxTrain_Kotlin140_LibrariesBranchesFor150Release/3388024

Allow extra suspension in Lincheck tests for `Semaphore.acquire()`

---

kotlinx-coroutines-core/common/src/CancellableContinuation.kt
kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/internal/DispatchedContinuation.kt
kotlinx-coroutines-core/jvm/test/CancelledAwaitStressTest.kt
kotlinx-coroutines-core/jvm/test/FieldWalker.kt
kotlinx-coroutines-core/jvm/test/ReusableCancellableContinuationLeakStressTest.kt

* Update initCancellability documentation and implementation to be aligned with current invariants
* Make parentHandle non-volatile and ensure there are no races around it
* Establish new reusability invariants
- Reusable continuation can be used _only_ if it's state is not REUSABLE_CLAIMED
- If it is, spin-loop and wait for release
- Now the parent is attached to reusable continuation only if it was suspended at least once. Otherwise, the state machine can return via fast-path and noone will be able to release intercepted continuation (-> detach from parent)
- It implies that the parent is attached after trySuspend call and can be concurrently reused, this is where new invariant comes into play
Fixes #2564

Rework reusability control in cancellable contination

---

kotlinx-coroutines-core/common/src/Job.kt

Fix wrong docs on Job.join

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt
kotlinx-coroutines-core/common/src/channels/ArrayChannel.kt
kotlinx-coroutines-core/common/src/channels/Channel.kt
kotlinx-coroutines-core/common/src/channels/ConflatedBroadcastChannel.kt
kotlinx-coroutines-core/jvm/src/channels/Channels.kt
reactive/kotlinx-coroutines-reactive/api/kotlinx-coroutines-reactive.api
reactive/kotlinx-coroutines-reactive/src/Publish.kt
reactive/kotlinx-coroutines-rx2/src/RxObservable.kt
reactive/kotlinx-coroutines-rx3/src/RxObservable.kt

Also, give it default stub implementation and remove it from all the subclasses. This implementation previously was partially correct, was used as a performance optimization and can be safely introduced for a marginally popular method

Remove deprecated SendChannel.isFull 

---

reactive/kotlinx-coroutines-reactor/src/Mono.kt
reactive/kotlinx-coroutines-reactor/test/MonoTest.kt

Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/2262

Complete mono { } on cancellation

---

docs/topics/debug-coroutines-with-idea.md

Fix invalid link to api doc for `println()` function.

Fix bad link in debug-coroutines-with-idea.md

---

reactive/kotlinx-coroutines-reactive/src/Await.kt
reactive/kotlinx-coroutines-reactive/test/IntegrationTest.kt

Reactive Streams' Subscriber's implementation for `await*` operations was assuming that the publisher is correct. Now, the implementation detects some instances of problematic behavior for publishers and reports them.
Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/2079

Make the subscriber in awaitOne less permissive

---

reactive/kotlinx-coroutines-reactor/test/MonoTest.kt

This change's gist is that `mono` is being run in the unconfined dispatcher and not in the default one. There were all sorts of nasty races due to `mono` being passed to the default workers, while here, everything seems deterministic.

Fix a flaky test in MonoTest

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/flow/Builders.kt
kotlinx-coroutines-core/jvm/src/channels/Channels.kt
kotlinx-coroutines-core/jvm/test/VirtualTimeSource.kt
kotlinx-coroutines-core/jvm/test/channels/ChannelsJvmTest.kt
kotlinx-coroutines-core/jvm/test/flow/StateFlowStressTest.kt
kotlinx-coroutines-core/jvm/test/scheduling/SchedulerTestBase.kt
reactive/kotlinx-coroutines-rx2/src/RxConvert.kt
reactive/kotlinx-coroutines-rx3/src/RxConvert.kt

* Introduce trySendBlocking and deprecate sendBlocking
* Use it in callbackFlow example
* Stabilize callbackFlow and channelFlow as they finally have error-safe API
* Irrelevant: migrate from deprecated stdlib API to be able to build with Kotlin 1.5

Embrace new channel API

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/flow/operators/Transform.kt
kotlinx-coroutines-core/common/test/flow/operators/ScanTest.kt

* Otherwise Kotlin users with non-reactive background get confused by flow/stdlib inconsistency
* Make it experimental to delay the final decision about the name
Fixes #2641

Introduce runningFold operator, make scan alias to runningFold

---

reactive/kotlinx-coroutines-jdk9/test/FlowAsPublisherTest.kt
reactive/kotlinx-coroutines-jdk9/test/IntegrationTest.kt
reactive/kotlinx-coroutines-jdk9/test/PublishTest.kt
reactive/kotlinx-coroutines-reactive/src/Publish.kt
reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt
reactive/kotlinx-coroutines-reactive/test/FlowAsPublisherTest.kt
reactive/kotlinx-coroutines-reactive/test/IntegrationTest.kt
reactive/kotlinx-coroutines-reactive/test/PublishTest.kt
reactive/kotlinx-coroutines-reactive/test/PublisherRequestStressTest.kt
reactive/kotlinx-coroutines-reactor/src/Flux.kt
reactive/kotlinx-coroutines-reactor/src/Mono.kt
reactive/kotlinx-coroutines-reactor/test/FluxTest.kt
reactive/kotlinx-coroutines-rx2/README.md
reactive/kotlinx-coroutines-rx2/src/RxCancellable.kt
reactive/kotlinx-coroutines-rx2/src/RxCompletable.kt
reactive/kotlinx-coroutines-rx2/src/RxMaybe.kt
reactive/kotlinx-coroutines-rx2/src/RxObservable.kt
reactive/kotlinx-coroutines-rx2/src/RxSingle.kt
reactive/kotlinx-coroutines-rx2/test/FlowableExceptionHandlingTest.kt
reactive/kotlinx-coroutines-rx2/test/IntegrationTest.kt
reactive/kotlinx-coroutines-rx2/test/ObservableExceptionHandlingTest.kt
reactive/kotlinx-coroutines-rx3/src/RxCancellable.kt
reactive/kotlinx-coroutines-rx3/src/RxCompletable.kt
reactive/kotlinx-coroutines-rx3/src/RxMaybe.kt
reactive/kotlinx-coroutines-rx3/src/RxObservable.kt
reactive/kotlinx-coroutines-rx3/src/RxSingle.kt
reactive/kotlinx-coroutines-rx3/test/FlowableExceptionHandlingTest.kt
reactive/kotlinx-coroutines-rx3/test/IntegrationTest.kt
reactive/kotlinx-coroutines-rx3/test/ObservableExceptionHandlingTest.kt

* Fixed `PublisherCoroutine`, `rxObservable`, and
`Flow.toPublisher` ignoring cancellations.
* Fatal exceptions are not treated in a special manner by us
anymore. Instead, we follow the requirement in the reactive
streams specification that, in case some method of `Subscriber`
throws, that subscriber MUST be considered canceled, and the
exception MUST be reported in someplace other than `onError`.
* Fixed `trySend` sometimes throwing in `PublisherCoroutine` and
`rxObservable`.
* When an exception happens inside a cancellation handler, we now
consistently throw the original exception passed to the handler,
with the new exception added as suppressed.
* Fixed `PublisherCoroutine` and `rxObservable` claiming that the
channel is not closed for send for some time after `close()` has
finished.
* …

Consistently handle exceptions in reactive streams

---

docs/topics/coroutines-guide.md

Update the links to the additional references
https://youtrack.jetbrains.com/issue/KT-45090
KT-45090 Broken link for "Guide to UI programming with coroutines"

update: update coroutines-guide.md

---

reactive/kotlinx-coroutines-jdk9/src/Await.kt
reactive/kotlinx-coroutines-jdk9/test/AwaitTest.kt
reactive/kotlinx-coroutines-reactive/src/Await.kt
reactive/kotlinx-coroutines-reactive/test/AwaitTest.kt
reactive/kotlinx-coroutines-reactor/api/kotlinx-coroutines-reactor.api
reactive/kotlinx-coroutines-reactor/src/Mono.kt
reactive/kotlinx-coroutines-reactor/src/ReactorContext.kt
reactive/kotlinx-coroutines-reactor/test/FlowAsFluxTest.kt
reactive/kotlinx-coroutines-reactor/test/FluxSingleTest.kt
reactive/kotlinx-coroutines-reactor/test/MonoTest.kt
reactive/kotlinx-coroutines-reactor/test/ReactorContextTest.kt
reactive/kotlinx-coroutines-rx2/api/kotlinx-coroutines-rx2.api
reactive/kotlinx-coroutines-rx2/src/RxAwait.kt
reactive/kotlinx-coroutines-rx2/test/CompletableTest.kt
reactive/kotlinx-coroutines-rx2/test/MaybeTest.kt
reactive/kotlinx-coroutines-rx2/test/ObservableSingleTest.kt
reactive/kotlinx-coroutines-rx2/test/SingleTest.kt
reactive/kotlinx-coroutines-rx3/api/kotlinx-coroutines-rx3.api
reactive/kotlinx-coroutines-rx3/src/RxAwait.kt
reactive/kotlinx-coroutines-rx3/test/CompletableTest.kt
reactive/kotlinx-coroutines-rx3/test/MaybeTest.kt
reactive/kotlinx-coroutines-rx3/test/ObservableSingleTest.kt
reactive/kotlinx-coroutines-rx3/test/SingleTest.kt

This PR
* Deprecates `awaitSingleOr*` on arbitrary Publishers
* Adds specialized `awaitSingle` and `awaitSingleOrNull` methods on `Maybe<T>` and `Mono<T>`
* Deprecates `Maybe<T>.await()` in favor of `Maybe<T>.awaitSingleOrNull()`
* Adds specializations of most of the `await*` methods for `Mono<T>` and deprecates them, as the only useful methods on `Mono<T>` are `awaitSingle` and `awaitSingleOrNull`
* Rewords some documentation for `await*` methods
Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/2591
Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/1587

Deprecate awaitSingleOr*, specialize some await* functions for Mono and Maybe

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/channels/Channel.kt
kotlinx-coroutines-core/common/test/channels/BasicOperationsTest.kt

* Establish clear contract on ChannelResult.isClosed
* This method provides a **clear** migration from correct 'offer' usages to 'trySend'

Add ChannelResult.onClosed

---

kotlinx-coroutines-core/common/test/flow/internal/FlowScopeTest.kt
kotlinx-coroutines-core/js/src/Exceptions.kt
kotlinx-coroutines-core/native/src/Exceptions.kt

* On JVM it uses java.util.concurrent.CancellationException, same as stdlib declaration
* Fully backward compatible for JVM, Native-friendly for Obj-C interop

Use cancellation exception from standard library in Kotlin/JS and K/N

---

reactive/kotlinx-coroutines-jdk9/src/Publish.kt
reactive/kotlinx-coroutines-jdk9/src/ReactiveFlow.kt
reactive/kotlinx-coroutines-jdk9/test/PublisherCollectTest.kt
reactive/kotlinx-coroutines-reactive/src/Channel.kt
reactive/kotlinx-coroutines-reactive/src/Publish.kt
reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt
reactive/kotlinx-coroutines-reactive/test/PublisherCollectTest.kt
reactive/kotlinx-coroutines-rx2/src/RxChannel.kt
reactive/kotlinx-coroutines-rx2/test/MaybeTest.kt
reactive/kotlinx-coroutines-rx2/test/ObservableCollectTest.kt
reactive/kotlinx-coroutines-rx3/src/RxChannel.kt
reactive/kotlinx-coroutines-rx3/test/MaybeTest.kt
reactive/kotlinx-coroutines-rx3/test/ObservableCollectTest.kt

Improves documentation, adds a couple of new tests.

Fixes for the reactive integrations

---

kotlinx-coroutines-core/jvm/src/AbstractTimeSource.kt
kotlinx-coroutines-core/jvm/test/VirtualTimeSource.kt

* It is the second TimeSource in our codebase
* Also make it abstract to let CHA kick in
Fixes #2691

Rename TimeSource to AbstractTimeSource due to KT-42625

---

kotlinx-coroutines-core/common/src/flow/Channels.kt
kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt
kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt
kotlinx-coroutines-core/common/test/flow/operators/OnCompletionTest.kt

It is helpful to prevent bugs like KT-46013 and potential deadlocks or delayed cancellations

Fail-fast in emitAll implementation from onCompletion

---

kotlinx-coroutines-core/common/src/Builders.common.kt
kotlinx-coroutines-core/common/src/CoroutineScope.kt
kotlinx-coroutines-core/common/src/Supervisor.kt
kotlinx-coroutines-core/common/src/Timeout.kt
kotlinx-coroutines-core/common/src/flow/internal/FlowCoroutine.kt
kotlinx-coroutines-core/common/src/internal/Scopes.kt
kotlinx-coroutines-core/js/src/CoroutineContext.kt
kotlinx-coroutines-core/jvm/src/CoroutineContext.kt
kotlinx-coroutines-core/native/src/CoroutineContext.kt
kotlinx-coroutines-core/native/test/WithTimeoutNativeTest.kt

Resolves #2688.
`TimeoutCoroutine` subclasses `ScopeCoroutine` and adds a backing field `time`.
Since `ScopeCoroutine` may potentially freeze itself during its init block (by adding itself to a frozen job as a child), the init steps of `TimeoutCoroutine` as a subclass may consequentially fail, due to the object now potentially failing `MutationCheck()`.
* Introduced a `useInitNativeKludge` constructor parameter in `ScopeCoroutine` to control whether the init kludge for native is enabled.
* Fixed #2688 by changing `TimeoutCoroutine` to disable the superclass' kludge, in favour of having the kludge as its own init block.
* Added a failing test case.
* The test case suffers from issue (2) in #2688 though, that the test runner should have been reporting the `InvalidMutabilityException`. But …

[native-mt, 1.5.0-RC] Fix withTimeout throwing InvalidMutabilityException.

---

kotlinx-coroutines-core/common/src/flow/operators/Share.kt
kotlinx-coroutines-core/jvm/test/flow/SharingReferenceTest.kt

Flows returned by stateIn/shareIn keep strong reference to sharing job

---

kotlinx-coroutines-core/jvm/test/flow/SharingReferenceTest.kt

Previously assert has been racing with the coroutine state spilling, triggering spurious wakeups

Fix flaky SharingReferenceTest

---

kotlinx-coroutines-core/jvm/src/Executors.kt
kotlinx-coroutines-core/jvm/src/ThreadPoolDispatcher.kt
kotlinx-coroutines-core/jvm/test/ExecutorAsCoroutineDispatcherDelayTest.kt
kotlinx-coroutines-core/jvm/test/knit/ClosedAfterGuideTestExecutor.kt
kotlinx-coroutines-core/jvm/test/knit/TestUtil.kt

* Document it properly
* Make it more robust to signature changes and/or delegation (e.g. see the implementation of java.util.concurrent.Executors.newScheduledThreadPool)
* Give a public way to reduce the memory pressure via ScheduledFuture.cancel

Document and tweak the contract of Executor.asCoroutineDispatcher and ExecutorService.asCoroutineDispatcher

---

kotlinx-coroutines-core/common/src/intrinsics/Cancellable.kt
kotlinx-coroutines-core/jvm/test/FailFastOnStartTest.kt
kotlinx-coroutines-core/jvm/test/FailingCoroutinesMachineryTest.kt

That helps to pro-actively catch cases like #2717 and to report such exception in even more robust manner

Fail eagerly during exceptions in isDispatchNeeded

---

build.gradle

Ensure "org.jetbrains.kotlinx:kotlinx-coroutines-core" transitive
dependencies are substituted with project itself to avoid test errors.

Improve ':kotlinx-coroutines-core' substitution for all modules.

---

kotlinx-coroutines-core/common/src/NonCancellable.kt

* ICA is misused here as lint, for which we consistently use @Deprecated in other places
* The current state is incompatible with 1.5.30 where KT-45844 is implemented

Replace InternalCoroutinesApi with deprecation in NonCancellable

---

kotlinx-coroutines-core/jvm/src/Dispatchers.kt

This implementation note mentions that withContext(IO) does not lead to a
context switch, which may be misunderstood as a general statement, while
it in fact only applies to switches between Default and IO dispatchers.
This is one example of misunderstanding:
https://stackoverflow.com/questions/68069529/is-kotlinx-coroutines-withcontext-safe-to-use-with-spring-webflux

Clarify Dispatchers.IO's implementation note

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt

* CoroutineDispatcher is internal for implementation and always has been
* Overriding this method may lead to memory leaks in parent coroutines and is considered dangerous

Make releaseInterceptedContinuation final

---

docs/kc.tree
docs/project.ihp

- remove `async-programming.md` (stored in kotlin-web-site) from coroutines Table of Contents
- specify unique WebHelp module name to allow building help together with kotlin-web-site.

docs: fix ToC and add module name

---

kotlinx-coroutines-core/common/src/CancellableContinuation.kt
kotlinx-coroutines-core/common/src/sync/Mutex.kt

* Get rid of addLastIf and DCSS primitive during contention
* Leverage constants returned by tryResume* and simplify signatures

Optimize mutex implementation

---

docs/kc.tree

Add `chunk` tag in the documentation ToC to allow including coroutines docs into Kotlin docs as a whole.

chore: wrap docs tree in chunk to include in Kotlin docs

---

README.md

raw exclude call is now deprecated and gives the following warning,
```
This property is deprecated. Use resources.excludes or jniLibs.excludes instead. Use
jniLibs.excludes for .so file patterns, and use resources.excludes for all
other file patterns.
```
Tested and works as expected here https://github.com/persian-calendar/DroidPersianCalendar/commit/b4c21e0d1eb4ea8f0a93e56de2f56793fa442608

Update DebugProbesKt.bin exclusion instruction

---

kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt
kotlinx-coroutines-debug/test/BlockHoundTest.kt

Fix BlockHound false-positive in ConflatedChannel

---

kotlinx-coroutines-core/common/src/CoroutineScope.kt

Update CoroutineScope() factory documentation

---

kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
kotlinx-coroutines-core/common/src/flow/StateFlow.kt
kotlinx-coroutines-core/common/src/flow/internal/AbstractSharedFlow.kt
kotlinx-coroutines-core/common/src/flow/operators/Share.kt
kotlinx-coroutines-core/common/test/flow/sharing/ShareInConflationTest.kt
kotlinx-coroutines-core/common/test/flow/sharing/ShareInTest.kt
kotlinx-coroutines-core/common/test/flow/sharing/SharedFlowTest.kt
kotlinx-coroutines-core/common/test/flow/sharing/SharingStartedWhileSubscribedTest.kt
kotlinx-coroutines-core/jvm/test/flow/SharingStressTest.kt

Sharing strategies are too sensitive to conflation around extrema and may miss the necessity to start or not to stop the sharing. For more particular examples see #2863 and #2488
Fixes #2488
Fixes #2863
Fixes #2871

Non-conflating subscription count in SharedFlow and StateFlow

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/Job.kt

It was internal and was not part of the ABI as it was internal.
So no existing code should break (well, except for those who called internal API via reflection) and source compatibility is preserved

Make DisposableHandle fun interface, remove our own adapter

---

docs/topics/exception-handling.md

The reason to remove 'later' is that section "Channels" comes before section "Coroutine Exceptions Handling" not after it.

Fix the doc of 'Coroutine Exceptions Handling'

---

kotlinx-coroutines-core/common/src/Annotations.kt
kotlinx-coroutines-core/common/src/CloseableCoroutineDispatcher.kt
kotlinx-coroutines-core/js/src/CloseableCoroutineDispatcher.kt
kotlinx-coroutines-core/jvm/src/Executors.kt
kotlinx-coroutines-core/native/src/CloseableCoroutineDispatcher.kt

* Alias it to ExecutorCoroutineDispatcher on JVM as the most appropriate candidate
* Add abstract classes to JVM and Native
* This class will be implemented by new dispathers for K/N new memory model

Introduce CloseableCoroutineDispatcher abstract class

---

docs/topics/cancellation-and-timeouts.md

This probably used to be the next chapter, but not any more.

Fix chapter pointer: it's the second next chapter

---

integration/kotlinx-coroutines-guava/src/ListenableFuture.kt
integration/kotlinx-coroutines-guava/test/ListenableFutureTest.kt

Fixes #2774 and #2791.
This change makes `future` coroutine builder consistent with `java.util.concurrent.FutureTask` which also drops exceptions that happen after successful cancellation.
Note: `future` will still pass the error to its parent in the tree if there's one. But if there's no parent, the exception is dropped.

Breaking change: Guava future coroutine builder shouldn't report to CoroutineExceptionHandler

---

kotlinx-coroutines-test/common/src/TestBuilders.kt
kotlinx-coroutines-test/common/src/TestCoroutineScope.kt
kotlinx-coroutines-test/common/src/TestDispatchers.kt
kotlinx-coroutines-test/common/src/internal/TestMainDispatcher.kt
kotlinx-coroutines-test/common/test/TestCoroutineScopeTest.kt

This change eliminates the common pattern that is currently needed to be able to use `Dispatchers.Main` in code under test:
```kotlin
val dispatcher = TestCoroutineDispatcher()
val scope = TestCoroutineScope(dispatcher)
@BeforeTest
fun setMain() {
Dispatchers.setMain(dispatcher)
}
@AfterTest
fun resetMain() {
Dispatcher.resetMain()
scope.cleanupTestCoroutines()
}
@Test
fun testFoo() = scope.runBlockingTest { ... }
```
Now this becomes just
```kotlin
@BeforeTest
fun setMain() {
Dispatchers.setMain(TestCoroutineDispatcher())
}
@AfterTest
fun resetMain() {
Dispatcher.resetMain()
}
@Test
fun testFoo() = runTest { ... }
```
This is done by querying `Dispatchers.Main` for its `TestCoroutineScheduler`.

Use the TestCoroutineDispatcher from Dispatchers.Main by default

---

kotlinx-coroutines-core/common/src/CoroutineContext.common.kt
kotlinx-coroutines-test/common/src/TestBuilders.kt
kotlinx-coroutines-test/common/src/TestCoroutineDispatchers.kt
kotlinx-coroutines-test/common/src/TestCoroutineScope.kt
kotlinx-coroutines-test/common/src/internal/TestMainDispatcher.kt
kotlinx-coroutines-test/common/test/Helpers.kt
kotlinx-coroutines-test/common/test/RunTestTest.kt
kotlinx-coroutines-test/common/test/StandardTestDispatcherTest.kt
kotlinx-coroutines-test/common/test/TestDispatchersTest.kt
kotlinx-coroutines-test/common/test/UnconfinedTestDispatcherTest.kt
kotlinx-coroutines-test/js/test/FailingTests.kt
kotlinx-coroutines-test/js/test/Helpers.kt
kotlinx-coroutines-test/native/test/FailingTests.kt
kotlinx-coroutines-test/native/test/Helpers.kt

@qwwdfsad found a convenient migration path for most tests that rely on `launch` and `async` blocks being entered eagerly. Implemented it here.
Also, I fixed `Dispatchers.Main` not delegating `Delay` methods and discovered that, on JS, `Dispatchers.Main` gets reset during the test if it is reset in `AfterTest`.

Eagerly enter `launch` and `async` blocks with unconfined dispatcher.

---

kotlinx-coroutines-core/build.gradle
kotlinx-coroutines-core/jvm/src/internal/ExceptionsConstructor.kt
ui/kotlinx-coroutines-android/test/R8ServiceLoaderOptimizationTest.kt

When it's available.
The change has two purposes:
* Provide `ClassLoader` leak-free implementation of `ExceptionsConstructor`
* Introduce a potentially erroneous pattern in the codebase to see how good we can workaround missing Java API on Android

Introduce ClassValue-based exception constructor cache to stracktrace recovery

---

kotlinx-coroutines-core/common/src/Delay.kt
kotlinx-coroutines-core/jvm/src/DefaultExecutor.kt
ui/kotlinx-coroutines-javafx/src/JavaFxDispatcher.kt

It reduces the number of redundant threads in the system and makes time source predictable across Android/JavaFx applications
Fixes #2972

Use Dispatchers.Main as default delay source where applicable

---

kotlinx-coroutines-test/common/test/RunTestTest.kt

Simple duplicated KDoc issue I noticed while browsing the tests: The `testRunTestWithLargeTimeout` used the KDoc from `testRunTestWithSmallTimeout`, which didn't make sense.
Feel free to reword the new KDoc however you'd like.

Fix RunTestTest.testRunTestWithLargeTimeout KDoc

---

kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt

Now the test module correctly exposes that initially, the Main dispatcher is missing, so the default delay mechanism is not rewritten.
This is option №1.

Fix crashes with the test module on the JVM: take #1

---

kotlinx-coroutines-core/common/src/internal/StackTraceRecovery.common.kt
kotlinx-coroutines-test/common/src/TestBuilders.kt
kotlinx-coroutines-test/common/src/TestScope.kt
kotlinx-coroutines-test/common/test/RunTestTest.kt
kotlinx-coroutines-test/jvm/src/migration/TestBuildersDeprecated.kt
kotlinx-coroutines-test/jvm/test/migration/RunTestLegacyScopeTest.kt

Make UncompletedTestCoroutines more verbose

---

kotlinx-coroutines-test/common/src/TestScope.kt
kotlinx-coroutines-test/jvm/src/migration/DelayController.kt
kotlinx-coroutines-test/jvm/src/migration/TestBuildersDeprecated.kt
kotlinx-coroutines-test/jvm/src/migration/TestCoroutineScope.kt

Improve docs for the test module

---

gradle.properties

To make work [KT-49738](https://youtrack.jetbrains.com/issue/KT-49738) with async `@AfterTest`, necessary to upgrade Node.JS version, because `Promise.finally` exists since 10.0.0

Update Node version to 10.0.0 because Promise.finally since this version

---

integration/kotlinx-coroutines-jdk8/src/stream/Stream.kt
kotlinx-coroutines-core/common/src/flow/Flow.kt
kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
kotlinx-coroutines-core/common/src/flow/operators/Distinct.kt

Get rid of @InternalCoroutinesApi from Flow.collect member

---

kotlinx-coroutines-core/jvm/resources/META-INF/com.android.tools/proguard/coroutines.pro
kotlinx-coroutines-core/jvm/resources/META-INF/com.android.tools/r8/coroutines.pro
kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro

Fixes #3058
Tried to get creative here but to no avail. Looks like just adding the new rules is the way to go.
I had my doubts about `dontwarn` for `IgnoreJRERequirements`, but, searching the net, it looks like this rule is common practice, and given that only methods and internal and private classes are marked with it, everything should be fine.

Fix R8 warnings

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt

Restore half a sentence from an earlier commit https://github.com/Kotlin/kotlinx.coroutines/pull/2918/commits/ecd36dd3802ba6b3a9115fd724b4dfe760ea058d (+ some wording adjustment)

Fix a broken sentence in CoroutineDispatcher.kt

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt

See https://github.com/rsocket/rsocket-kotlin/issues/201
Seems like it can be quite a disrupting change otherwise

Restore MPP backwards compatibility on K/JS and K/N

---

kotlinx-coroutines-core/common/src/internal/MainDispatcherFactory.kt
ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt
ui/kotlinx-coroutines-swing/src/SwingDispatcher.kt

* If `unitTests.returnDefaultValues=true` is set on Android, then
`Looper.getMainLooper()` may return `null`. The type system of
Kotlin is tricked to believe that the method can't ever return
`null`, so doesn't check for it anywhere. As a result, despite not
being fully initialized, `Dispatchers.Main` is considered
non-missing.
* When running in a headless environment, Swing crashes, but
the dispatcher successfully initializes nonetheless.
This was not an issue before, as it only surfaced when
`Dispatchers.Main` was used. However, now `Main` is the source of
time for delays, so any delay will throw something
incomprehensible if this happens.

Fix Dispatchers.Main not being fully initialized on Android and Swing

---

kotlinx-coroutines-core/common/src/CoroutineScope.kt

Fixed a typo in the documentation of `GlobalScope`. Changed `coroutinesScope` to `coroutineScope`

Fixed a typo in `GlobalScope` documentation

---

integration/kotlinx-coroutines-slf4j/build.gradle.kts
integration/kotlinx-coroutines-slf4j/src/MDCContext.kt

The SLF4J integration module now also no longer uses the deprecated Gradle dependency declaration keywords

Updated SLF4J Dependencies In SLF4J Integration Module To 1.7.32

---

README.md

Fixes #3095.
Use common syntax where possible.

Unify Groovy and Kotlin DSL code snippets

---

kotlinx-coroutines-core/native/src/internal/Concurrent.kt

This change fixes an issue with initialization order observed when
lazy initialization is disabled (-Xir-property-lazy-initialization=
disabled compiler flag) and the new MM is used.
The problem is the following: the initialization of DefaultDelay
happens before initialization of multithreadingSupported. Thus
the initialization of DefaultDelay gets an uninitialized value
of multithreadingSupported and behaves as if the old MM is used.
Related issue: #KT-50491.

Make multithreadingSupported a property with a getter

---

kotlinx-coroutines-core/jvm/src/DefaultExecutor.kt
ui/kotlinx-coroutines-android/test/HandlerDispatcherTest.kt

The approach from 1.6.0 has proven itself as unstable and multiple hard-to-understand bugs have been reported:
* JavaFx timer doesn't really work outside the main thread
* The frequent initialization pattern "runBlocking { doSomethingThatMayCallDelay() }" used on the main thread during startup now silently deadlocks
* The latter issue was reported both by Android and internal JB Compose users
* The provided workaround with system property completely switches off the desired behaviour that e.g. Compose may rely on, potentially introducing new sources of invalid behaviour
The original benefits does not outweigh these pitfalls, so the decision is to revert this changes in the minor release
Fixes #3113
Fixes #3106

Rollback #2972, but leave a compatibility option with 1.6.0

---

kotlinx-coroutines-core/jvm/src/internal/ResizableAtomicArray.kt
kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt
kotlinx-coroutines-core/jvm/test/lincheck/ResizableAtomicArrayLincheckTest.kt

Instead of allocating an array of maxPoolSize (~2M) elements for the worst-case supported scenario that may never be reached in practice and takes considerable memory, allocate just an array of corePoolSize elements and grow it dynamically if needed to accommodate more workers.
The data-structure to make it happen must support lock-free reads for performance reasons, but it is simple, since workers array is modified exclusively under synchronization.

Optimization: resizable workers array

---

integration/kotlinx-coroutines-guava/README.md
integration/kotlinx-coroutines-guava/build.gradle.kts
integration/kotlinx-coroutines-guava/src/ListenableFuture.kt

Guava's current nullness annotations don't yet trigger Kotlin compile
errors. However, Guava did recently remove the misleading `@Nullable`
annotation from the parameter of `FutureCallback.onSuccess`:
Before:
https://github.com/google/guava/blob/v28.0/guava/src/com/google/common/util/concurrent/FutureCallback.java#L34
After:
https://github.com/google/guava/blob/v31.0.1/guava/src/com/google/common/util/concurrent/FutureCallback.java#L35
That means that a `FutureCallback<T>` can now implement `onSuccess(T)`
instead of `onSuccess(T?)`. And with a future change to Guava, it will
_have to_.
(For background, see the section on "Nullness annotations" in
https://github.com/google/guava/releases/tag/v31.0)
In order to make that change, this commit updates from from Guava 28.0
to Guava 31.0.1.
When …

Update code to prepare for nullness annotations in Guava.

---

kotlinx-coroutines-test/MIGRATION.md

Addresses #3143
Addresses #3120

Update the migration guide to highlight how to test all emissions

---

kotlinx-coroutines-core/common/src/flow/operators/Context.kt

Addressing a small typo I found in Flow's conflate source file

docs: typo in Conflate documentation

---

kotlinx-coroutines-core/jvm/src/ThreadContextElement.kt

The example code in the comment of `CopyableThreadContextElement` contained references to non-existing (property, parameter, class) names. This PR fixes those, simplifies the `Key` initialization and adds a `copy()` invocation in `copyForChildCoroutine()` for a more realistic use case.

Fix example code in comment of CopyableThreadContextElement

---

kotlinx-coroutines-core/common/src/Await.kt

It seems like there is an extra "when" and a missing "for".

Modify the KDoc for awaitAll

---

kotlinx-coroutines-core/common/src/flow/SharedFlow.kt

The details on how buffering conceptually works and what happens without subscribers are buried deep inside the SharedFlow docs. This clarification puts the important information right into the doc of emit and tryEmit methods.

docs: Clarify MutableSharedFlow.emit/tryEmit on subscribers and overflow

---

kotlinx-coroutines-core/jvm/test/exceptions/StackTraceRecoveryCustomExceptionsTest.kt

Validate that throwing tryCopy does not crash with an internal error

---

kotlinx-coroutines-test/common/src/TestDispatcher.kt

Currently, linking to [TestDispatcher](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-dispatcher/index.html) directly leads the user to a page where they can't find the available implementations of this interface. This is mostly caused by the implementations being private classes with factory functions instead of inheritors.
This PR adds references to the two implementations. The description of the implementations here is not very important, feel free to modify it if needed.

Add references to available implementations in TestDispatcher docs

---

docs/topics/coroutines-basics.md

Updates the section "Coroutines are light-weight" to clarify its
comparison of the resource-intensiveness of coroutines and threads. The
content is much the same, I've attempted to make it follow the pattern
of the other sections by introducing the conceptual point first, then
presenting the code sample.
This commit also makes the code sample in this section runnable and
omits the surrounding runBlocking block.

docs: clarify section on coroutine memory consumption

---

kotlinx-coroutines-core/jvm/src/Dispatchers.kt

Dispatchers.IO doc clarification

---

kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt

There are two "pollInternal". :)

Remove duplicate allowed method in BlockHound integration

---

.gitignore
benchmarks/build.gradle.kts
build.gradle
buildSrc/src/main/kotlin/Publishing.kt
buildSrc/src/main/kotlin/animalsniffer-conventions.gradle.kts
gradle.properties
gradle/compile-js-multiplatform.gradle
gradle/dokka.gradle.kts
gradle/node-js.gradle
gradle/publish.gradle
gradle/test-mocha-js.gradle
gradle/wrapper/gradle-wrapper.properties
integration-testing/build.gradle
integration/kotlinx-coroutines-guava/build.gradle.kts
kotlinx-coroutines-core/build.gradle
kotlinx-coroutines-debug/build.gradle
reactive/kotlinx-coroutines-reactive/build.gradle.kts
reactive/kotlinx-coroutines-reactor/build.gradle.kts
settings.gradle
ui/kotlinx-coroutines-swing/build.gradle.kts

Upgrading to Gradle 7.4.2 also includes updating or removing plugins that were outdated or incompatible with Gradle 7.x
Kotlin 1.6.21 update is not required but bumping anyway since tests pass.
One difference that I noticed is that dokka now generates absolute paths for links, and not `../../`, if this is a problem it's something that should be looked into. 
`./gradlew build` passes, and I also verified (more or less) that all files are generated in the right paths in the maven publication.

Gradle 7.4.2, Kotlin 1.6.21 and other plugin updates

---

docs/topics/coroutine-context-and-dispatchers.md
kotlinx-coroutines-core/jvm/test/guide/example-context-06.kt
kotlinx-coroutines-core/jvm/test/guide/test/DispatcherGuideTest.kt

Update guide example to better reflect the intent

---

docs/topics/cancellation-and-timeouts.md
kotlinx-coroutines-core/jvm/test/guide/example-cancel-03.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-04.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-05.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-06.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-07.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-08.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-10.kt
kotlinx-coroutines-core/jvm/test/guide/test/CancellationGuideTest.kt

No idea how to make the diff more structured/less ugly.

Mention swallowing CancellationExceptions in the docs

---

kotlinx-coroutines-core/common/src/CoroutineScope.kt

Clarify the difference between `MainScope()` and `CoroutineScope()`, remove mention of `CustomScope`

Update docs about creating custom CoroutineScopes

---

kotlinx-coroutines-core/common/src/Builders.common.kt

Update withContext KDoc

---

kotlinx-coroutines-core/jvm/test/exceptions/WithContextCancellationStressTest.kt

Not sure what the test checks for. Does it really need to make all these iterations, or just waiting for every type of exception to fire is enough?

Fix a flaky test

---

kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt

Reduce reachable references of disposed invokeOnTimeout handle

---

reactive/kotlinx-coroutines-reactive/src/Await.kt
reactive/kotlinx-coroutines-reactive/test/AwaitCancellationStressTest.kt
reactive/kotlinx-coroutines-reactive/test/AwaitTest.kt

Rule [2.7](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#2-subscriber-code) requires Subscription methods to be executed serially.
There is a possibility of race between Subscription.request and Subscription.cancel methods since cancellation handler could be executed in a separate thread.
In particular this bug leads to database connection leaks if used with [jooq subscription](https://github.com/jOOQ/jOOQ/blob/9423e7b6a2e25e136217e431b1780b737e6078fd/jOOQ/src/main/java/org/jooq/impl/R2DBC.java#L138) as cancel can happen while request being initialized and hence it misses to close connection.

Await comply with reactive streams Subscriber rule 2.7

---

gradle/publish.gradle
integration-testing/build.gradle
integration-testing/src/debugDynamicAgentTest/kotlin/DynamicAttachDebugTest.kt
kotlinx-coroutines-debug/build.gradle

It seems like Maven's BOM has never worked with shadow plugin in our previous releases: added `api` dependency was just too late.
It has been changed in the latest shadow plugin release and it automatically promoted all `api` dependencies to `runtime` (https://github.com/johnrengelman/shadow/issues/321), triggering #3345. Gradle builds were never affected though because they were primarily parsing Gradle metadata.
<details>
<summary>Resulting debug module POM</summary>
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion> …
```

Fix debug module publication with shadow plugin

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/internal/StackTraceRecovery.common.kt
kotlinx-coroutines-core/common/src/internal/ThreadSafeHeap.kt
kotlinx-coroutines-test/api/kotlinx-coroutines-test.api
kotlinx-coroutines-test/common/src/TestBuilders.kt
kotlinx-coroutines-test/common/src/TestCoroutineDispatchers.kt
kotlinx-coroutines-test/common/src/TestCoroutineScheduler.kt
kotlinx-coroutines-test/common/src/TestDispatcher.kt
kotlinx-coroutines-test/common/src/TestScope.kt
kotlinx-coroutines-test/common/src/internal/ReportingSupervisorJob.kt
kotlinx-coroutines-test/common/test/RunTestTest.kt
kotlinx-coroutines-test/common/test/TestScopeTest.kt
kotlinx-coroutines-test/js/src/TestBuilders.kt
kotlinx-coroutines-test/jvm/src/TestBuildersJvm.kt
kotlinx-coroutines-test/jvm/src/migration/TestBuildersDeprecated.kt
kotlinx-coroutines-test/jvm/src/migration/TestCoroutineDispatcher.kt
kotlinx-coroutines-test/jvm/test/migration/RunBlockingTestOnTestScopeTest.kt
kotlinx-coroutines-test/native/src/TestBuilders.kt

Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/3287

Add a scope for launching background work in tests

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt

Improve CoroutineDispatcher documentation

---

integration-testing/src/withGuavaTest/kotlin/ListAllCoroutineThrowableSubclassesTest.kt
kotlinx-coroutines-core/jvm/src/CoroutineExceptionHandlerImpl.kt

Mark context in DiagnosticCoroutineContextException as transient

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/Job.kt
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/NonCancellable.kt
kotlinx-coroutines-core/common/src/internal/Scopes.kt
kotlinx-coroutines-core/common/test/JobStatesTest.kt
kotlinx-coroutines-core/common/test/JobTest.kt

* The API is crucial for debugger extension and deadlock detection
* It enables allows more fluent coroutines hierarchy inspection, e.g. capability to build a list of roots and procrss them top-bottom separately
Fixes #3201

Introduce Job.parent API

---

kotlinx-coroutines-core/jvm/src/Debug.kt

Based against `master` as this PR only fixes documentation and doesn't change line numbers.

Fix documentation for `DEBUG_PROPERTY_VALUE_OFF`

---

docs/topics/select-expression.md
kotlinx-coroutines-core/jvm/test/guide/example-select-01.kt
kotlinx-coroutines-core/jvm/test/guide/test/SelectGuideTest.kt

Update select-guide timings to be precise

---

RELEASE.md
bump-version.sh

* It doesn't require specifying the old version.
Instead, the version will be taken from gradle.properties.
* It reverts the changes if there is an error in the process.
* It will output a command to undo the changes manually.

Improve bump-version.sh

---

build.gradle
dokka-templates/README.md
gradle/dokka.gradle.kts

We want to customize the header and the footer in coroutines API reference on kotlinlang.org to provide a better user experience and consistency between all parts of kotlinlang.org. 
Starting from the 1.6.20 version, Dokka supports customization of HTML output. You can read about it [here](https://kotlin.github.io/dokka/1.6.20/user_guide/base-specific/frontend/#custom-html-pages).
To use this opportunity, we need a small preparation on your side.
These changes allow HTML customization. 
The rest we will do on our side.

Provide a way for customization Dokka's HTML output

---

docs/topics/debug-coroutines-with-idea.md
docs/topics/debug-flow-with-idea.md

update: adding kotlinx.dependencies

---

kotlinx-coroutines-test/common/src/TestDispatcher.kt
kotlinx-coroutines-test/jvm/test/MemoryLeakTest.kt

Fix cancelled delayed jobs not being disposed of in TestDispatcher

---

kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt

Fix another potential memory leak in WorkerDispatcher

---

kotlinx-coroutines-core/common/src/CompletionState.kt
kotlinx-coroutines-core/common/src/Yield.kt
kotlinx-coroutines-core/common/src/channels/Channel.kt
kotlinx-coroutines-core/common/src/channels/ChannelCoroutine.kt
kotlinx-coroutines-core/common/src/channels/Channels.common.kt
kotlinx-coroutines-core/common/src/flow/Channels.kt
kotlinx-coroutines-core/common/src/flow/internal/AbstractSharedFlow.kt
kotlinx-coroutines-core/common/src/flow/internal/Combine.kt
kotlinx-coroutines-core/common/src/flow/terminal/Count.kt
kotlinx-coroutines-core/common/src/internal/Concurrent.common.kt
kotlinx-coroutines-core/common/src/internal/DispatchedContinuation.kt
kotlinx-coroutines-core/common/src/selects/SelectUnbiased.kt
kotlinx-coroutines-core/common/src/selects/WhileSelect.kt
kotlinx-coroutines-core/common/src/sync/Mutex.kt

The correctness of the change is verified by ConsumeAsFlowLeakTest

Get rid of workaround for KT-16222 that is long time fixed

---

kotlinx-coroutines-core/common/src/Dispatchers.common.kt

Update Dispatchers.Main documentation

---

build.gradle
reactive/kotlinx-coroutines-rx2/src/RxAwait.kt
reactive/kotlinx-coroutines-rx2/src/RxChannel.kt
reactive/kotlinx-coroutines-rx2/src/RxObservable.kt
reactive/kotlinx-coroutines-rx3/build.gradle
reactive/kotlinx-coroutines-rx3/src/RxAwait.kt
reactive/kotlinx-coroutines-rx3/src/RxChannel.kt
reactive/kotlinx-coroutines-rx3/src/RxConvert.kt
reactive/kotlinx-coroutines-rx3/src/RxMaybe.kt
reactive/kotlinx-coroutines-rx3/src/RxObservable.kt
reactive/kotlinx-coroutines-rx3/src/RxScheduler.kt

* For RxJava2, use them in internal implementations where appropriate
* For RxJava3, introduce & Any bound to generic argument in our extensions to avoid errors in Kotlin 1.8.0 due to non-nullability rx3 annotations being part of generics upper bound. This change went through commitee, and all the "unsound" declarations such as "RxSignature<Foo?>" were properly highlighted as warning that will become an error.

Introduce non-nullable types in reactive integrations where appropriate

---

kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt

In CoroutineScheduler's KDoc, missing `(` was added. Considering the keyboard distance between `)` and `.`, `)` was judged as missing a `(` in front of the sentence instead of a typo of `.`.

Insert missing "(" in CoroutineScheduler's KDoc

---

kotlinx-coroutines-core/common/src/Builders.common.kt
kotlinx-coroutines-core/jvm/test/ThreadContextElementTest.kt

Properly use UndispatchedCoroutine context for context-specific elements

---

kotlinx-coroutines-core/common/src/internal/SystemProps.common.kt
kotlinx-coroutines-core/jvm/src/scheduling/Tasks.kt

Allow customization of default scheduler name on JVM

---

gradle/test-mocha-js.gradle

Because of changes in API of compile task

Use outputFileProperty instead of outputFile

---

integration/kotlinx-coroutines-jdk8/src/future/Future.kt

Which leads a better performance.
https://github.com/line/armeria/pull/1440
https://github.com/akka/akka/pull/31283

Make use of `CompletionStage#handle` instead of `whenComplete`.

---

build.gradle

The new way of atomicfu compiler plugin applicaition takes 3 steps: 
- first the compiler plugin `AtomicfuKotlinGradleSubplugin` is [applied](https://github.com/Kotlin/kotlinx-atomicfu/blob/70dd7aaa2c51d5ca2556e981581830c5696fcbd3/atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt#L119). It adds an extension `AtomicfuKotlinGradleExtension` with properties for turning on jvm and js transformation.
- Then these extension properties are [set](https://github.com/Kotlin/kotlinx-atomicfu/blob/70dd7aaa2c51d5ca2556e981581830c5696fcbd3/atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt#L121) in the AtomicfuGradlePlugin.
- When `AtomicfuKotlinGradleSubplugin$isApplicable` is invoked, the values of the extension …

Fix atomicfu plugin application

---

kotlinx-coroutines-test/common/test/RunTestTest.kt
kotlinx-coroutines-test/jvm/test/migration/RunTestLegacyScopeTest.kt

These tests haven't been reliable for a very long time for some reason. We could ensure that they pass with a manual check, but it feels like nobody actually relies on this behavior, and it's not clear who even would want to.
https://github.com/search?p=3&q=%22dispatchTimeoutMs+%3D+0%22&type=Code https://grep.app/search?q=dispatchTimeoutMs%20%3D%200

Remove some broken tests

---

gradle.properties

Update atomicfu to 0.18.5

---

kotlinx-coroutines-debug/test/CoroutinesDumpTest.kt
kotlinx-coroutines-debug/test/RunningThreadStackMergeTest.kt
kotlinx-coroutines-debug/test/StacktraceUtils.kt

`CoroutinesDumpTest` tests used `verifyDump` incorrectly because of all coroutine traces contains `BlockingCoroutine` substring. So these tests actually did not check any coroutine stack traces.
To reduce probability of incorrect usage of `verifyDump` added code that parses coroutine stack traces.

Fix coroutines dump tests

---

reactive/kotlinx-coroutines-jdk9/build.gradle.kts

By default Java targetCompatibility is equal to current Gradle JDK version which could be different from specified in this module Kotlin 'jvmTarget' and depend on current user JDK version.
Also Java targetCompatability controls Gradle "org.gradle.jvm.version" publication attribute, which is wrongly set to '8' in '1.6.4' release module file. Setting it explicetly fixes publication issue.
This change fixes compatibility with Kotlin 1.8.0 release changes from
this issue: https://youtrack.jetbrains.com/issue/KT-54993

Kotlin 1.8.0: Fix java targetCompatibility was unset in :kotlinx-coroutines-jdk9

---

docs/topics/coroutines-and-channels.md

Updated the "Coroutines and channels" tutorial according to the API changes in 1.6:
- `runBlockingTest` replaced with `runTest`
- `TestCoroutineScope` -> `TestScope`
- `TestCoroutineDispatcher` -> `TestDispatcher`
Related PR in the hands-on lab repo: https://github.com/kotlin-hands-on/intro-coroutines/pull/32

Coroutines and channels tutorial: updated API deprecations for version 1.6

---

kotlinx-coroutines-core/common/src/EventLoop.common.kt

Make EventLoopImplBase properly synchronized on Kotlin/Native

---

build.gradle
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/CommunityProjectsBuild.kt

//KTI-1051
Support passing an url for a kotlin compiler repository, drop space kotlin/dev repo from dependencies: Kotlin compiler artifacts should be downloaded from maven central by default. In case of compiling with not-published into the MC kotlin compiler artifacts, a kotlin_repo_url should be specified as a gradle parameter(E.g. space kotlin/dev repo).

Prepare coroutines for including to the community projects composite build

---

docs/topics/cancellation-and-timeouts.md

Improve the section on resource leaks in the docs

---

kotlinx-coroutines-core/jvm/src/scheduling/Dispatcher.kt

Before the change `LimitedDispatcher(parallelism)` was returned. While it does work as expected, any submitted task 
goes through its queue and `parallelism` number of workers. The change allows to eliminate the `LimitedDispatcher` 
instance and its queue in case the requested parallelism is greater or equal to the effective parallelism of `Dispatchers.Default` and/or `Dispatchers.IO`

Eliminate unneeded `LimitedDispatcher` instances on `Dispatchers.Default` and `Dispatchers.IO`

---

kotlinx-coroutines-core/concurrent/src/channels/Channels.kt

There was a small typo on the channels documentation

Fix typo on Channels documentation

---

docs/topics/coroutines-and-channels.md

This change makes sure the sentence reflects the actual meaning: We're switching to the type of API that uses callbacks, rather than switching to the API, which incidentally happens to use callbacks.

Remove confusing comma in Coroutines Hands-on

---

kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt
kotlinx-coroutines-core/jvm/src/scheduling/WorkQueue.kt
kotlinx-coroutines-core/jvm/test/scheduling/CoroutineSchedulerOversubscriptionTest.kt
kotlinx-coroutines-core/jvm/test/scheduling/WorkQueueStressTest.kt
kotlinx-coroutines-core/jvm/test/scheduling/WorkQueueTest.kt

It solves two problems:
* Stealing into exclusively owned local queue does no longer require and CAS'es or atomic operations where they were previously not needed. It should save a few cycles on the stealing code path
* The overall timing perturbations should be slightly better now: previously it was possible for the stolen task to be immediately got stolen again from the stealer thread because it was actually published to owner's queue, but its submission time was never updated
Fixes #3416

Introduce a separate slot for stealing tasks into in CoroutineScheduler

---

kotlinx-coroutines-core/jvm/src/scheduling/WorkQueue.kt

Otherwise, it is possible to leave dangling blockingTasksInBuffer increment that will never be decremented back, leading to unnecessary full-scans on any attempt to steal only blocking task. This change does not have a corresponding unit-test because it fixes the performance regression that is not observable semantically

Increment WorkQueue.blockingTasksInBuffer only after capacity check

---

kotlinx-coroutines-core/native/src/Builders.kt
kotlinx-coroutines-core/native/test/WorkerTest.kt

Fixes #3578
A competitor to https://github.com/Kotlin/kotlinx.coroutines/pull/3584

Prevent `runBlocking` failure when the Worker it runs on terminates

---

benchmarks/build.gradle.kts
benchmarks/src/jmh/kotlin/benchmarks/debug/DebugProbesConcurrentBenchmark.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugCoroutineInfoImpl.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt
kotlinx-coroutines-debug/src/DebugProbes.kt

* Get rid of RW lock that was contended enough on reads to be observable by non-concurrent coroutines-heavy code (up to 30% of throughput on IDEA-specific benchmark)
* Tweak the code to be DRF in the absence of RW lock
* Document snapshots' weak consistency guarantee 
Fixes #3527

Improve DebugProbes performance

---

kotlinx-coroutines-core/common/src/Dispatchers.common.kt

The previous example used `withContext` which is guaranteed to complete before the code after it runs. The updated example uses `launch` which I think was originally intended.
This fixes #3605 and [KT-47032](https://youtrack.jetbrains.com/issue/KT-47032/Incorrect-code-example-for-Dispatchers.Unconfined-in-kotlinx.coroutines-docs)

Update the code example for Dispatchers.Unconfined

---

kotlinx-coroutines-core/common/src/Dispatchers.common.kt
kotlinx-coroutines-core/jvm/src/Dispatchers.kt

We update the docs in Dispatchers.common.kt, but JVM's Dispatchers.kt also has its own version of it, which is accessible via the "JVM" tab of the docs:
<https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-unconfined.html> The docs there are outdated, so we should remove them.

Remove docs about Dispatchers.kt that replicate the common code

---

kotlinx-coroutines-core/jvm/src/debug/internal/DebugCoroutineInfoImpl.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt
kotlinx-coroutines-debug/test/DebugProbesTest.kt

For the following code:
```
suspend fun foo() = yield()
```
the following bytecode is produced:
```
fun foo(...) {
uCont.intercepted().dispatchUsingDispatcher() // 1
probeCoroutineSuspended() // 2
return COROUTINE_SUSPENDED // Unroll the stack
}
```
And it is possible to observe the next 'probeCoroutineSuspended' **prior** to receiving 'probeCoroutineSuspended'.
To address this, a dedicated 'unmatchedResumes' field is introduced to the coroutine state, which keeps track of consecutive 'probeCoroutineResumed' without matching 'probeCoroutineSuspended' and attributes lately arrived probes to it.
Unfortunately, it introduces a much more unlikely race when **two** 'probeCoroutineSuspended' are reordered, then we misattribute 'lastObservedFrame', but it is still better than misattributing the …

Fix suspend-resume race in DebugProbes

---

kotlinx-coroutines-core/common/src/channels/BufferedChannel.kt
kotlinx-coroutines-core/common/src/internal/ConcurrentLinkedList.kt
kotlinx-coroutines-core/common/src/sync/Semaphore.kt

* 'inline' modifier is removed from 'findSegmentInternal'. It previously lead to KT-55983: incorrect SMAP was produced that crashed the debugger consistently
* Non-inline functions are non-capturing, thus no additional performance overhead
* Method-reference is extracted to a variable in few places as it were crashing JVM compiler with AIOOB consistently

Workaround for debugger+compiler crash:

---

kotlinx-coroutines-core/common/src/Delay.kt
kotlinx-coroutines-core/common/src/Timeout.kt
kotlinx-coroutines-core/common/test/flow/operators/TimeoutTest.kt
kotlinx-coroutines-test/api/kotlinx-coroutines-test.api
kotlinx-coroutines-test/common/src/TestDispatcher.kt
kotlinx-coroutines-test/common/test/TestScopeTest.kt

Explain the test framework behavior in the withTimeout message

---

kotlinx-coroutines-core/common/src/channels/BufferedChannel.kt

This alone improves our default `ChannelSinkBenchmark` by 30%:  `3.121` -> `2.045`

Restore TCO in BufferedChannel

---

docs/topics/cancellation-and-timeouts.md
kotlinx-coroutines-core/jvm/test/guide/example-cancel-09.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-10.kt

See [KT-51515](https://youtrack.jetbrains.com/issue/KT-51515) for the details.

Documentation: fix OutOfMemoryError for the runnable samples 

---

README.md
kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/Dispatchers.common.kt
kotlinx-coroutines-core/concurrent/src/Dispatchers.kt
kotlinx-coroutines-core/concurrent/test/DefaultDispatchersConcurrencyTest.kt
kotlinx-coroutines-core/jvm/src/Dispatchers.kt
kotlinx-coroutines-core/native/src/Dispatchers.kt

* Emulate expect declaration refinement via extension property as the only way to do it in a backwards-compatible manner: in the current model it is impossible to have common 'expect' Dispatchers declaration, then refined 'concurrent' Dispatchers declaration with 'expect val IO' and then JVM declaration with JVM-specific members. Current solutions seems to be the less intrusive one
* Elasticity is not supported as K/N Workers API lacks capability to gracefully shutdown workers, meaning that for any unlimited underlying pool, memory consumption is only going to grow in an unbound manner
Fixes #3205

Introduce first version of Dispatchers.IO for K/N

---

kotlinx-coroutines-core/common/src/Deferred.kt

This pull request simply removes duplicated "be" verb from `Deferred` kdoc.

Remove duplicated 'be' from Deferred kdoc

---

README.md
gradle/compile-native-multiplatform.gradle
kotlinx-coroutines-core/build.gradle

More tier 3 targets added
Fixes #3601
Fixes #812
Fixes #855

Update K/N targets in accordance with official recommendations

---

docs/topics/coroutines-and-channels.md

GlobalScope should not be in loadContributorsConcurrent if you want the function to be cancellable by using the cancel button.

Fix example code

---

kotlinx-coroutines-core/common/src/channels/Broadcast.kt
kotlinx-coroutines-core/common/src/channels/BroadcastChannel.kt
kotlinx-coroutines-core/common/src/channels/Channels.common.kt
kotlinx-coroutines-core/common/src/flow/Channels.kt

Deprecate BroadcastChannel and the corresponding API

---

kotlinx-coroutines-test/jvm/src/migration/DelayController.kt
kotlinx-coroutines-test/jvm/src/migration/TestBuildersDeprecated.kt
kotlinx-coroutines-test/jvm/src/migration/TestCoroutineDispatcher.kt
kotlinx-coroutines-test/jvm/src/migration/TestCoroutineExceptionHandler.kt
kotlinx-coroutines-test/jvm/src/migration/TestCoroutineScope.kt
kotlinx-coroutines-test/jvm/test/migration/TestBuildersTest.kt
kotlinx-coroutines-test/jvm/test/migration/TestCoroutineDispatcherOrderTest.kt
kotlinx-coroutines-test/jvm/test/migration/TestCoroutineDispatcherTest.kt
kotlinx-coroutines-test/jvm/test/migration/TestCoroutineExceptionHandlerTest.kt
kotlinx-coroutines-test/jvm/test/migration/TestRunBlockingTest.kt

There are two kinds of APIs in the old version of the test framework:
* Foundational (`runBlockingTest`, `TestCoroutineScope`, etc.).
* Auxiliary (`DelayController`, some `TestCoroutineScope` methods like `pauseDispatcher`, etc.).
Some code bases are slow to migrate from the old foundational pieces, and I think we have quite many useful things in this release, so it would be unfortunate if someone stuck to the old release just because they didn't manage to update the tests yet. So, I just deprecated the things that the overwhelming majority of code bases don't use. The trio of `TestCoroutineScheduler`, `runBlockingTest`, and `TestCoroutineScope` is still here for one more release.

Promote the test module deprecation levels for 1.7.0

---

kotlinx-coroutines-test/common/test/RunTestTest.kt

The timeout was too low, the test body did not get a chance to run.
Fixes #3657

Fix a broken test

---

kotlinx-coroutines-test/api/kotlinx-coroutines-test.api
kotlinx-coroutines-test/common/src/TestBuilders.kt

Preserve binary compatibility with `TestScope.runTest(Long)`

---

kotlinx-coroutines-core/common/src/internal/LimitedDispatcher.kt
kotlinx-coroutines-core/concurrent/test/LimitedParallelismConcurrentTest.kt
kotlinx-coroutines-core/jvm/test/TestBase.kt

To support fairness w.r.t. the tasks that want to run on the wrapped dispatcher outside of its view, `LimitedDispatcher` redispatches the work loop periodically. This can happen even when there are no more tasks in `LimitedDispatcher`'s queue. Typically, this behavior is completely benign: after being redistpatched, the new runner just checks the queue, sees that there is nothing there, and leaves. However, with closable dispatchers, this affects correctness, as this redispatch may happen even after all the dispatched tasks were run and the dispatcher was closed.

Fix `limitedParallelism` doing dispatches when it has no tasks

---

kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt
kotlinx-coroutines-core/jvm/test/scheduling/CoroutineSchedulerInternalApiStressTest.kt

Previously, an arbitrary task was added to the scheduler's queue and the corresponding counter was incremented. The actual executing thread decremented the counter as soon as the task was done, meaning that, if timings are unlucky enough, the overall balance of blocking tasks could've been negative.
The second part of the equation is that all increments are atomic (instead of being CAS-based), meaning that due to programmatic bugs like the previous one, it's easy to overstep the boundary of adjacent masks, leaving the state in an inconsistent state.
Fix is trivial -- increment counter before publishing, do not reset it if the scheduler is closed and task wasn't added.
Fixes #3642

Fix oversubscription in Dispatchers.Default

---

kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/flow/StateFlow.kt
kotlinx-coroutines-core/common/src/flow/internal/AbstractSharedFlow.kt
kotlinx-coroutines-core/common/src/internal/Synchronized.common.kt
kotlinx-coroutines-core/js/src/internal/Synchronized.kt
kotlinx-coroutines-core/jvm/src/internal/ResizableAtomicArray.kt
kotlinx-coroutines-core/jvm/src/internal/Synchronized.kt
kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt
kotlinx-coroutines-core/native/src/internal/Synchronized.kt

The previous implementation was prone to a non-trivial contention that caused EDT freezes and, potentially, Android's ANRs.
Two root causes were identified:
1) Thread() constructor that has a non-trivial complexity along with JVM upcalls and is significantly slower than any other regular allocation 2) Thread.start() is on itself a JVM upcall that ends up on a global JVM lock[s]
Thread.start() is now invoked when the lock is released to reduce contention. The first root cause is not addressed as optimistic thread allocation may lead to a potential CPU waste due to how optimistically lock-less detection is and because Thread.start() is an order of magnitude slower anyway
Fixes #3652

Reduce contention on worker's lock in CoroutineScheduler

---

README.md

search.maven.org has been deprecated, and the provided links only redirect to the main page of central.sonatype.com.
I also replaced the usage of mvnrepository.com to be more consistent

Replace maven repostiory sites

---

kotlinx-coroutines-core/native/src/Debug.kt

The function was made experimental as a part of efforts to stabilize Native stdlib.

@OptIn for experimental identityHashCode

---

gradle.properties

Currently, tests for `android-unit-tests` and `kotlinx-coroutines-android` modules fail if they are being run on JDK 17. This is due to using version 4.4 of Robolectric; [starting from version 4.7 and onwards, Robolectric supports JDK 17](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.7).
Bumping Robolectric version to 4.9 in the project seems to have fixed the issue (and have not introduced any new issues) (checked via running `gradle clean build -x kotlinStoreYarnLock --continue --no-build-cache --no-configuration-cache`).

Update Robolectric to 4.9 for JDK 17 support during builds

---

kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt

Fix is needed for kotlinx.train on master after [KT-56583](https://youtrack.jetbrains.com/issue/KT-56583).

Fix type mismatch for integer cinterop conversions KT-56583

---

kotlinx-coroutines-core/build.gradle

This commit fixes the buildscript part that disabled Kover for jvmLincheckTest Gradle task. Previous implementation of this part disabled jvmLincheckTest altogether because `enabled` property that was being set to false actually belonged to DefaultTask class (inherited by jvmLincheckTest) instead of Kover API.

Enable jvmLincheckTest Gradle task back

---

kotlinx-coroutines-core/jvm/src/Executors.kt
kotlinx-coroutines-core/jvm/test/ExecutorsTest.kt

Calling `Dispatchers.Main.immediate.asExecutor().execute { ... }` should respect the fact that it's immediate, and avoid dispatch (and posting to the Looper) when in the right context.

CoroutineDispatcher.asExecutor() to respect isDispatchNeeded

---

docs/topics/cancellation-and-timeouts.md
docs/topics/coroutines-basics.md
kotlinx-coroutines-core/jvm/test/guide/example-basic-06.kt
kotlinx-coroutines-core/jvm/test/guide/test/BasicsGuideTest.kt

See https://youtrack.jetbrains.com/issue/KT-51515
Small fixes to clean up #3631
* Fix comment about 100k corouties in cancellation and timeouts section (it is now 10k!)
* Make "Coroutines are light-weight" example runnable by reducing the number of coroutines to 50k, also change the wording about what happens with threads

KT-51515 cleanup

---

benchmarks/build.gradle.kts
benchmarks/src/jmh/kotlin/benchmarks/flow/scrabble/ShakespearePlaysScrabble.kt

And remove usages of JvmDefault, which is going to be deprecated with error in KT-54746.

Enable -Xjvm-default=all for benchmarks

---

kotlinx-coroutines-debug/test/RunningThreadStackMergeTest.kt
kotlinx-coroutines-debug/test/StacktraceUtils.kt

We do rely on java.util.concurrent primitives for rendezvous in tests, but we cannot rely on their internal stacktraces in tests, thus filtering them out from test data.
Otherwise, tests outcome depends on the underlying JDK version
Fixes #3700

Filter out "java.util.concurrent" frames from debugging test machinery

---

kotlinx-coroutines-test/common/src/TestScope.kt

With #3449, the unrelated uncaught exceptions can also be caught in this manner.

Fix the error message if there were uncaught exceptions before test

---

kotlinx-coroutines-core/common/src/channels/BufferedChannel.kt

`expandBuffer()` was incorrectly processing removed segments.

Fix non-linearizability in `BufferedChannel.expandBuffer()`

---

kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt

[`require()`](https://github.com/lukellmann/kotlinx.coroutines/blob/d17e875275ff4ffbf5cf1a09e3fdbbf7d34acb83/kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt#L58) throws `IllegalArgumentException`, not `IllegalStateException`.

Fix documented exception type for `Flow.single()`

---

kotlinx-coroutines-test/api/kotlinx-coroutines-test.api
kotlinx-coroutines-test/common/src/TestBuilders.kt

Try once more to restore binary compatibility in `runTest`

---

kotlinx-coroutines-test/common/src/TestBuilders.kt

Fixes #3673 
Thanks, @ephemient!
Context: https://github.com/Kotlin/kotlinx.coroutines/pull/3742#discussion_r1192265210

Third time's the charm

---

docs/topics/shared-mutable-state-and-concurrency.md

The newline looks unnecessary.

Remove unnecessary newline

---

README.md

This PR updates the playground link to use the latest Kotlin version in in the `README.md`.

Update playground link to use latest Kotlin version in README.md

---

buildSrc/build.gradle.kts

Cherry pick from `kotlin-community/dev`

Fix CLI property ignored in version resolution

---

gradle.properties
kotlinx-coroutines-debug/README.md
kotlinx-coroutines-debug/build.gradle
kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt

* Also, exclude integration from docs, it shouldn't be there
Fixes #3701

Update BlockHound version to be compatible with JDK 17

---

kotlinx-coroutines-core/common/src/flow/internal/ChannelFlow.kt
kotlinx-coroutines-core/jvm/test/ThreadContextElementTest.kt
kotlinx-coroutines-core/jvm/test/ThreadContextMutableCopiesTest.kt

Hi, coroutine owners, this patch is needed as I'm using the thread context element to propagate thread local changes across context switching with flow. I have added a test case that demonstrate my use case. Please take a look when you have time, thanks!

Copy CopyableThreadContextElement when switching context with flowOn.

---

buildSrc/src/main/kotlin/CommunityProjectsBuild.kt
buildSrc/src/main/kotlin/configure-compilation-conventions.gradle.kts

Update user projects config: adapt build script to new TeamCity variables

---

kotlinx-coroutines-core/concurrent/src/MultithreadedDispatchers.common.kt
kotlinx-coroutines-core/jvm/src/ThreadPoolDispatcher.kt
kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt
kotlinx-coroutines-core/native/test/MultithreadedDispatchersTest.kt

Before the change, the Worker is not notified about its work being cancelled, due to no API being present for that.
We work around the issue by checking every 100 milliseconds whether cancellation happened.
Fixes #3768

Fix newSingleThreadContext awaiting cancelled scheduled coroutines

---

kotlinx-coroutines-core/common/src/internal/StackTraceRecovery.common.kt

In https://youtrack.jetbrains.com/issue/KT-58551 we require all annotations from expect declaration to be present on actual.
`unwrap` violates this by having `@PublishedApi` only on expect.
This blocks merge of PR in KT-58551.
Currently, `unwrap` is not called from public inline functions. 
Looks like just removing annotation is a safe fix.

Remove `@PublishedApi` from `unwrap` to comply with new compiler resriction

---

kotlinx-coroutines-core/concurrent/test/LimitedParallelismConcurrentTest.kt
kotlinx-coroutines-core/concurrent/test/MultithreadedDispatcherStressTest.kt
kotlinx-coroutines-core/jvm/test/JobHandlersUpgradeStressTest.kt

The new atomicfu JVM compiler plugin (since 1.9.20) will explicitly require atomic properties to be private or internal (or be members of private or internal classes). These fixes are required now in the aggregate build to merge changes in the new jvm plugin, so this commit is added to develop first.

Fixed visibility of atomic properties as required by the new JVM compiler plugin

---

build.gradle
gradle.properties
kotlinx-coroutines-core/build.gradle

Please review the changes in the published artifacts in kotlinx-coroutines-core and kotlinx-coroutines-test:
- the main artifact is now a common klib (with .jar extension) instead of legacy metadata jar, 
- no artifact is published under `-all` classifier, which was previously a common klib.

Stop building and publishing compatibility MPP metadata variant

---

kotlinx-coroutines-core/common/src/sync/Mutex.kt

The previous documentation of the `Mutex.lock()` method was confusing to me. It seemed to imply that the call would suspend the entire time that the lock was held, when in fact it just suspends until the lock is acquired.

Clarify documentation of Mutex.lock() behavior

---

kotlinx-coroutines-core/common/src/flow/operators/Delay.kt
kotlinx-coroutines-core/jvm/test/examples/example-timeout-duration-01.kt

3789: Update flow.timeout example to re-throw

---

docs/topics/coroutine-context-and-dispatchers.md

Runnable snippet produces errors, probably due to Playground limitations. See [KT-60424](https://youtrack.jetbrains.com/issue/KT-60424/Web-feedback-from-Coroutine-context-and-dispatchers-https-kotlinlang.org-docs-coroutine-context-and-dispatchers.html)

fix: errors in runnable snippet

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt

PR #3746 introduced a bug due to which the IDEA coroutine debugger didn't run. See
https://youtrack.jetbrains.com/issue/KTIJ-26327

Fix the IDEA debugger

---

kotlinx-coroutines-core/build.gradle

After changes required for https://youtrack.jetbrains.com/issue/KT-57292/Rework-configuration-of-compiler-settings-in-MPP-Projects consistency checks were move later in configuration phase. Now they started also catch inconsistency between "jvmMain" and "jvmCoreMain" source sets.

Ignore adding additional optIns also for "jvmCoreMain" source set

---

kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt

Caused by: https://youtrack.jetbrains.com/issue/KT-59859/Change-the-OptIn-Level-to-Error-for-kotlinx.cinterop.UnsafeNumber
was found in kotlinx.train, reproduced only on macOS

Add Optin for kotlinx.cinterop.UnsafeNumber due to KT-59859

---

docs/topics/composing-suspending-functions.md

With the current version, it's easy to read and understand all the examples, get distracted/move on to a different topic, and miss the warning that this is a _strongly discouraged_ approach below the text.

Move async-style warning above the paragraph in question

---

kotlinx-coroutines-core/jvm/test/TestBase.kt

The compilation error appeared after KT-59665

Fix NO_ACTUAL_CLASS_MEMBER_FOR_EXPECTED_CLASS compilation error

---

kotlinx-coroutines-core/js/test/TestBase.kt

The compilation error appeared after KT-59665
It's a follow-up on #3826
I didn't discover this problem when I was merging my changes in `kotlin/master` because of user-project misconfiguration in aggregator: https://jetbrains.slack.com/archives/C3AHQFSKH/p1692181741230819?thread_ts=1691744229.982909&cid=C3AHQFSKH

Fix NO_ACTUAL_CLASS_MEMBER_FOR_EXPECTED_CLASS compilation error #2

---

kotlinx-coroutines-core/common/src/CoroutineScope.kt

It probably makes sense to clearly differentiate that this is, in fact, _concurrent_ rather than _parallel_ (that is, single-threaded interleaved computations are okay)
(Previous internal discussion: https://jetbrains.slack.com/archives/C3TNY2MM5/p1680694409771889)

Change "parallel decomposition" to "concurrent decomposition"

---

kotlinx-coroutines-core/native/test/ConcurrentTestUtilities.kt

Kotlin 1.9.20 migration: Fix NO_ACTUAL_CLASS_MEMBER_FOR_EXPECTED_CLASS

---

kotlinx-coroutines-core/native/test/ConcurrentTestUtilities.kt

Update suppress after KT-22841

Kotlin 1.9.20 migration: Fix ACTUAL_CLASSIFIER_MUST_HAVE_THE_SAME_MEM…BERS_AS_NON_FINAL_EXPECT_CLASSIFIER compilation error (#3870)

---

buildSrc/src/main/kotlin/configure-compilation-conventions.gradle.kts

This warning is introduced in Kotlin 1.9. KT-61573 If I don't mute this warning then the build fails because of `-Werror`

Mute "expect/actual classes are experimental" warning

---

kotlinx-coroutines-core/concurrent/src/internal/LockFreeLinkedList.kt

Code red in IDE on IU-232.9921.47, Kotlin IDE Plugin 232-1.9.20-Beta-release-242
Would be nice to merge it, because IDE Integration tests in IJ check exactly this file and they're failing at the moment.

Suppress forgotten error about actual classifier scope mismatch

---

kotlinx-coroutines-core/concurrent/src/CompletionHandler.kt
kotlinx-coroutines-core/concurrent/src/internal/LockFreeLinkedList.kt
kotlinx-coroutines-core/js/src/internal/LinkedList.kt
kotlinx-coroutines-core/jvm/src/EventLoop.kt
kotlinx-coroutines-core/jvm/src/Executors.kt
kotlinx-coroutines-core/jvm/src/SchedulerTask.kt
kotlinx-coroutines-core/jvm/test/TestBase.kt
kotlinx-coroutines-core/native/src/internal/Synchronized.kt
kotlinx-coroutines-core/native/test/ConcurrentTestUtilities.kt

https://youtrack.jetbrains.com/issue/KT-62263

"member scope mismatch for open expect" was downgraded from error to warning

---

kotlinx-coroutines-test/common/src/TestScope.kt
kotlinx-coroutines-test/common/test/Helpers.kt
kotlinx-coroutines-test/common/test/RunTestTest.kt
kotlinx-coroutines-test/common/test/TestScopeTest.kt
kotlinx-coroutines-test/jvm/test/UncaughtExceptionsTest.kt

Ensure `runTest` unsubscribes from the exception handler

---

kotlinx-coroutines-core/common/src/sync/Mutex.kt
kotlinx-coroutines-core/common/src/sync/Semaphore.kt
kotlinx-coroutines-core/common/test/sync/MutexTest.kt
kotlinx-coroutines-core/common/test/sync/SemaphoreTest.kt

Since at least Kotlin 1.8.0, the Kotlin/JS IR compiler miscompiles a specific combination of a caller of an `inline` function containing a `finally` block: the `finally` block is called twice. This is rare, but can happen when a user calls `Mutex.withLock` or `Semaphore.withPermit`.
I originally reported this issue to the library (https://github.com/Kotlin/kotlinx.coroutines/issues/3754) without any idea how to reproduce it. @dkhalanskyjb managed to create a minimal reproducer and created a ticket against the Kotlin compiler ([KT-58685](https://youtrack.jetbrains.com/issue/KT-58685)). After discussing on the Kotlin Slack ([thread](https://kotlinlang.slack.com/archives/C0B8L3U69/p1693863899538249)), @rjaros found the workaround contained in this PR. Thanks to @JSMonk as well for attempting …

Workaround for KT-58685

---

README.md
gradle.properties
integration-testing/gradle.properties
kotlinx-coroutines-core/api/kotlinx-coroutines-core.api

Addresses [KT-60230](https://youtrack.jetbrains.com/issue/KT-60230)-related failures on our CI

Update Kotlin to 1.9.20

---

docs/topics/exception-handling.md

Because `inner` is a soft keyword in Kotlin, it's wrongly highlighted in the playground. Renaming the variable to `innerJob` makes it consistent with the other `job` variable that is in the same snippet, and removes this odd highlighting.

Rename `inner` to `innerJob` in exception-handling.md to fix highlighting

---

docs/topics/exception-handling.md

Since [Kotlin 1.5](https://kotlinlang.org/docs/whatsnew15.html#new-default-jvm-target-1-8), the compiler does not support producing bytecode compatible with Java versions below 8. Therefore, this reference to needing JDK 8 or higher seems superfluous.

Remove JDK7 reference from exception handling guide

---

kotlinx-coroutines-core/common/src/flow/SharedFlow.kt

Addresses the new comment to #2871

Specify that `subscriptionCount` not conflating is a guarantee

---

docs/topics/exception-handling.md

Actors are marked as `@ObsoleteCoroutinesApi`, so people learning about coroutines most likely don't need to learn about them here.

Remove reference to actors from coroutines guide

---

kotlinx-coroutines-core/common/src/Delay.kt
kotlinx-coroutines-core/common/test/DurationToMillisTest.kt

Prior to this commit Durations used for delays or timeouts lost their nanosecond granularity when being converted to a millisecond Long value. This effectively meant that delays could resume prior to when they were scheduled to do so.
This commit solves this by rounding a Duration with nanosecond components up to the next largest millisecond.
Closes #3920

Properly round `Duration` instances to milliseconds

---

gradle/dokka.gradle.kts

Change Gradle configuration to make sure "source" button is visible in all API docs (#3929)

---

kotlinx-coroutines-core/build.gradle
kotlinx-coroutines-core/jvmBenchmark/README.md
kotlinx-coroutines-core/jvmBenchmark/kotlin/kotlinx/coroutines/BenchmarkUtils.kt
kotlinx-coroutines-core/jvmBenchmark/kotlin/kotlinx/coroutines/SemaphoreBenchmark.kt
kotlinx-coroutines-core/jvmBenchmark/kotlin/kotlinx/coroutines/channels/ChannelProducerConsumerBenchmark.kt
kotlinx-coroutines-core/jvmBenchmark/kotlin/kotlinx/coroutines/channels/SelectBenchmark.kt
kotlinx-coroutines-core/jvmBenchmark/kotlin/kotlinx/coroutines/channels/SimpleChannel.kt
kotlinx-coroutines-core/jvmBenchmark/kotlin/kotlinx/coroutines/channels/SimpleChannelBenchmark.kt
kotlinx-coroutines-core/jvmBenchmark/kotlin/kotlinx/coroutines/flow/TakeWhileBenchmark.kt

It allows us to benchmark `internal` API unavailable otherwise and allows us to backport K2 changes properly.
Only benchmarks that somehow leverage `internal` API are moved in the new source-set

Introduce jvmBenchmarks into kotlinx-coroutines-core

---

kotlinx-coroutines-core/common/test/TestBase.common.kt
kotlinx-coroutines-core/js/test/TestBase.kt
kotlinx-coroutines-core/jvm/test/TestBase.kt
kotlinx-coroutines-core/native/test/TestBase.kt

In K2, the resolution rules changed, and we relied on the specific behavior of the K1 compiler.

Ensure that `println` is properly resolved in the JVM tests

---

kotlinx-coroutines-test/common/src/TestBuilders.kt
kotlinx-coroutines-test/js/src/TestBuilders.kt
kotlinx-coroutines-test/jvm/src/TestBuildersJvm.kt
kotlinx-coroutines-test/native/src/TestBuilders.kt

This PR attempts to fix #3800.
The first part of the fix, reverting the timeout to 60 seconds, is successful.
The second part, allowing global configuration, not so much.
On JVM, Native, and Node JS, it's possible to use environment variables to communicate data to the process, and it could in theory be the solution, but it doesn't seem to interoperate well with Gradle.
The best attempt so far was to use this:
```kotlin
tasks.withType(AbstractTestTask::class).all {
if (this is ProcessForkOptions) {
environment("kotlinx.coroutines.test.default_timeout", "1ms")
}
}
```
Unfortunately, only `jvmTest` implements `ProcessForkOptions`.
Without a clear way to configure the `runTest` timeout in Gradle builds, we can't claim that this is a proper solution.

Rollback runTest timeout to 60 seconds, configure it with getenv

---

gradle/dokka.gradle.kts

Fully fixes #3929 
After #3930 was merged there is no more `(source)` for MPP modules (core and test) because they are using different convention for sources.
In this PR dokka configuration for MPP modules is aligned with how sources are configured + it now doesn't use hardcoded names of sourceSets (previously, f.e. `jdk8` and `concurrent` were not configured, and so no `(source)` link were there)
BTW, I found, that there is some issue, that functions which are in `jdk8` can't resolve classes from `common` (in this case there should be `Flow`:
<details><summary>Screenshot</summary>
</details>
I will try to address this in another PR later, or create an issue at Dokka side, depending on the results of investigation

Update Gradle Dokka configuration to make sure `(source)` button is visible in all API docs

---

kotlinx-coroutines-core/common/test/MainDispatcherTestBase.kt
kotlinx-coroutines-core/js/test/ImmediateDispatcherTest.kt
kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt
kotlinx-coroutines-core/nativeDarwin/test/MainDispatcherTest.kt
ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt
ui/kotlinx-coroutines-android/test/HandlerDispatcherTest.kt
ui/kotlinx-coroutines-javafx/build.gradle.kts
ui/kotlinx-coroutines-javafx/test/JavaFxDispatcherTest.kt
ui/kotlinx-coroutines-swing/test/SwingTest.kt

Ensure Dispatchers.Main != Dispatchers.Main.immediate on Android

---

gradle/dokka.gradle.kts

Based on discussion: https://github.com/Kotlin/kotlinx-datetime/pull/323#discussion_r1412147614
Checked locally - content is identical for both approaches

Simplify Dokka source link configuration

---

build.gradle

A rather obscure problem was revealed while compiling coroutines against the current develop atomicfu branch before 0.23.2 release.  
**Reproducer:**
kotlinx-atomicfu: 
`develop` branch: `clean build publishToMavenLocal` 
kotlinx.coroutines:
`obscure-atomicfu-application-order` branch: `:kotlinx-coroutines-core:compileKotlinJvm -Patomicfu_version=0.23.1-SNAPSHOT`
Reproduced with Kotlin `1.9.20`, `1.9.21` and `2.0.0-dev-*`
```
e: Module kotlinx.atomicfu cannot be found in the module graph
```
> Note that this error is thrown before atomicfu-gradle-plugin is applied. 
The error started to reproduce after these changes in [kotlinx-atomicfu#377](https://github.com/Kotlin/kotlinx-atomicfu/pull/377): (atomicfu compiler plugin should be manually added to the classpath by the user).
Changing the …

Change the order of atomicfu and kotlin plugins in the classpath

---

gradle.properties
kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/build.gradle
kotlinx-coroutines-core/common/src/CoroutineStart.kt
kotlinx-coroutines-core/common/src/channels/Channels.common.kt
kotlinx-coroutines-core/common/src/channels/Deprecated.kt
kotlinx-coroutines-core/common/src/flow/operators/Delay.kt
kotlinx-coroutines-core/common/src/flow/operators/Zip.kt
kotlinx-coroutines-core/common/src/internal/ThreadSafeHeap.kt
kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt
kotlinx-coroutines-core/common/test/channels/BroadcastTest.kt
kotlinx-coroutines-core/common/test/flow/BuildersTest.kt
kotlinx-coroutines-core/common/test/flow/operators/BufferTest.kt
kotlinx-coroutines-core/common/test/flow/operators/CombineTest.kt
kotlinx-coroutines-core/common/test/flow/operators/DebounceTest.kt
kotlinx-coroutines-core/common/test/flow/operators/SampleTest.kt
kotlinx-coroutines-core/common/test/flow/operators/TimeoutTest.kt
kotlinx-coroutines-core/common/test/sync/MutexTest.kt
kotlinx-coroutines-core/concurrent/src/internal/LockFreeLinkedList.kt
kotlinx-coroutines-core/jvm/test/internal/LockFreeLinkedListLongStressTest.kt
kotlinx-coroutines-core/jvm/test/jdk8/future/FutureTest.kt

* Add missing tests for reasonable things (i.e. invariants are tested, things like utility 'toString' are not)
* Remove some unused code
* Add a few more excludes
* Move Broadcast-related deprecations to 'Deprecated.kt' and promote them to ERROR

Increase code coverage in core module

---

buildSrc/src/main/kotlin/kotlin-multiplatform-conventions.gradle.kts
integration-testing/smokeTest/build.gradle

I think we should keep #3968 open until it's fixed properly.

Work around #3968, start running integration tests for Native

---

kotlinx-coroutines-core/build.gradle.kts

With the newer Kotlin Gradle plugin, we got this error: `'var compilations: NamedDomainObjectContainer<KotlinJvmCompilation>' can't be called in this context by implicit receiver. Use the explicit one if necessary`
With this change, we use an explicit receiver, as instructed.

Fix a build error

---

kotlinx-coroutines-core/common/src/flow/internal/Combine.kt
kotlinx-coroutines-core/common/src/flow/internal/FlowExceptions.common.kt
kotlinx-coroutines-core/common/src/flow/operators/Limit.kt
kotlinx-coroutines-core/common/test/flow/operators/OnCompletionTest.kt
kotlinx-coroutines-core/jsAndWasmShared/src/flow/internal/FlowExceptions.kt
kotlinx-coroutines-core/jvm/src/flow/internal/FlowExceptions.kt
kotlinx-coroutines-core/native/src/flow/internal/FlowExceptions.kt

Before this change, it could happen that some size-limiting operators upstream swallowed the requests to limit the flow size emitted by the operators downstream.
This could cause `onCompletion` calls between these operators to incorrectly report that the flow was not in fact limited by the downstream operators.
Additionally, in the presence of additional size-limiting operators in the chain, `first` and `single` and their variants could exhibit incorrect behavior where emitting a value from `onCompletion` would overwrite their output.
Fixes #4035

Ensure that flow operators propagate the cancellation exceptions

---

kotlinx-coroutines-core/jvm/test/flow/SharingStressTest.kt
kotlinx-coroutines-test/common/src/TestCoroutineScheduler.kt
kotlinx-coroutines-test/common/src/TestScope.kt
kotlinx-coroutines-test/common/test/TestCoroutineSchedulerTest.kt

It's stable since Kotlin 1.9.0.

Remove outdated ExperimentalTime annotation on TimeSource

---

kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt

During the creation of `CoroutineScheduler.Worker`, we need to initialize its embedded random number generator. To avoid additional class-loading costs (#4051), `rngState` is now directly initialized from the current nanoTime (that is used as seed).
Also, a potential bug is fixed, where `nextInt` will always return zero due to incorrect initialization of rngState with zero.
This may happen during the creation of a worker with thread id = `1595972770` (JDK >=8), or unpredictable if fallback thread-local random is used (android SDK <34 or JDK <7), approximate probability is 2.4E-10
Fixes #4051

Remove usage of `kotlin.random.Random` form `CoroutineScheduler.Worker` init

---

kotlinx-coroutines-core/concurrent/test/channels/BroadcastChannelSubStressTest.kt
kotlinx-coroutines-core/concurrent/test/sync/MutexStressTest.kt
kotlinx-coroutines-core/jvm/test/AbstractLincheckTest.kt
kotlinx-coroutines-core/jvm/test/channels/BroadcastChannelMultiReceiveStressTest.kt
kotlinx-coroutines-core/jvm/test/selects/SelectPhilosophersStressTest.kt

For now, it takes up to 8 hours, gobbling our TC agent pool and failing by timeout

Reduce the overall time spent on stress tests in stress mode

---

kotlinx-coroutines-core/common/src/flow/StateFlow.kt
kotlinx-coroutines-core/common/src/internal/Concurrent.common.kt
kotlinx-coroutines-core/jsAndWasmShared/src/internal/Concurrent.kt
kotlinx-coroutines-core/jvm/src/internal/Concurrent.kt
kotlinx-coroutines-core/native/src/internal/Concurrent.kt

Replace the specific place where ARFU gets misexecuted by specific Android toolchain
Fixes #3820

Potential workaround for #3820

---

kotlinx-coroutines-core/common/src/channels/BufferedChannel.kt
kotlinx-coroutines-core/common/src/channels/ConflatedBufferedChannel.kt

Calling a function containing atomic operations from a different file results in the failure of Native incremental compilation.
Made `BufferedChannel#sendImpl` function private.
This is a WA for [KT-65554](https://youtrack.jetbrains.com/issue/KT-65554/atomicfu-K-N-Plugin-generates-IrGetField-from-another-file)
Maybe we could refactor this in a better way though.

Function containing atomic operations should be private 

---

kotlinx-coroutines-core/jvm/src/scheduling/CoroutineScheduler.kt
kotlinx-coroutines-core/jvm/test/scheduling/BlockingCoroutineDispatcherThreadLimitStressTest.kt
kotlinx-coroutines-core/jvm/test/scheduling/SchedulerTestBase.kt

These tests, in their current form, have two flaws:
1) `checkPoolThreadsCreated` is used incorrectly because it's awfully misguiding. Here is the gist of it:
```
fun checkPoolThreadsCreated(range: IntRange, base: Int = CORES_COUNT) {
val maxSequenceNumber = maxSequenceNumber()!!
val r = (range.first)..(range.last + base)
assertTrue(
...
)
}
```
It attempts to acknowledge that apart from the threads created, there should be at most `CORES_COUNT` "core" threads, which does not make any sense test-wise.
So the original test hasn't tested that there were threads created in `[1 .. CORES + 1]` range, it tested that there were threads created in `[1 .. + 2*CORES + 1]` range, which makes it, well, much less reproducible.
This fix of this problem alone is enough to let the problem manifest itself. …

Remove created threads restriction from BlockingCoroutineDispatcherThreadLimitStressTest

---

kotlinx-coroutines-core/common/src/flow/operators/Delay.kt
kotlinx-coroutines-core/common/test/flow/operators/TimeoutTest.kt

Fix `Flow.timeout` swallowing the channel closure exception

---

kotlinx-coroutines-core/common/test/CoroutineScopeTest.kt
kotlinx-coroutines-core/native/src/CoroutineContext.kt

Install `Dispatchers.Default` on native when creating new context for coroutine builders when there is no `ContinuationInterceptor` there

---

docs/topics/coroutine-context-and-dispatchers.md

https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html#jumping-between-threads
UPD: removed sampleStart and sampleEnd comments.
Fix this sample not being runnable:

fix: remove `sampleStart` and `sampleEnd` comments from example in coroutine-context-and-dispatchers.md

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/Builders.common.kt
kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/common/src/internal/DispatchedContinuation.kt
kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugCoroutineInfoImpl.kt
kotlinx-coroutines-core/jvm/src/debug/internal/StackTraceFrame.kt
kotlinx-coroutines-core/jvm/src/scheduling/Tasks.kt
kotlinx-coroutines-core/jvm/test/ReusableCancellableContinuationTest.kt

According to @mvicsokolova, the following entry points are not used by IDEA since 2020:
```
kotlinx.coroutines.debug.internal.StackTraceFrame
field callerFrame
field stackTraceElement
kotlinx.coroutines.StandaloneCoroutine
field _state
field context
kotlinx.coroutines.ChildContinuation
field child
kotlinx.coroutines.CancellableContinuationImpl
field _decision
field delegate
field resumeMode
field submissionTime
field context
kotlinx.coroutines.DispatchedContinuation
field continuation
```
According to https://youtrack.jetbrains.com/issue/IDEA-335375/Change-coroutine-debugger-implementation-to-use-a-new-package#focus=Comments-27-6989405.0-0,
this leaves only the following *internal* entry points:
```
kotlinx.coroutines.debug.internal.DebugCoroutineInfo
method getCreationStackTrace()
method …
```

Remove the `@PublishedApi` that are no longer needed for the debugger

---

kotlinx-coroutines-core/common/src/channels/BufferedChannel.kt
kotlinx-coroutines-core/common/test/channels/BufferedChannelTest.kt

The rationale in favor of the change includes:
* in the `1.6.x` series `Channel().iterator().hasNext()` was idempotent
* despite the lack of requirement for the `Iterator#hasNext` method implementations to be idempotent, it is generally safer to make them such. The same applies to `ChannelIterator#hasNext`
Here is an example where it matters. Consider the following code snippet:
```
val chunk = mutableListOf<Int>()
while(iter.hasNext()) {
val v = iter.next()
chunk.add(v)
if (chunk.size >= MAX_BATCH_SIZE || !iter.hasNext()) {
yield(chunk.toList())
chunk.clear()
}
}
```
We address two concerns with one block of code - we run the if-block on reaching the chunk size limit or on the last chunk.
If `#hasNext` isn't idempotent, I see a couple of options. The first solution is, the code would …

Make `BufferedChannelIterator#hasNext` idempotent

---

docs/topics/coroutine-context-and-dispatchers.md

This PR fixes a typo in the `coroutine-context-and-dispatchers.md`.

Fix typo in coroutine-context-and-dispatchers.md

---

docs/topics/flow.md

Recently I've come across the flow docs and noticed one example output isn't displayed in the online version.
In the source file the output is present but hidden inside an XML comment.
I've extracted the output to a text block to display it in the online docs.

Extract example output from comment to text block

---

docs/topics/channels.md
kotlinx-coroutines-core/jvm/test/guide/example-channel-01.kt

1. Got rid of this scrolling:
2. Moved //sampleStart higher to show more code. We mention the "produce" function but don't show it. A reader immediately starts searching for it in the example below:
When not finding it, they have to expand this code anyway:

fix: get rid of horizontal scrolling by splitting the comment and show more code mentioned

---

kotlinx-coroutines-test/README.md

The default timeout for runTest changed from 10 seconds to 60 seconds in 9a98eabed91c71cb2da9b0fe061139632e08990b. This PR makes the README reflect that change.

Fix documentation about the default timeout for runTest

---

docs/topics/exception-handling.md
kotlinx-coroutines-core/jvm/test/guide/test/ExceptionsGuideTest.kt

1. fix the number of DefaultDispatcher-worker in the output: the output always gives the number 1 for worker, not 2:
2. give the link to the `Thread.uncaughtException Handler` interface itself:
Now it will be:
It was:

fix link to `Thread.uncaughtException Handler`: give the link to the interface itself; fix the number of DefaultDispatcher-worker in the output

---

gradle.properties
reactive/kotlinx-coroutines-reactor/build.gradle.kts

See <https://github.com/reactor/reactor-core/issues/3794>

Fix broken API reference links to the Project Reactor Javadoc

---

docs/topics/channels.md
kotlinx-coroutines-core/jvm/test/guide/example-channel-10.kt
kotlinx-coroutines-core/jvm/test/guide/test/ChannelsGuideTest.kt

https://play.kotlinlang.org/ of the example that's being changed here is currently unreliable: the last line is occasionally `null`.
By increasing all time intervals twofold, we reduce the impact of the CPU scheduling in the constrained environment. With this change, the results are consistent across dozens of runs: <https://pl.kotl.in/uCa-60j43>
Originally reported by `@PetrakovichVictoria`

Fix the ticker channel example giving wrong results on the website

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/internal/LimitedDispatcher.kt
kotlinx-coroutines-core/concurrent/src/Dispatchers.kt
kotlinx-coroutines-core/concurrent/src/MultithreadedDispatchers.common.kt
kotlinx-coroutines-core/jvm/src/DefaultExecutor.kt
kotlinx-coroutines-core/jvm/src/scheduling/Dispatcher.kt
kotlinx-coroutines-core/jvm/test/DispatchersToStringTest.kt

While I figure out stabilization details, these are pretty straightforward changes that can be merged into minor releases

Limited parallelism improvements

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/api/kotlinx-coroutines-core.klib.api
kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/EventLoop.common.kt
kotlinx-coroutines-core/common/src/MainCoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/Unconfined.kt
kotlinx-coroutines-core/common/src/internal/LimitedDispatcher.kt
kotlinx-coroutines-core/common/src/internal/NamedDispatcher.kt
kotlinx-coroutines-core/jsAndWasmShared/src/internal/JSDispatcher.kt
kotlinx-coroutines-core/jvm/src/internal/MainDispatchers.kt
kotlinx-coroutines-core/jvm/src/scheduling/Dispatcher.kt
kotlinx-coroutines-core/jvm/test/DispatchersToStringTest.kt
kotlinx-coroutines-core/native/src/Dispatchers.kt
test-utils/common/src/TestBase.common.kt

Add optional name parameter to .limitedParallelism

---

kotlinx-coroutines-core/common/src/flow/Migration.kt

Replacing "SharingStared" with correct "SharingStarted".  
Fixing wrong order of parameters in replaceWith of cache() method.

Fix documentation of Migration.kt

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/Unconfined.kt
kotlinx-coroutines-core/common/src/internal/LimitedDispatcher.kt
kotlinx-coroutines-core/jvm/src/scheduling/Dispatcher.kt
kotlinx-coroutines-core/native/src/Dispatchers.kt
kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt

Promote CoroutineDispatcher.limitedParallelism to stable

---

kotlinx-coroutines-core/common/src/EventLoop.common.kt
kotlinx-coroutines-core/jvm/test/EventLoopsTest.kt

Preserve the relative order of delayed and non-delayed tasks in event loops

---

kotlinx-coroutines-core/build.gradle.kts
kotlinx-coroutines-test/build.gradle.kts

Optimization was turned on due to performance problems. However, with new K/N memory manager these performance problems seem to be fixed. On the other hand, compiling in optimized mode significantly increases the compiler's memory consumption, so it's better to turn it off.
In particular, we (in K/N team) are having some problems with updating to LLVM 16 due to increased memory consumption (it's still being investigated what causes it), more details here: https://youtrack.jetbrains.com/issue/KT-68418/Native-updating-to-LLVM-16-makes-kotlinx.coroutines-build-in-Aggregate-unstable. This commit workarounds it.

Turn off optimization mode when compiling tests for K/N

---

kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt

This line of the `launchIn` documentation is a bit confusing: I think it applies to all general usage of `launchIn`, which left me wondering why the returned `Job` is ignored. 
This is a really small tweak to make this clear. As an alternate, I think we can also just remove the line altogether and avoid any confusion. 
See also: https://kotlinlang.slack.com/archives/CRJCTR5PD/p1717093849474799

Clarify documentation of `launchIn`

---

buildSrc/src/main/kotlin/GlobalKotlinCompilerOptions.kt
buildSrc/src/main/kotlin/configure-compilation-conventions.gradle.kts
buildSrc/src/main/kotlin/kotlin-jvm-conventions.gradle.kts
buildSrc/src/main/kotlin/kotlin-multiplatform-conventions.gradle.kts

Problem:
IntelliJ IDEA reports opt-in usage errors despite the fact that opt-ins are configured for all the compilations correctly. The reported error doesn't result in broken compilations or tests.
Motivation for the change:
The problem is not caused by the K2 IDE analysis mode, but it affects the K2 IDE quality gates.
See: https://youtrack.jetbrains.com/issue/KT-68642
Explanation:
Before the release of KGP 2.0.0 there was no clear way to set up compiler arguments for particular Kotlin multiplatform source sets: ones that participate in multiple compilations but are not a default source set for any compilation. Examples of such source sets are shared test source sets (they are not compiled into Kotlin metadata) and the unique `jdk8` source set used in `kotlinx-coroutines`. The 2.0.0 …

Fix opt-in usage error shown in IntelliJ IDEA for some of the project files

---

kotlinx-coroutines-core/common/src/Timeout.kt

Currently, it ends up rendering wrong in the [API reference](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-timeout.html).

Fix links to external documentation in Timeout

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.klib.api
kotlinx-coroutines-core/wasmJs/src/CoroutineContext.kt
kotlinx-coroutines-core/wasmJs/src/JSDispatcher.kt

In a matter of removing w3c declarations from WasmJs stdlib we need to remove its usages from the coroutines.

Remove w3c usages from wasmJs implementation

---

kotlinx-coroutines-core/common/src/CoroutineStart.kt

Stabilize CoroutineStart.ATOMIC

---

kotlinx-coroutines-core/common/src/sync/Mutex.kt
kotlinx-coroutines-core/common/src/sync/Semaphore.kt
kotlinx-coroutines-core/common/test/sync/MutexTest.kt
kotlinx-coroutines-core/jvm/test/lincheck/SemaphoreLincheckTest.kt

Forbid casting Mutex to a Semaphore

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/common/src/Await.kt
kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt
kotlinx-coroutines-core/common/src/Job.kt
kotlinx-coroutines-core/common/src/JobSupport.kt
kotlinx-coroutines-core/jdk8/src/future/Future.kt
kotlinx-coroutines-core/jvm/src/Executors.kt
kotlinx-coroutines-core/jvm/src/Future.kt
kotlinx-coroutines-core/jvm/src/Interruptible.kt
kotlinx-coroutines-core/jvm/test/ExecutorAsCoroutineDispatcherDelayTest.kt
kotlinx-coroutines-core/jvm/test/jdk8/future/FutureTest.kt

Fix stack overflow when calling asDeferred on a Future many times

---

kotlinx-coroutines-test/common/src/TestBuilders.kt

* Clearly separate the cases when the test body finished and was just waiting for the children from the cases where the test body itself kept running;
* When the test only awaits the child coroutines, mention `TestScope.backgroundScope`
Fixes #4182

Improve runTest timeout messages

---

reactive/README.md

Correct the link for RxJava 2.x

Correct the link for RxJava 2.x

---

kotlinx-coroutines-core/native/src/Builders.kt

kotlinx-coroutines-core/jvm/src/Builders.kt documentation looked rather strange and had incorrect grammar, replaced with kotlinx-coroutines-core/native/src/Builders.kt documentation for runBlocking.
This should be correct. If I have made a mistake, I apologize in advance.

Fix documentation of runBlocking

---

kotlinx-coroutines-core/common/src/channels/BufferOverflow.kt
kotlinx-coroutines-core/common/src/channels/Channels.common.kt
kotlinx-coroutines-core/common/src/channels/Produce.kt
kotlinx-coroutines-core/common/test/channels/ChannelsTest.kt
kotlinx-coroutines-core/common/test/channels/ConsumeTest.kt
kotlinx-coroutines-core/common/test/channels/ProduceTest.kt

One of the pieces of https://github.com/Kotlin/kotlinx.coroutines/issues/4133.
Each file can be reviewed independently (and changes to other files will be added later). I'm keeping this a single pull request to avoid spamming.

Extend the KDoc for some channel APIs

---

docs/topics/channels.md
kotlinx-coroutines-core/common/src/flow/Migration.kt
kotlinx-coroutines-core/common/src/flow/operators/Limit.kt

I think that the double use of `the` and `it` in this part in English is grammatically incorrect, except for the intentional emphasis.  
And, it doesn't seems to be something that needed to be emphasized.
So, I didn't think it was an intentional mistake, so I fixed it.

Fix too many `the` and `it` on some comments

---

gradle.properties

Looks like property for [kotlinx.html](https://github.com/Kotlin/kotlinx.html), which isn't used in project

Remove redundant `html_version` gradle property

---

kotlinx-coroutines-core/api/kotlinx-coroutines-core.klib.api
kotlinx-coroutines-test/api/kotlinx-coroutines-test.klib.api

Refresh the API dump without code changes. Fix the order of items in the dump after updating to a newer version of the compatibility-validator. Version updates without dump refreshing were possible due to https://github.com/Kotlin/binary-compatibility-validator/issues/260

Rerun apiDump

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/CoroutineStart.kt

One of the pieces of #4133.
@fzhinkin, could you take a look?

Extend the KDoc for `CoroutineStart`

---

kotlinx-coroutines-core/common/src/CompletableDeferred.kt
kotlinx-coroutines-core/common/src/CompletableJob.kt
kotlinx-coroutines-core/common/src/Deferred.kt
kotlinx-coroutines-core/common/src/Job.kt

The SubclassOptInRequired annotation will accept multiple markers in arguments. This fix is required to maintain source compatibility.

Preparation commit for KT-70562

---

kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt

When `first` is called on a flow that doesn't satisfy the predicate it throws a `NoSuchElementException` with the message `"Expected at least one element matching the predicate $predicate"`. The use of `$predicate` implies printing out the lambda however, the lambda's pointer is printed instead.
As far as I know, getting the lambda's string representation is not feasible. Therefore I feel it is best to remove `$predicate` from the error message to make it more readable and remove unnecessary information.
For example, running
`flowOf(1, 2, 3).first {it > 4}` https://pl.kotl.in/jjalTWjTt
returns the error message
```
Exception in thread "main" java.util.NoSuchElementException: Expected at least one element matching the predicate Function2&amp;lt;java.lang.Integer, …
```

Remove unnecessary lambda pointer from first(predicate) error message.

---

benchmarks/src/jmh/kotlin/benchmarks/flow/scrabble/ShakespearePlaysScrabble.kt

The function was deprecated with warning in Kotlin 1.5. In Kotlin 2.1 the deprecation level will be raised to error.
This is a blocker for https://youtrack.jetbrains.com/issue/KT-71628

Replace a usage of deprecated String.toLowerCase()

---

README.md

A bit easier and more convenient to find quickly

Add API reference badge to README.md

---

kotlinx-coroutines-core/wasmWasi/src/EventLoop.kt

Before, the event loop was only set when a non-delayed action was being scheduled.
Fixes #4239

Set the event loop whenever DefaultExecutor is accessed

---

kotlinx-coroutines-core/native/src/EventLoop.kt

The function was deprecated with warning in Kotlin 1.9. In Kotlin 2.1 the deprecation level will be raised to error.
See KT-71628

Replace a usage of deprecated getTimeNanos() in K/N

---

integration-testing/.gitignore
integration-testing/README.md
integration-testing/build.gradle
integration-testing/jpmsTest/build.gradle.kts
integration-testing/jpmsTest/src/debugDynamicAgentJpmsTest/java/module-info.java
integration-testing/jpmsTest/src/debugDynamicAgentJpmsTest/kotlin/DynamicAttachDebugJpmsTest.kt
integration-testing/settings.gradle
kotlinx-coroutines-core/api/kotlinx-coroutines-core.api
kotlinx-coroutines-core/build.gradle.kts
kotlinx-coroutines-core/jvm/resources/META-INF/com.android.tools/proguard/coroutines.pro
kotlinx-coroutines-core/jvm/resources/META-INF/com.android.tools/r8/coroutines.pro
kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro
kotlinx-coroutines-core/jvm/src/debug/internal/AgentInstallationType.kt
kotlinx-coroutines-core/jvm/src/debug/internal/AgentPremain.kt
kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbesImpl.kt
kotlinx-coroutines-core/jvm/src/module-info.java
kotlinx-coroutines-debug/build.gradle.kts
kotlinx-coroutines-debug/src/Attach.kt
kotlinx-coroutines-debug/src/NoOpProbes.kt
kotlinx-coroutines-debug/src/module-info.java

https://youtrack.jetbrains.com/issue/IDEA-359879/coroutines-debugging-Investigate-split-package-problem
https://github.com/Kotlin/kotlinx.coroutines/issues/4124

Fix 'kotlinx.coroutines.debug' & 'kotlinx.coroutines.debug.internal' split package problem

---

kotlinx-coroutines-core/jvm/test/jdk8/future/FutureTest.kt

Star imports of `java.util.concurrent.atomic.*` and `kotlin.concurrent.*` will lead to the compilation error: once Atomic classes are introduced in `kotlin.concurrent` package, they will conflict with Java atomic classes, which have the same names.

Remove star import of the packages, which contain conflicting declarations

---

kotlinx-coroutines-core/common/src/channels/BufferOverflow.kt
kotlinx-coroutines-core/common/src/channels/Channel.kt
kotlinx-coroutines-core/common/src/channels/Produce.kt
kotlinx-coroutines-core/common/test/channels/BufferedChannelTest.kt
kotlinx-coroutines-core/common/test/channels/ProduceTest.kt
kotlinx-coroutines-core/common/test/channels/RendezvousChannelTest.kt
kotlinx-coroutines-core/common/test/selects/SelectRendezvousChannelTest.kt
kotlinx-coroutines-core/jvm/src/channels/Actor.kt
kotlinx-coroutines-core/jvm/test/channels/CancelledChannelLeakTest.kt

Note: a major piece of terminology that's changed in this is that when a channel is closed with a cause, it's no longer called a "failed channel". I found it immensely confusing to have `channelResult.isClosed` that means "the channel is closed", but `channelResult.isFailed` that doesn't mean "the channel is failed". Also, every cancelled channel is a "failed" channel by the definition of being closed with a cause, which doesn't seem to be the intention. So, I suggest that we remove mentions of "failed channels" throughout and replace them with "closed with a cause". Luckily, it's only relevant in a limited number of places.

Update the documentation for the Channel interface

---

kotlinx-coroutines-core/common/src/flow/operators/Limit.kt
kotlinx-coroutines-core/common/test/flow/terminal/FirstTest.kt

collectWhile catches AbortFlowException even if the CoroutineScope is cancelled while waiting on child tasks, causing it to fail to respond to cancel().

Rethrow AbortFlowException upon cancellation (#4034)

---

kotlinx-coroutines-core/jvm/src/Exceptions.kt
kotlinx-coroutines-core/jvm/test/JobCancellationExceptionSerializerTest.kt

On JVM `JobCancellationException` is Serializable, but `job` field is nullable and Transient:
```kt
@JvmField @Transient internal actual val job: Job
```
as a result `job` is null after deserialization, so when `hashCode()` is ran on the exception, it results in null pointer exception. This change is to fix this issue by handling nullability of the `job` field.
Exception from Production while running Apache Flink:
```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "this.job" is null
at kotlinx.coroutines.JobCancellationException.hashCode(Exceptions.kt:65)
at java.base/java.util.HashMap.hash(Unknown Source)
at java.base/java.util.HashMap.put(Unknown Source)
at java.base/java.util.HashSet.add(Unknown Source)
at …
```

fix(jvm): make job cancellation hashcode not fail after deserialization

---

kotlinx-coroutines-core/jvm/src/Exceptions.kt
kotlinx-coroutines-core/jvm/src/flow/internal/FlowExceptions.kt
kotlinx-coroutines-core/jvm/src/internal/CoroutineExceptionHandlerImpl.kt

Revisit all @Transient usages in coroutines

---

kotlinx-coroutines-test/common/src/internal/TestMainDispatcher.kt
kotlinx-coroutines-test/jvm/src/internal/TestMainDispatcherJvm.kt
ui/kotlinx-coroutines-android/android-unit-tests/test/ordered/tests/FirstMockedMainTest.kt

Before this change, the following could happen on the JVM:
* `kotlinx.coroutines.test` accesses `Dispatchers.Main` before `setMain` is called.
* `Dispatchers.Main` attempts to initialize *some other* Main dispatcher in addition to the `kotlinx-coroutines-test` Main dispatcher, if there is one.
* If the `kotlinx-coroutines-android` artifact is present + its R8 rules are used to minify the tests, it's illegal to attempt to fail to create a `Main` dispatcher. `SUPPORT_MISSING = false` ensures that attempting to create a Main dispatcher fails immediately, in the call frame that attempts the creation, not waiting for `Dispatchers.Main` to be meaningfully used.
In total, `kotlinx-coroutines-test` + `kotlinx-coroutines-android` + R8 minification of tests leads to some patterns of …

Do not initialize non-mocked Dispatchers.Main unnecessarily

---

kotlinx-coroutines-debug/build.gradle.kts

- From version 1.10.0, kotlinx-coroutines-debug no longer bundles bytebuddy and has stopped using its custom shadowJar task.
- https://github.com/Kotlin/kotlinx.coroutines/pull/4266
- It now conflicts with build-logic that were configured globally for Java 9 module system.
- https://github.com/Kotlin/kotlinx.coroutines/blob/ee92d16c4b48345648dcd8bb15f11ab9c3747f67/buildSrc/src/main/kotlin/Java9Modularity.kt#L137-L146
- This conflict of module-info.class causes issues in programs that use ASM-based tools like Jacoco, so it needs to be fixed.

resolve conflicts of module-info.class on kotlinx-coroutine-debug

---

kotlinx-coroutines-test/common/src/TestScope.kt

The [docs for the `TestScope` factory function](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-scope.html) are supposed to include a nested list, but the indentation is wrong so the KDoc is a bit confusing.
Before:
After:

Fix TestScope factory KDoc formatting

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt
kotlinx-coroutines-core/common/src/internal/LimitedDispatcher.kt
kotlinx-coroutines-core/common/test/LimitedParallelismSharedTest.kt
kotlinx-coroutines-core/jvm/test/LimitedParallelismStressTest.kt

A tiny self-contained piece of https://github.com/Kotlin/kotlinx.coroutines/pull/4277

Reach target parallelism in .limitedParallelism of failing dispatchers

---

buildSrc/src/main/kotlin/Publishing.kt

This replaces the custom name with an SPDX identifier to enable tooling to automatically detect the correct license. Using an SPDX identifier is recommended [by the official Maven documentation](https://maven.apache.org/pom.html#Licenses).
See https://spdx.org/licenses/Apache-2.0.html

Use SPDX identifier in POMs

---

kotlinx-coroutines-core/common/src/CoroutineScope.kt

`cancallation` -> `cancellation`

Fix typo in CoroutineScope KDocs

---

kotlinx-coroutines-core/common/src/flow/Channels.kt

Fix receiveAsFlow not mentioning the prompt cancellation guarantee

---

kotlinx-coroutines-core/common/src/flow/operators/Context.kt

Fix the incorrect documentation for Flow.conflate

---

docs/topics/cancellation-and-timeouts.md
docs/topics/composing-suspending-functions.md
docs/topics/coroutine-context-and-dispatchers.md
docs/topics/coroutines-basics.md
kotlinx-coroutines-core/common/src/CompletableJob.kt
kotlinx-coroutines-core/common/src/CoroutineScope.kt
kotlinx-coroutines-core/common/src/Job.kt
kotlinx-coroutines-core/common/src/Supervisor.kt
kotlinx-coroutines-core/common/src/Yield.kt
kotlinx-coroutines-core/jvm/src/ThreadContextElement.kt
kotlinx-coroutines-core/jvm/test/guide/example-cancel-04.kt

This pull request improves the documentation and code comments in the repository. 
The changes include:
- Clarifications and corrections in the `cancellation-and-timeouts.md` document.
- Enhanced explanations and added references in `composing-suspending-functions.md`.
- Improved readability and structure in `coroutine-context-and-dispatchers.md`.
- Various grammatical and stylistic improvements across multiple documentation files.
- Code comments updated for better clarity and accuracy in `CompletableJob.kt`, `CoroutineScope.kt`, `Job.kt`, `Supervisor.kt`, `Yield.kt`, and `ThreadContextElement.kt.`

Minor Improvements to the documentation and code comments

---

buildSrc/src/main/kotlin/kotlin-multiplatform-conventions.gradle.kts

The default mode is changing from 'disable' to 'enable' in KT-71768. However, core libraries will migrate to the new '-jvm-default=enable' mode explicitly, once they update to Kotlin 2.2, see KT-72051.

Enable '-jvm-default=disable' explicitly to prevent API dump changes

---

buildSrc/src/main/kotlin/kotlin-multiplatform-conventions.gradle.kts

Apparently this branch is used in user projects to build both 2.1.20 and 2.2.0, and 2.1.20 did not support the new `-jvm-default` (KT-73007).

Use -Xjvm-default instead of -jvm-default

---

buildSrc/src/main/kotlin/kotlin-multiplatform-conventions.gradle.kts

The default mode is changing from 'disable' to 'enable' in KT-71768. However, core libraries will migrate to the new '-jvm-default=enable' mode explicitly, once they update to Kotlin 2.2, see KT-72051.

Enable '-Xjvm-default=disable' explicitly to prevent API dump changes

---

kotlinx-coroutines-core/jvm/src/Dispatchers.kt
kotlinx-coroutines-core/jvm/src/ThreadPoolDispatcher.kt

- Simplify newFixedThreadPoolContext using a scope function
- Remove unused import

Simplify newFixedThreadPoolContext using apply and remove unused import

---

kotlinx-coroutines-core/common/src/flow/Migration.kt

It's necessary for merging a fix for KT-74325
Duplicate of #4388 but to `develop` branch

Specify explicit return types for some public API functions

---

kotlinx-coroutines-core/common/src/flow/Flow.kt

In this part, it says that it checks whether it's the same coroutine, but in the [actual implementation](https://github.com/Kotlin/kotlinx.coroutines/blob/465e29d325841244f3a1aac2e13073bc965f9736/kotlinx-coroutines-core/common/src/flow/internal/SafeCollector.common.kt#L23), it checks whether it's the same CoroutineContext rather than the same coroutine.
Specifically, in the case of the withContext example, although it internally creates a DispatchedCoroutine object, this is only for context switching, and it still maintains the same coroutine.
```
val myFlow = flow {
// GlobalScope.launch { // is prohibited
// launch(Dispatchers.IO) { // is prohibited
// withContext(CoroutineName("myFlow")) { // is prohibited
emit(1) // OK
coroutineScope {
emit(2) // OK -- still the same coroutine
}
}
``` …

Fix the explanation of flow emit constraints

---

kotlinx-coroutines-core/jvm/src/Builders.kt
kotlinx-coroutines-core/jvm/test/ExecutorsTest.kt
kotlinx-coroutines-core/jvm/test/RunBlockingJvmTest.kt

Reliably run finalizers even if `runBlocking` got interrupted.

---

buildSrc/src/main/kotlin/pub-conventions.gradle.kts

Original implementation:
https://github.com/vanniktech/gradle-maven-publish-plugin/blob/f22bd35c84c3df28700db4ca3de11d5b78a29fde/plugin/src/main/kotlin/com/vanniktech/maven/publish/Platform.kt#L472 Thanks, @vanniktech!
The issue with the replaced implementation is that it only packs the jar, without registering the publication variant. Checking the sources of `java { withSourcesJar() }`, we see the corresponding logic, but given that we can instead invoke it directly, no need to reimplement it.
Fixes #4112

Advertise source jars for JVM-only libraries

---

kotlinx-coroutines-core/jvm/src/Exceptions.kt

Looking at the git diff, seems like this change was first made to address `job` being null after deserialization, but then a commit afterwards made `job` a truly non-nullable computed property based on `_job`, thus this safe call is unnecessary and misleading. This was likely overlooked in the latter commit since everything compiled and ran just fine

Nit: Remove vestigial safe call in jvm Exceptions.kt

---

kotlinx-coroutines-core/common/src/flow/operators/Context.kt

In this part, it says :
Otherwise, if changing dispatcher is required, it collects flow emissions in one coroutine that is run using a specified [context] and emits them from another coroutines with the original collector's context
and this explanation is reversed.
If flowOn passes CoroutineDispatcher, then the flow's emissions are performed in a coroutine running with the specified CoroutineContext not collector's context. The collector's original context is used to collect values emitted from the flow. 
You can easily configure this by running below code.
```
val numberFlow: Flow<Int> = flow {
for (number in 1..3) {
println("[${Thread.currentThread().name}] Emitting: $number")
emit(number)
delay(1000)
}
}
fun main() = runBlocking<Unit> {
numberFlow
.flowOn(Dispatchers.IO) 
.collect { …
```

Fix an explanation of flowOn Operator

---

docs/topics/coroutines-guide.md

The original URL
https://play.kotlinlang.org/hands-on/Introduction%20to%20Coroutines%20and%20Channels
redirects to
https://kotlinlang.org/docs/kotlin-hands-on.html,
and the `Introduction to Kotlin coroutines and channels﻿` subsection links you straight back to
https://kotlinlang.org/docs/coroutines-and-channels.html
So I just applied transitive closure :)
Also, this way it becomes consistent with the left-hand-side navigation pane [here](https://kotlinlang.org/docs/coroutines-guide.html#table-of-contents):

docs: Coroutines guide: update URL

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/CommunityProjectsBuild.kt
buildSrc/src/main/kotlin/Projects.kt
gradle.properties
integration-testing/build.gradle.kts
integration-testing/src/debugDynamicAgentTest/kotlin/DynamicAttachDebugTest.kt
kotlinx-coroutines-core/build.gradle.kts

See <https://github.com/Kotlin/kotlinx.coroutines/pull/4392/files#r2016110128>
for an explanation of the benefits of this.
Additionally, the `integration-testing` no longer sees the `kotlinx.coroutines` having a `SNAPSHOT` version (which is always the case) as a valid reason to start looking at development repositories for packages.

Use providers.gradle property instead of rootProject.properties in the build scripts

---

kotlinx-coroutines-test/api/kotlinx-coroutines-test.klib.api
kotlinx-coroutines-test/wasmJs/src/TestBuilders.kt
kotlinx-coroutines-test/wasmJs/src/internal/JsPromiseInterfaceForTesting.kt

The suppressed warning was indicating something wrong with the code. After [KT-63348](https://youtrack.jetbrains.com/issue/KT-63348) we get a compilation error
```
file:///C:/Users/Kirill/IdeaProjects/user-projects/kotlinx.coroutines/build/wasm/packages/kotlinx-coroutines-testWasm-test/kotlin/kotlinx-coroutines-testWasm-test.uninstantiated.mjs:269
const wasmModule = new WebAssembly.Module(wasmBuffer);
^
CompileError: WebAssembly.Module(): Compiling function #6810:"kotlinx.coroutines.test.createTestResult" failed: call[0] expected type (ref null 6), found call of type externref @+775164
at instantiate (file:///C:/Users/Kirill/IdeaProjects/user-projects/kotlinx.coroutines/build/wasm/packages/kotlinx-coroutines-testWasm-test/kotlin/kotlinx-coroutines-testWasm-test.uninstantiated.mjs:269:28) …
```

Fix wasm compilation in user project branch

---

kotlinx-coroutines-test/api/kotlinx-coroutines-test.klib.api
kotlinx-coroutines-test/wasmJs/src/TestBuilders.kt
kotlinx-coroutines-test/wasmJs/src/internal/JsPromiseInterfaceForTesting.kt

The suppressed warning was indicating something wrong with the code. After [KT-63348](https://youtrack.jetbrains.com/issue/KT-63348) we get a compilation error
```
file:///C:/Users/Kirill/IdeaProjects/user-projects/kotlinx.coroutines/build/wasm/packages/kotlinx-coroutines-testWasm-test/kotlin/kotlinx-coroutines-testWasm-test.uninstantiated.mjs:269
const wasmModule = new WebAssembly.Module(wasmBuffer);
^
CompileError: WebAssembly.Module(): Compiling function #6810:"kotlinx.coroutines.test.createTestResult" failed: call[0] expected type (ref null 6), found call of type externref @+775164
at instantiate (file:///C:/Users/Kirill/IdeaProjects/user-projects/kotlinx.coroutines/build/wasm/packages/kotlinx-coroutines-testWasm-test/kotlin/kotlinx-coroutines-testWasm-test.uninstantiated.mjs:269:28) …
```

Fix wasm compilation after KT-63348

---

kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt

Fixed the typo which was introduced in the following PR:
https://github.com/Kotlin/kotlinx.coroutines/pull/4272

Fix typo in Undispatched.kt

---

kotlinx-coroutines-core/common/src/CancellableContinuation.kt

- Corrects some grammatical issues.
- Fixes typo (withing -> within).
- Ensures consistent terminology (Canceled -> Cancelled).

Fix documentation comments in `CancellableContinutation.kt`

---

kotlinx-coroutines-core/common/src/AbstractCoroutine.kt

Removed an outdated comment that incorrectly stated active has a default value.
The default value was removed in this PR: https://github.com/Kotlin/kotlinx.coroutines/pull/2512/files

Fix outdated documentation in AbstractCoroutine.kt

---

kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt

Renamed `backgroundDispatcher` to `dispatcher` to match the variable name in the sample code.
The variable name was renamed to `dispatcher` in this PR:
https://github.com/Kotlin/kotlinx.coroutines/pull/4098/files

Update outdated comment in `CoroutineDispatcher.kt`

---

kotlinx-coroutines-core/common/src/flow/SharedFlow.kt

https://youtrack.jetbrains.com/issue/KT-22786/Returns-are-not-allowed-for-expression-body-functions-and-are-allowed-when-an-inline-lambda-is-added

Convert return in expression body to labeled return in preparation for KT-22786

---

kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt
test-utils/common/src/MainDispatcherTestBase.kt

Ensure consistent `delay` behavior in `immediate` across platforms

---

kotlinx-coroutines-core/common/src/flow/SharingStarted.kt

In this case, `StartLazily` uses `flow`, but since it simply collects `subscriptionCount` and processes it, there is no need to use SafeFlow and consume additional resources for context checks.
```
private class StartedLazily : SharingStarted {
override fun command(subscriptionCount: StateFlow<Int>): Flow<SharingCommand> = flow { 
var started = false
subscriptionCount.collect { count ->
if (count > 0 && !started) {
started = true
emit(SharingCommand.START)
}
}
}
override fun toString(): String = "SharingStarted.Lazily"
}
```
In other words, because it only collects data from another Flow and passes it along without executing any custom logic which switches coroutine context(similar to operators like `map` or `filter`), it can use `unsafeFlow` to skip context checks and reduce computing …

Improve performance of SharingStarted.StartedLazily by changing flow to unsafeFlow

---

kotlinx-coroutines-core/jvm/test/channels/ChannelSelectStressTest.kt

It's possible for another sender to close the channel between incrementing `sent` and suspending for `select`. If that happens, the `select` just throws `CancellationException`, cancelling the coroutine and causing an element to be missing at the end of the test.

Fix flakiness in `ChannelSelectStressTest`.

---

kotlinx-coroutines-core/jvm/test/flow/StateFlowStressTest.kt

There's no guarantee that any particular collector will ever encounter a value emitted by a particular emitter. It's entirely possible for the value to be overwritten by a different emitter before the collector gets a chance to collect it. It's very unlikely for a collector to miss the second half of all values emitted by a particular emitter, but it is still possible and this causes the test to be flaky.

Fix a flaky check and a TSan violation in `StateFlowStressTest`.

---

README.md

It's been Kotlin 2.1.0 for three patch releases already, but the readme wrongly says 2.0.0.

Update Readme to say Kotlin 2.1.0 to match the reality

---

kotlinx-coroutines-core/common/src/flow/operators/Errors.kt

replaced unsafe `coroutineContext` with `currentCoroutineContext()`

Replaced coroutineContext to currentCoroutineContext in Flow.catchImpl method for safety
